#959 Add unit tests for Norm load model
DARMA-tasking/vt pull request #1012
Opened 2020-09-01 15:16 UTC by JacobDomagala

Fixes #959 

Part 2 of adding unit tests for load models (part 1 -> https://github.com/DARMA-tasking/vt/pull/1001)

Add unit tests for following load models:
- [ ] - Norm
- [ ] - CommOverhead
- [ ] - SelectSubphases

2020-09-01 15:19 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collection/test_model_norm.nompi.cc  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6105410&bid=19985057)

2020-09-02 15:47 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collection/test_model_comm_overhead.nompi.cc  2
- tests/unit/collection/test_model_norm.nompi.cc  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6105410&bid=19985057)

2020-09-02 18:24 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collection/test_model_select_subphases.nompi.cc  13
- tests/unit/collection/test_model_comm_overhead.nompi.cc  3
- tests/unit/collection/test_model_norm.nompi.cc  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6105410&bid=19985057)

2020-09-02 18:36 UTC, PhilMiller commented on tests/unit/collection/test_model_norm.nompi.cc
> +    std::make_shared<Norm>(std::make_shared<StubModel>(), std::exp(800));
Is there a reason not to use and test with a power argument of `double inf = std::numeric_limits<double>::infinity();` here?

2020-09-02 18:39 UTC, PhilMiller commented
This generally looks good. Thanks!

2020-09-02 18:50 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collection/test_model_select_subphases.nompi.cc  13
- tests/unit/collection/test_model_comm_overhead.nompi.cc  3
- tests/unit/collection/test_model_norm.nompi.cc  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6105410&bid=19985057)

2020-09-02 18:51 UTC, JacobDomagala commented on tests/unit/collection/test_model_norm.nompi.cc
> +    std::make_shared<Norm>(std::make_shared<StubModel>(), std::exp(800));
No particular reason. The numeric_limits looks better, thanks!

2020-09-08 14:39 UTC, cz4rs approved these changes
Looks good to me

2020-09-08 20:41 UTC, PhilMiller approved these changes

2020-09-09 17:39 UTC, lifflander approved these changes
Looks great, let's rebase and merge

2020-09-09 17:40 UTC, lifflander commented
I'm kicking off the extended tests for this one just to be sure. But, I think this is good.

2020-09-09 20:27 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collection/test_model_select_subphases.nompi.cc  13
- tests/unit/collection/test_model_comm_overhead.nompi.cc  3
- tests/unit/collection/test_model_norm.nompi.cc  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6105410&bid=19985057)

2020-09-09 21:12 UTC, PhilMiller requested changes
In light of the broader object lifecycle issue identified in #1034, could these tests have `updateLoads()` calls added in the appropriate spots.

2020-09-10 16:17 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collection/test_model_select_subphases.nompi.cc  13
- tests/unit/collection/test_model_comm_overhead.nompi.cc  3
- tests/unit/collection/test_model_norm.nompi.cc  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6105410&bid=19985057)

2020-09-10 16:21 UTC, JacobDomagala commented
> In light of the broader object lifecycle issue identified in #1034, could these tests have `updateLoads()` calls added in the appropriate spots.

Updated.

2020-09-10 16:22 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collection/test_model_select_subphases.nompi.cc  13
- tests/unit/collection/test_model_comm_overhead.nompi.cc  3
- tests/unit/collection/test_model_norm.nompi.cc  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6105410&bid=19985057)

2020-09-10 16:31 UTC, PhilMiller approved these changes

2020-09-10 17:40 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collection/test_model_select_subphases.nompi.cc  13
- tests/unit/collection/test_model_comm_overhead.nompi.cc  3
- tests/unit/collection/test_model_norm.nompi.cc  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6105410&bid=19985057)

2020-09-11 01:11 UTC, lifflander commented
@JacobDomagala Can you rebase this so we can get it merged? The test failure looks spurious. I just re-ran it.

2020-09-11 09:01 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collection/test_model_select_subphases.nompi.cc  13
- tests/unit/collection/test_model_comm_overhead.nompi.cc  3
- tests/unit/collection/test_model_norm.nompi.cc  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6105410&bid=19985057)

2020-09-11 17:31 UTC, merged