1033 Add getter for subphase on element stats
DARMA-tasking/vt pull request #1038
Opened 2020-09-10 17:27 UTC by lifflander

Fixes #1033

2020-09-10 17:28 UTC, nlslatt approved these changes

2020-09-10 17:36 UTC, JacobDomagala approved these changes

2020-09-10 17:51 UTC, nlslatt requested changes

2020-09-10 17:51 UTC, nlslatt commented on src/vt/vrt/collection/balance/elm_stats.cc
> +SubphaseType ElementStats::getSubPhase() const {
Looks like it needs to be `ElementStats::SubphaseType`.

2020-09-10 18:06 UTC, lifflander commented on src/vt/vrt/collection/balance/elm_stats.cc
> +SubphaseType ElementStats::getSubPhase() const {
Just fixed

2020-09-10 18:19 UTC, nlslatt approved these changes

2020-09-11 18:17 UTC, PhilMiller approved these changes

2020-09-13 03:51 UTC, merged