1098 Enable assertions during CI when release builds are used
DARMA-tasking/vt pull request #1107
Opened 2020-10-12 16:00 UTC by JacobDomagala

2020-10-12 20:37 UTC, lifflander requested changes

2020-10-12 20:37 UTC, lifflander commented on .github/workflows/dockerimage-clang-3.9-ubuntu-mpich.yml
> +      VT_CI_BUILD: 1
The workflow files are generated. Instead of editing them, you should edit `vt/scripts/workflows.ini` and `vt/scripts/workflow-template.yml`. Then, you can run this command to generate:

```bash
./scripts/generate-workflow.pl ./scripts/workflow-template.yml ./scripts/workflows.ini
````

2020-10-12 21:58 UTC, JacobDomagala commented on .github/workflows/dockerimage-clang-3.9-ubuntu-mpich.yml
> +      VT_CI_BUILD: 1
It even says on top of the workflow files that there're generated. My bad.

2020-10-13 01:50 UTC, lifflander commented on .github/workflows/dockerimage-clang-3.9-ubuntu-mpich.yml
> +      VT_CI_BUILD: 1
No problem... Looks good!

2020-10-13 01:51 UTC, lifflander approved these changes
Looks good now! :)

2020-10-13 13:42 UTC, merged

2020-10-13 15:48 UTC, PhilMiller commented on cmake/define_build_types.cmake
> +  if (loop_build_type STREQUAL "debug" OR ${vt_ci_build})
This seems to have broken manual builds outside the CI setting, with an error as follows:

```
CMake Error at cmake/define_build_types.cmake:219 (if):
  if given arguments:

    "loop_build_type" "STREQUAL" "debug" "OR"

  Unknown arguments specified
Call Stack (most recent call first):
  src/CMakeLists.txt:275 (include)
```

The variable expansion `${vt_ci_build}` seems to be an empty string, causing a CMake syntax error.

2020-10-13 15:50 UTC, PhilMiller commented on cmake/define_build_types.cmake
> +  if (loop_build_type STREQUAL "debug" OR ${vt_ci_build})
I was building with the command
> `cmake /projects/empire/users/pbmille/repos/vt/ -DCMAKE_BUILD_TYPE=RelWithDebInfo`

to get that error.

When I run
> `cmake /projects/empire/users/pbmille/repos/vt/ -DCMAKE_BUILD_TYPE=RelWithDebInfo -Dvt_ci_build=False`

It succeeds

2020-10-13 16:19 UTC, JacobDomagala commented on cmake/define_build_types.cmake
> +  if (loop_build_type STREQUAL "debug" OR ${vt_ci_build})
Addressed the issue in https://github.com/DARMA-tasking/vt/pull/1109