#1079: Rewrote sucessor to parent epoch in all associated files
DARMA-tasking/vt pull request #1130
Opened 2020-10-28 04:17 UTC by bradybray

2020-10-28 16:43 UTC, PhilMiller requested changes
So, I realize that the description in the issue was not entirely explicit. The captured 'Successor' epoch is the **parent**, not the child. The epochs make a tree, with all children terminating before a parent terminates. That's what equates parent<->successor.

2020-10-28 17:08 UTC, PhilMiller approved these changes

2020-11-05 03:02 UTC, bradybray commented
> 
> 
> Looks good to me!

@PhilMiller @lifflander There appears to be a problem with the python version used for brew on OS X. Do either of you know anything about this?

2020-11-10 17:50 UTC, lifflander approved these changes

2021-04-20 23:07 UTC, merged