903: Implement trace-only mode for vt
DARMA-tasking/vt pull request #1182
Opened 2020-12-15 19:13 UTC by JacobDomagala

Fixes #903 

Example usage: 
```
#include "vt/trace/trace.h"

int main(int argc, char** argv) {

  MPI_Init(&argc, &argv);

  ::vt::trace::Trace myTrace("TestApp");

  myTrace.initializeStandalone(MPI_COMM_WORLD, 0);
  // Do MPI related work here
  myTrace.finalizeStandalone();

  MPI_Finalize();
}
```

It's also possible use existing API for tracing such as :
- enableTracing
- disableTracing
- flushTracesFile

2020-12-18 00:50 UTC, nmm0 approved these changes
Looks good to me! Quick question -- would it be straightforward to have a minimal header to include just the trace API? I think it would help reducing compile times not having to include runtime headers.

2021-01-04 20:01 UTC, PhilMiller commented
The code changes generally look fine to me.

The diff coverage check is a reminder that we don't seem to have suitably targeted testing for the tracing subsystem. Perhaps that should be added.

2021-01-19 19:25 UTC, nmm0 requested changes
Additionally, could you change it from replacing the vt library to adding a separate trace library (maybe enabled by the cmake flag)? This way is simpler for the end user. In our use case in NimbleSM it would make our build system logic significantly easier.

2021-01-19 19:25 UTC, nmm0 commented on src/CMakeLists.txt
> +      DESTINATION "include/${DIR}"
A weird cmake-ism -- DIR here contains the absolute path so installing is installing the headers to install-dir/include/absolutepath/ so the path is broken.

2021-01-27 22:33 UTC, JacobDomagala commented
@nmm0  I've updated the PR (also updated the description on top with example CMake usage). Let me know if there's anything you'd want to be added. 
In the meantime i will try to create CI tests for vt-trace target and will try to add some documentation.

2021-02-03 00:06 UTC, lifflander reviewed
I'm seeing this error when trying to compile with trace-only:

```
[ 86%] Built target nimble
[ 90%] Building CXX object src/CMakeFiles/NimbleSM_MPI.dir/nimble_mpi_main.cc.o
In file included from /Users/jliffla/codes/collision/NimbleSM/src/nimble_mpi_main.cc:55:
In file included from /Users/jliffla/codes/vt/vt-install-clang-9/include/vt-trace/vt/trace/trace_lite.h:51:
In file included from /Users/jliffla/codes/vt/vt-install-clang-9/include/vt-trace/vt/trace/trace_user_event.h:56:
In file included from /Users/jliffla/codes/vt/vt-install-clang-9/include/vt-trace/vt/context/context.h:54:
/Users/jliffla/codes/vt/vt-install-clang-9/include/vt-trace/vt/utils/tls/tls.h:53:12: fatal error: 'vt/utils/tls/omp_tls.h' file not found
  #include "vt/utils/tls/omp_tls.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

I think that @cz4rs's work on disabling threading might be useful here for the trace-only mode where we don't need threading at all.

2021-02-03 00:08 UTC, lifflander commented
Threading should probably just be disabled by default. Or, we could just include those threading files (but I think this is unnecessary).

2021-02-03 00:19 UTC, lifflander commented
I pushed some changes. Once @jstrzebonski gets the vt-sample-project working, let's add the trace-only build to it for testing.

2021-02-04 15:57 UTC, jstrzebonski commented
@JacobDomagala @lifflander 
#1230 is merged

2021-02-05 16:15 UTC, JacobDomagala commented on ci/build_cpp.sh
> +    git clone https://github.com/DARMA-tasking/vt-sample-project -b sample-use-of-trace-only-vt
Temporarily using non-master branch

2021-02-05 16:21 UTC, JacobDomagala commented on src/vt/runtime/component/diagnostic_value.h
> +/**1
Fixed

2021-02-09 15:59 UTC, JacobDomagala commented on ci/build_cpp.sh
> +    git clone https://github.com/DARMA-tasking/vt-sample-project -b sample-use-of-trace-only-vt
Will be changed to master once https://github.com/DARMA-tasking/vt-sample-project/issues/1 is merged

2021-02-09 18:55 UTC, nmm0 requested changes
Just a minor change

2021-02-09 18:55 UTC, nmm0 commented on src/CMakeLists.txt
> +  include(../cmake/trace_only_functions.cmake)
I think this include line needs to be pulled outside the if statement. There are some functions later that are defined in this file and CMake errors out if vt_trace_only is set to OFF

2021-02-09 22:00 UTC, JacobDomagala commented on src/CMakeLists.txt
> +  include(../cmake/trace_only_functions.cmake)
That's kinda weird. This file only defines two functions (create_trace_only_target and set_trace_only_config) and both are called only when vt_trace_only is set to 1.

2021-02-09 22:04 UTC, JacobDomagala commented on src/CMakeLists.txt
> +  include(../cmake/trace_only_functions.cmake)
Anyways I've updated the PR.

2021-02-09 22:23 UTC, lifflander approved these changes
Looks good

2021-02-09 23:15 UTC, nmm0 approved these changes
Works for me!

2021-02-10 10:50 UTC, merged