1202 Write container build for Intel 21 OneAPI
DARMA-tasking/vt pull request #1203
Opened 2021-01-06 19:12 UTC by lifflander

Fixes #1202

2021-07-05 14:16 UTC, cz4rs commented on ci/docker/ubuntu-18.04-intel-oneapi-cpp.dockerfile
> +    intel-oneapi-compiler-dpcpp-cpp \
TODO: check if this can be slimmed down further (using only `classic` package)

2021-07-05 14:17 UTC, cz4rs commented on ci/docker/ubuntu-18.04-intel-oneapi-cpp.dockerfile
> +ENV CCL_CONFIGURATION='cpu_gpu_dpcpp'
FIXME: this is copy-pasta from Intel's dockerfiles, remove unnecessary variables

2021-07-06 15:41 UTC, cz4rs commented on ci/docker/ubuntu-18.04-intel-oneapi-cpp.dockerfile
> +ENV CCL_CONFIGURATION='cpu_gpu_dpcpp'
I have removed the ones that were obviously obsolete.

2021-07-06 15:43 UTC, cz4rs commented on ci/docker/ubuntu-18.04-intel-oneapi-cpp.dockerfile
> +    intel-oneapi-compiler-dpcpp-cpp \
In the end, it has boiled down to installing following packages (+ dependencies):
```
    intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic \
    intel-oneapi-mpi-devel
```

2021-07-06 15:49 UTC, cz4rs commented
To give some idea about the size and dependencies installed on top of `os-tools-ubuntu18.04`:
```
root@be71392eb44e:/# apt install --no-install-recommends intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-mpi-devel
Reading package lists... Done
(...)
The following NEW packages will be installed:
  intel-oneapi-common-licensing-2021.3.0 intel-oneapi-common-vars intel-oneapi-compiler-cpp-eclipse-cfg
  intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
  intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2021.3.0
  intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-common-2021.3.0
  intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-runtime-2021.3.0
  intel-oneapi-compiler-dpcpp-cpp-classic-fortran-shared-runtime-2021.3.0
  intel-oneapi-compiler-dpcpp-cpp-common-2021.3.0 intel-oneapi-compiler-dpcpp-cpp-runtime-2021.3.0
  intel-oneapi-compiler-dpcpp-eclipse-cfg intel-oneapi-compiler-shared-2021.3.0
  intel-oneapi-compiler-shared-common-2021.3.0 intel-oneapi-compiler-shared-common-runtime-2021.3.0
  intel-oneapi-compiler-shared-runtime-2021.3.0 intel-oneapi-condaindex
  intel-oneapi-dev-utilities-2021.3.0 intel-oneapi-dev-utilities-eclipse-cfg
  intel-oneapi-dpcpp-cpp-2021.3.0 intel-oneapi-dpcpp-debugger-10.1.2
  intel-oneapi-dpcpp-debugger-eclipse-cfg intel-oneapi-mpi-2021.3.0 intel-oneapi-mpi-devel
  intel-oneapi-mpi-devel-2021.3.0 intel-oneapi-openmp-2021.3.0 intel-oneapi-openmp-common-2021.3.0
  intel-oneapi-tbb-2021.3.0 intel-oneapi-tbb-common-2021.3.0 intel-oneapi-tbb-common-devel-2021.3.0
  intel-oneapi-tbb-devel-2021.3.0
0 upgraded, 30 newly installed, 0 to remove and 6 not upgraded.
Need to get 1008 MB of archives.
After this operation, 3746 MB of additional disk space will be used.
```

The base image [(os-tools-ubuntu18.04)](https://github.com/intel/oneapi-containers/blob/master/images/docker/os-tools-ubuntu18.04/Dockerfile) is pretty lightweight, it just adds Intel repo and a couple of basic tools on top of ubuntu 18.04.

2021-07-20 14:49 UTC, cz4rs commented on ci/docker/ubuntu-18.04-intel-oneapi-cpp.dockerfile
> +ENV CCL_CONFIGURATION='cpu_gpu_dpcpp' \
this configuration could probably be replaced with [setvars.sh setup](https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-linux/top/before-you-begin.html#before-you-begin_GUID-338EB548-7DB6-410E-B4BF-E65C017389C4)

2021-07-26 11:58 UTC, cz4rs commented on ci/docker/ubuntu-18.04-intel-oneapi-cpp.dockerfile
> +ENV CCL_CONFIGURATION='cpu_gpu_dpcpp' \
In the end, it seems like there is no good way to persist the environment between `RUN` instructions (other than using `ENV`). I have trimmed down the configuration and this is probably as good as it gets.

2021-07-26 13:28 UTC, cz4rs commented
I have used `icc-18` pipeline to try out the new Dockerfile on Azure. This is using `icx/icpx` to build `mpich` and then `vt`.

There's only one test failing:
```
119/455 Test #119: vt:TestModelNorm.test_model_norm_3_no_mpi ..........................................***Failed  Error regular expression found in output. Regex=[FAILED]  0.01 sec
2021-07-26T12:40:07.4727770Z Note: Google Test filter = TestModelNorm.test_model_norm_3
2021-07-26T12:40:07.4728205Z [==========] Running 1 test from 1 test suite.
2021-07-26T12:40:07.4729187Z [----------] Global test environment set-up.
2021-07-26T12:40:07.4729786Z [----------] 1 test from TestModelNorm
2021-07-26T12:40:07.4730441Z [ RUN      ] TestModelNorm.test_model_norm_3
2021-07-26T12:40:07.4730911Z /vt/tests/unit/collection/test_model_norm.nompi.cc:208: Failure
2021-07-26T12:40:07.4731355Z Expected equality of these values:
2021-07-26T12:40:07.4731695Z   work_val
2021-07-26T12:40:07.4731996Z     Which is: 1
2021-07-26T12:40:07.4732768Z   expected_norms[obj.id - 1]
2021-07-26T12:40:07.4733125Z     Which is: 60
2021-07-26T12:40:07.4733529Z /vt/tests/unit/collection/test_model_norm.nompi.cc:208: Failure
2021-07-26T12:40:07.4733966Z Expected equality of these values:
2021-07-26T12:40:07.4734433Z   work_val
2021-07-26T12:40:07.4734720Z     Which is: 1
2021-07-26T12:40:07.4735382Z   expected_norms[obj.id - 1]
2021-07-26T12:40:07.4735738Z     Which is: 30
2021-07-26T12:40:07.4736120Z [  FAILED  ] TestModelNorm.test_model_norm_3 (1 ms)
2021-07-26T12:40:07.4736743Z [----------] 1 test from TestModelNorm (1 ms total)
```

2021-07-29 10:17 UTC, cz4rs commented
**TLDR**
`std::isfinite` returns `true` for `std::numeric_limits<double>::infinity()` when using `icpx`

Reduced example @ Compiler Explorer: https://godbolt.org/z/KEqYs1e51

**Context**
We use `std::isfinite` in `Norm::getWork`. Failing test is using `std::numeric_limits<double>::infinity()` as the power value for computing the norm.

After adding following log:
```diff
--- a/src/vt/vrt/collection/balance/model/norm.cc
+++ b/src/vt/vrt/collection/balance/model/norm.cc
@@ -44,6 +44,7 @@
 
 #include "vt/vrt/collection/balance/model/norm.h"
 #include <cmath>
+#include <iostream>
 
 namespace vt { namespace vrt { namespace collection { namespace balance {
 
@@ -60,6 +61,7 @@ TimeType Norm::getWork(ElementIDStruct object, PhaseOffset offset)
   if (offset.subphase != PhaseOffset::WHOLE_PHASE)
     return ComposedModel::getWork(object, offset);
 
+  std::cout << "std::isfinite:\t" << std::boolalpha << std::isfinite(power_) << std::endl;
   if (std::isfinite(power_)) {
     double sum = 0.0;
```

Output using `icpx` (`Intel(R) oneAPI DPC++/C++ Compiler 2021.3.0 (2021.3.0.20210619)`):
```
root@7609992bd94c:/build# ./tests/collection_nompi --gtest_filter=TestModelNorm.test_model_norm_3
(...)
[ RUN      ] TestModelNorm.test_model_norm_3
std::isfinite:	true
/vt/tests/unit/collection/test_model_norm.nompi.cc:209: Failure
Expected equality of these values:
  work_val
    Which is: 1
  expected_norms[obj.id - 1]
    Which is: 60
std::isfinite:	true
/vt/tests/unit/collection/test_model_norm.nompi.cc:209: Failure
Expected equality of these values:
  work_val
    Which is: 1
  expected_norms[obj.id - 1]
    Which is: 30
[  FAILED  ] TestModelNorm.test_model_norm_3 (1 ms)
```

Using gcc / clang:
```
> ./tests/collection_nompi --gtest_filter=TestModelNorm.test_model_norm_3
(...)
[ RUN      ] TestModelNorm.test_model_norm_3
std::isfinite:  false
std::isfinite:  false
[       OK ] TestModelNorm.test_model_norm_3 (0 ms)
(...)
[  PASSED  ] 1 test.
```

2021-07-29 14:22 UTC, PhilMiller commented
I'll report the compiler issue to the lab's point of contact, and I guess investigate a little further

2021-08-06 18:17 UTC, cz4rs commented
Success after adding `-fhonor-infinites` flag:

![image](https://user-images.githubusercontent.com/4639165/128554554-5c414f29-cf1b-4221-bf8c-b1e04de862b6.png)

[build.log](https://github.com/DARMA-tasking/vt/files/6947316/build.log)

2021-08-06 19:10 UTC, cz4rs commented
Explanation:

> The problem is that icx's default floating point model is -fp-model fast
One of the things that -fp-model fast does it that it sets an attribute in the LLVM IR on floating point operations that says they can never yield infinity values.
So, when optimization is turned on, the LLVM IR ends up assuming that the call to `std::isfinite(power)` MUST return true, since the fp model says that inf values will never be generated.
You can use either `-fp-model precise` option, or `-fhonor-infinities` option to tell the compiler that it needs to assume infinities may be generated. Note that a similar problem can occur for NANs. fp-model fast assumes that NANs cannot occur/be generated, and `-fp-model precise` or `-fhonor-nans` will enable NANs .
```
$ icpx -O1 -fp-model precise test.cpp
$ ./a.out
false
$ icpx -O1 -fhonor-infinities test.cpp
$ ./a.out
false
```
> And it was in compiler version 2021.2 where the fp-model default was changed from precise to fast.
This was done purposefully for floating point model compatibility with the Intel classic compiler (ICC/ICL).
 
> the change in 2021.2 ICX was to make fp-model fast the default.  The behavior for NaNs and infinites is in the community LLVM code which we use as the base for our compiler.  The -fhonor and behaviors are from the community and not our additions to LLVM.  We are working with the community on a number of FP related changes we’d like to see from the LLVM community.

2021-08-10 12:43 UTC, cz4rs commented
@lifflander 
I have added `icpx` workflow, compilation and tests pass fine locally. Can you please add a pipeline in Azure?

2021-08-10 17:24 UTC, PhilMiller commented on cmake-modules/SetCXXCompilerFlags.cmake
> +  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fhonor-infinites")
Given that this flag affects behavior of generated code, we should be very cautious about applying it, especially as a workaround for a bug. Though, at least as far as I can tell, it's not going to be inherited by dependent applications.

2021-08-10 18:09 UTC, lifflander commented
@cz4rs I have the pipeline added to Azure now!

2021-08-10 18:22 UTC, cz4rs commented
> @cz4rs I have the pipeline added to Azure now!

Great! I think it's good for merging as long as we get an approval from someone.

2021-08-10 18:26 UTC, cz4rs commented on cmake-modules/SetCXXCompilerFlags.cmake
> +  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fhonor-infinites")
A better option could be to use `target_compile_options` (which can specify `INTERFACE|PUBLIC|PRIVATE` scope), but we don't really use that in `vt` and it would require more changes.

2021-08-10 18:29 UTC, JacobDomagala approved these changes

2021-08-10 18:29 UTC, cz4rs commented on cmake-modules/SetCXXCompilerFlags.cmake
> +  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fhonor-infinites")
Overall, I think this should be fine as is, but we could create a separate issue for some CMake improvements.

2021-11-03 14:46 UTC, cz4rs commented
TODO: use `target_compile_options` instead of global `CMAKE_CXX_FLAGS`

2021-11-04 16:40 UTC, jstrzebonski commented
@cz4rs There are still compilation errors, example:
```bash
FAILED: src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx.o 
/usr/bin/ccache /usr/local/bin/mpicxx -DJSON_USE_IMPLICIT_CONVERSIONS=1 -I/vt/lib/CLI -Irelease -I/vt/src -I/vt/lib/json/include -I/vt/lib/brotli/c/include -I/vt/lib/libfort/lib -isystem /vt/lib/fmt/include -isystem /build/checkpoint/install/include -isystem /build/detector/install/include -Wall -pedantic -Wshadow -Wno-unknown-pragmas -Wsign-compare -ftemplate-backtrace-limit=100 -fhonor-infinites -Werror -O3 -DNDEBUG -fPIC -std=c++14 -MD -MT src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx.o -MF src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx.o.d -o src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx.o -c src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx
In file included from src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx:17:
/vt/src/vt/vrt/collection/balance/model/norm.cc:54:16: error: comparison with NaN always evaluates to false in fast floating point modes [-Werror,-Wtautological-constant-compare]
  vtAssert(not std::isnan(power), "Power must have a real value");
               ^~~~~~~~~~~~~~~~~
/vt/src/vt/configs/error/config_assert.h:156:40: note: expanded from macro 'vtAssert'
    vtAssertImpl(vt_assert_should_fail,cond,str)
                                       ^~~~
/vt/src/vt/configs/error/config_assert.h:126:13: note: expanded from macro 'vtAssertImpl'
      if (!(cond)) {                                                    \
            ^~~~
1 error generated.
```

2021-11-04 16:41 UTC, jstrzebonski requested changes
@cz4rs There are still compilation errors, example:
```bash
FAILED: src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx.o 
/usr/bin/ccache /usr/local/bin/mpicxx -DJSON_USE_IMPLICIT_CONVERSIONS=1 -I/vt/lib/CLI -Irelease -I/vt/src -I/vt/lib/json/include -I/vt/lib/brotli/c/include -I/vt/lib/libfort/lib -isystem /vt/lib/fmt/include -isystem /build/checkpoint/install/include -isystem /build/detector/install/include -Wall -pedantic -Wshadow -Wno-unknown-pragmas -Wsign-compare -ftemplate-backtrace-limit=100 -fhonor-infinites -Werror -O3 -DNDEBUG -fPIC -std=c++14 -MD -MT src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx.o -MF src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx.o.d -o src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx.o -c src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx
In file included from src/CMakeFiles/vt.dir/Unity/unity_12_cxx.cxx:17:
/vt/src/vt/vrt/collection/balance/model/norm.cc:54:16: error: comparison with NaN always evaluates to false in fast floating point modes [-Werror,-Wtautological-constant-compare]
  vtAssert(not std::isnan(power), "Power must have a real value");
               ^~~~~~~~~~~~~~~~~
/vt/src/vt/configs/error/config_assert.h:156:40: note: expanded from macro 'vtAssert'
    vtAssertImpl(vt_assert_should_fail,cond,str)
                                       ^~~~
/vt/src/vt/configs/error/config_assert.h:126:13: note: expanded from macro 'vtAssertImpl'
      if (!(cond)) {                                                    \
            ^~~~
1 error generated.
```

2021-11-04 17:18 UTC, jstrzebonski commented
BTW, you could also add pipeline badge to readme.

2021-11-05 14:49 UTC, cz4rs commented on cmake-modules/SetCXXCompilerFlags.cmake
> +  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fhonor-infinites")
New issue created to handle this in all `vt`: https://github.com/DARMA-tasking/vt/issues/1602.

2021-11-05 18:16 UTC, lifflander commented
Approved... but I can't actually approve it since I'm an author.

2021-11-05 18:16 UTC, merged