1229: Explore enabling debug prints in release builds and assertions
DARMA-tasking/vt pull request #1288
Opened 2021-02-25 22:06 UTC by cz4rs

fixes #1229

2021-02-26 21:18 UTC, cz4rs commented on cmake/define_build_types.cmake
> -if (${VT_DEBUG_FAST})
this was only ever used in `build_vt.pl`

2021-02-26 21:22 UTC, cz4rs commented on cmake/define_build_types.cmake
>    # assume production mode for everything except debug or CI build
the only remaining use for this would be `Production Build` information in the banner:
 ```cpp
#if vt_check_enabled(production)
  features.push_back(vt_feature_str_production);
#endif
 ```

2021-02-26 21:23 UTC, cz4rs commented on scripts/build_vt.pl
> -my $fast_str = "";
after taking a closer look, I have decided to remove the script completely

2021-02-26 22:21 UTC, cz4rs commented on src/vt/configs/debug/debug_masterconfig.h
> -#if !vt_debug_enabled
this no longer depends on build type - we could introduce explicit configuration variable instead (`vt_debug_print_enabled`?)

2021-02-26 22:50 UTC, cz4rs commented on tests/unit/test_parallel_harness.h
> -    std::copy(
random fix: binary name wasn't placed correctly

2021-03-01 15:13 UTC, cz4rs commented on src/vt/configs/features/features_featureswitch.h
> +#define vt_feature_str_fcontext           "fcontext Threading"
added missing string for `fcontext` (and sorted all the strings for clarity)

2021-03-01 15:33 UTC, cz4rs commented
@lifflander 
This was mostly about removing code so far (no categorization done for `Terse, normal, verbose`). I am looking at simplifying things even further if we decide to stick with `vt_debug_print` always enabled, but I need your feedback / thoughts on general direction for logging.
- I haven't measured the impact on build time precisely - looking at the intermediate CI builds, there is some hit, but I have not a comparison with caching disabled yet.
- Also, how often is the configuration below actually used? I'm not sure if keeping it in cmake source is preferential to having it directly in C++ code.
https://github.com/DARMA-tasking/vt/blob/0a4bacbce7788ae72e049ec94691abc4dd515d80/cmake/define_build_types.cmake#L29-L59

2021-03-01 16:58 UTC, cz4rs commented on src/vt/configs/error/config_assert.h
> -#if vt_check_enabled(production)
enabling assertions for release build

note:
There is `#if vt_check_enabled(assert_no_fail)` conditional below that I have not removed yet, but `vt_feature_cmake_assert_no_fail` is not defined anywhere. Should we always enforce failing or create a config option for `assert_no_fail`?

2021-03-01 17:07 UTC, cz4rs commented on cmake/define_build_types.cmake
>    cmake_vt_debug_modes_all
compared to `vt::config::CatEnum` we are missing following categories here:
```cpp
  event        = 1ull<<7,
  rdma_state   = 1ull<<13,
  sequence_vrt = 1ull<<19,
  vrt          = 1ull<<24,
  worker       = 1ull<<26,
```

2021-03-01 18:18 UTC, lifflander commented on cmake/define_build_types.cmake
> -if (${VT_DEBUG_FAST})
We can delete `build_vt.pl` and `build_vt.sh`..they are both old scripts that aren't used anymore AFAIK.

2021-03-01 18:19 UTC, lifflander commented on cmake/define_build_types.cmake
>    # assume production mode for everything except debug or CI build
I think we can remove it then, unless there is another use for it.

2021-03-01 18:22 UTC, lifflander commented on cmake/define_build_types.cmake
>    cmake_vt_debug_modes_all
That was intensional for the most part, but `event` should have probably been included. There's a question of whether we need that distinction now though.

2021-03-01 18:40 UTC, lifflander requested changes

2021-03-01 18:40 UTC, lifflander commented on docs/md/building.md
> -| `vt_fcontext_enabled`            | 1               | Force use of fcontext for threading |
I'm a little confused on the wording here that was changed in a different PR? Does that flag enable fcontext *and* force its use in worker or just enable it?

2021-03-01 18:40 UTC, lifflander commented on scripts/build_vt.pl
> -my $fast_str = "";
With this change, we should probably delete the `vt-auto-build` repository also since it's the one that calls this script. Now that checkpoint and detector can be put into the `vt/lib` directory, there's no reason for the builder script I think.

2021-03-01 18:40 UTC, lifflander commented on src/vt/configs/debug/debug_masterconfig.h
> -#if !vt_debug_enabled
I think we still need a mode where all prints are compile-time removed. I think it shouldn't be the default though for release.

2021-03-01 18:40 UTC, lifflander commented on src/vt/configs/error/config_assert.h
> -#if vt_check_enabled(production)
I think that assertions, if enabled, should always cause the program to fail in general. The reason that option exists is the rare occasion that you want the code to run past a bug to observe the behavior. I think we could add a runtime argument for doing just that---it doesn't really make sense at compile-time.

2021-03-01 18:40 UTC, lifflander commented on src/vt/configs/error/config_assert.h
> -#if vt_check_enabled(production)
I still think there should be a mode where assertions are disabled, but that should be a cmake configuration variable that is opt-in.

2021-03-01 18:40 UTC, lifflander commented on tests/unit/test_parallel_harness.h
> -    std::copy(
Good catch

2021-03-01 18:40 UTC, lifflander commented on cmake/define_build_types.cmake
>    # assume production mode for everything except debug or CI build
We could say that a production build disables all debug prints at compile time and disables assertions. What do you think about that idea?

2021-03-01 18:42 UTC, lifflander commented
Overall I like the direction this is headed. But, I think we should preserve the mode where debug printing is completely compiled out and assertions are disabled. Maybe we can all that `production`, with an opt-in flag at compile-time to enable it.

I would like to get others feedback on this issue: @PhilMiller @nlslatt

2021-03-01 18:51 UTC, nlslatt commented on src/vt/configs/error/config_assert.h
> -#if vt_check_enabled(production)
I agree about an opt-in disable of assertions and debug prints, so that we can optimize fully for production runs.

2021-03-01 19:37 UTC, cz4rs commented on docs/md/building.md
> -| `vt_fcontext_enabled`            | 1               | Force use of fcontext for threading |
It does both, enables fcontext and forces its use in worker.
There is only one configuration variable defined that is used both in `worker::WorkerSeq` and `seq::SeqULTContext` - should this be controlled independently?

2021-03-01 19:38 UTC, cz4rs commented on docs/md/building.md
> -| `vt_fcontext_enabled`            | 1               | Force use of fcontext for threading |
+ should the description be changed back to `Enable user-level threads through boost fcontext`?

2021-03-01 20:07 UTC, lifflander commented on docs/md/building.md
> -| `vt_fcontext_enabled`            | 1               | Force use of fcontext for threading |
I think we can leave it alone for now--enabling and forcing the use. Later on, depending on @PhilMiller work with ULTs, we might want to have seperate options available.

2021-03-01 20:16 UTC, cz4rs commented on cmake/define_build_types.cmake
>    # assume production mode for everything except debug or CI build
Sounds good to me.
- this would replace replace `vt_debug_enabled` (which was deduced from build type) with explicit, opt-in **`vt_production_build`** configuration variable (as discussed in the assertions thread)
- do you think it is worth it to have separate configuration variables for debug prints and assertions?

2021-03-01 21:20 UTC, cz4rs commented on src/vt/configs/error/config_assert.h
> -#if vt_check_enabled(production)
Introduced `vt_production_build_enabled` CMake configuration variable (default off).

2021-03-01 21:32 UTC, cz4rs commented on cmake/define_build_types.cmake
>    cmake_vt_debug_modes_all
So is this fine-grained control mechanism needed? We have the runtime flags as a basic tool to control which debug prints will be displayed. Now we will also have the possibility to disable assertions and debug prints completely with the opt-in.
We could:
- remove `CatEnum` mechanism completely and simplify debug printing logic 
- at least move this list directly into C++ code (as some `constexpr`) to avoid having it separated from actual debug code (this is definitely "advanced" control and requires rebuilding anyways)

2021-03-01 21:46 UTC, cz4rs commented
`vt_production_build_enabled=1` working as expected:

```
hello_world  --vt_debug_runtime
```
![image](https://user-images.githubusercontent.com/4639165/109563265-d385f780-7adf-11eb-900c-3ae8a6baa8de.png)

2021-03-02 22:39 UTC, cz4rs commented on src/vt/configs/error/config_assert.h
> -#if vt_check_enabled(production)
+ runtime argument `--vt_no_assert_fail`

2021-03-03 10:54 UTC, cz4rs commented on cmake/define_build_types.cmake
>    cmake_vt_debug_modes_all
`cmake_vt_debug_modes_all` was removed, compile-time policy is now based on `vt_production_build` config

2021-03-04 14:27 UTC, cz4rs commented
remaining issues:
- `macosx` build fails with following error:
```
 vt: [1] ------------------------------------------- Runtime Error: System Aborting! --------------------------------------------
 vt: [1] ------------------------------------------------ Fatal Error on Node 1 -------------------------------------------------
 vt: [1] ------------------------------------------------------------------------------------------------------------------------
 vt: [1] 
 vt: [1]              Reason: Must have valid op
 vt: [1]    Assertion failed: (op_id != no_op_id)
 vt: [1]                Node: 1
 vt: [1]           Num Nodes: 2
 vt: [1]                File: /Users/runner/work/vt/vt/src/vt/group/collective/group_info_collective.cc
 vt: [1]                Line: 587
 vt: [1]            Function: tree
(...)
vt: [1] 5   18  0x109db95a1   vt::group::InfoColl::tree(vt::group::GroupMsg<vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> >*) + 273
```
This is hard to debug because I don't have access to any mac machine, currently suspecting that for wrong ctor for `GroupMsg` is used.

- alpine build - had segmentation faults during compilation and some other errors randomly, trying to reproduce the issue consistently

2021-03-04 16:28 UTC, PhilMiller commented
For compilation segfaults try using less parallelism during the build. That's often the result of memory exhaustion.

2021-03-08 17:37 UTC, cz4rs commented
> I believe this is a known bug. Refer to #1006

That's right - a329082 works around this but a long term solution for #1006 is required.
As far as this PR goes, the only remaining issue is alpine not respecting `--vt_no_assert_fail` flag.

2021-03-09 22:00 UTC, lifflander approved these changes
Looks great to me!

2021-03-10 21:12 UTC, cz4rs commented
```
The following tests FAILED:
	  8 - vt_example:insertable_collection_2 (Failed)
```
This is a recently reported bug - #1317. I will see if there is any quick fix for the memory leak possible.

2021-03-12 17:05 UTC, merged