413 ults in scheduler
DARMA-tasking/vt pull request #1322
Opened 2021-03-12 20:49 UTC by lifflander

Fixes #413

2021-03-12 20:52 UTC, lifflander commented on examples/hello_world/hello_world.cc
> +#include <vt/scheduler/thread_action.h>
This won't be merged..just playing with this interface.

2021-03-12 20:54 UTC, lifflander commented on src/vt/scheduler/thread_action.h
> +  explicit ThreadAction(ActionType in_action)
Need to pick up epoch here to produce and consume on suspend and resume

2021-03-12 21:56 UTC, PhilMiller commented
@jstrzebonski It looks like the testing is reporting as `Testing - passed` even when the build didn't complete.

2021-03-12 22:03 UTC, PhilMiller commented on src/vt/scheduler/thread_action.cc
> +  destroy_fcontext_stack(stack);
I think these need to be in `runFnImpl` rather than here, since that accurately captures the active life of the thread.

2021-03-12 22:05 UTC, PhilMiller commented
This looks fine for what it is. The scheduler bits are where it will start to get interesting.

2021-03-12 22:07 UTC, lifflander commented
> This looks fine for what it is. The scheduler bits are where it will start to get interesting.

Cool, I'm working on the next bit. I'm thinking about tying the suspend to `AsyncOpWrapper`.

2021-03-14 15:53 UTC, PhilMiller commented
I think you're making the TD interaction too complicated, and in a way that could actually be wrong. Produce when a thread starts, consume when it's done, and don't mess around at suspend or resume.

2021-03-16 17:18 UTC, PhilMiller commented
Candidates for context classes to feed into `Runnable`:
* Trace events
* LB timing
* TD
* collection index/proxy

2021-03-19 01:19 UTC, lifflander commented on src/vt/context/runnable_context/base.h
> + * \c ctx::Base is used to create contexts that are associated with tasks
Lots of typos here...

2021-03-19 18:44 UTC, PhilMiller commented on src/vt/context/context.cc
> +#include "vt/runnable/runnable.h"
This isn't needed - the forward declaration from the context header is sufficient to take and assign a pointer

2021-03-19 18:45 UTC, PhilMiller commented on src/vt/context/runnable_context/base.h
> + * \c ctx::Base is used to create contexts that are associated with tasks
s/build/built/ in at least a few instances

2021-03-19 18:46 UTC, PhilMiller commented on src/vt/context/runnable_context/collection.h
> +  void resume() override;
It's probably worth marking all of these `final`, since the calls to them are likely to be inlined, and that would facilitate devirtualization.

2021-03-19 18:47 UTC, PhilMiller commented on src/vt/context/runnable_context/collection.impl.h
> +  vrt::collection::InsertContextHolder<IndexT>::set(&idx_, proxy_);
Is this context class only used for element insertions, or is the name of the thing it's calling a historical misnomer?

2021-03-19 18:51 UTC, PhilMiller commented on src/vt/context/runnable_context/lb_stats.impl.h
> +  theMsg()->addSendListener(std::move(listener));
This method of instrumenting sends seems rather overwrought, in that it involves allocating and inserting the listener object in a data structure.

There's an opportunity here - can we just add a `send` method to the context classes, for this use?

2021-03-19 18:55 UTC, PhilMiller commented on src/vt/context/runnable_context/td.h
> +   * suspended
Subtle note here - it will restore the stack values at and below the one in which the task is running. It's not going to touch the 'ambient' contents of the stack, which may differ between `suspend()` and `resume()` (safely, I believe)

2021-03-19 18:58 UTC, PhilMiller commented on src/vt/messaging/active.cc
> +  return theContext()->getNode();
It seems like this could be refactored to be a method of `theContext` instead

2021-03-19 18:58 UTC, PhilMiller commented on src/vt/messaging/active.cc
> +  return theContext()->getNode();
Or even a `static` member of `ctx::FromNode`, if `theContext` shouldn't have references to concrete classes it may be holding.

2021-03-19 18:59 UTC, PhilMiller commented on src/vt/messaging/active.cc
> +  return theContext()->getNode();
The same applies for `getCurrentTraceEvent` above.

2021-03-19 19:01 UTC, PhilMiller commented on src/vt/messaging/active.impl.h
> +    cur_stack_size > 0 ? epoch_stack_.top() : no_epoch
Can't we delete `epochPreludeHandler` and `epochEpilogHandler` now?

2021-03-19 19:01 UTC, PhilMiller commented on src/vt/messaging/active.h
> +
I don't see this referenced in the header or the impl.h - move down to the cc file?

2021-03-19 19:07 UTC, PhilMiller commented on src/vt/pipe/callback/handler_send/callback_send.impl.h
> +    r->run();
Not exactly entailed by the present issue, but should this be calling `run` inline, rather than `theSched()->enqueue`? There may be re-entrancy issues relative to when the caller would expect a 'sent message' to run, especially if the send ends up being an object sending a message to itself.

2021-03-19 19:08 UTC, PhilMiller commented on src/vt/pipe/callback/handler_send/callback_send.impl.h
> +    r->run();
Or, rather, shouldn't it call into whatever call path would handle a just-received message, and let that do the context setup and such?

2021-03-19 19:11 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +  if (run_type == RunnableEnum::Collection) {
Could this check and abort be a `vtAssert()` instead?

2021-03-19 19:12 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +      vtAssert(false, "Must be auto handler");
Instead of `else`, maybe `vtAssert(func != nullptr)`?

2021-03-19 19:12 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +      vtAssert(false, "Must be auto handler");
And regardless,  `vtAssert(false, ...)` should just be `vtAbort()`

2021-03-19 19:18 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +  consumeEpochMsg();
Could this call be moved to `end()` instead?

More generally, should the produce/consume pair here instead be handled by an `enqueue()` method implemented on `ctx::TD` (as a new `virtual void Base::enqueue()`), with `RunnableNew::enqueue` being called by the scheduler when asked to enqueue one of these?

I can also see potential performance analysis uses for such a method, to record a time, and then see how long the work spent in the queue.

2021-03-19 19:20 UTC, PhilMiller commented on src/vt/runnable/runnable.h
> +  void end();
I don't think `begin()` and `end()` need to be `public`, since they're being called by `run()`

2021-03-19 19:23 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +  consumeEpochMsg();
With that change, I think any concern about TD and epochs here in `RunnableNew` could just go away. The `produce` call in `TD::begin` would move to `TD::enqueue`, and then nothing would be necessary here.

2021-03-19 19:24 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +  consumeEpochMsg();
The epoch determination logic probably belongs in `ctx::TD` as well.

2021-03-19 19:32 UTC, PhilMiller commented on src/vt/scheduler/priority_queue.h
> +    T elm = std::move(const_cast<T&>(impl_.top()));
I'd had some sense that the interface defined by `std::priority_queue` was not great, but this really drives it home.

2021-03-19 19:39 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +  consumeEpochMsg();
Or, instead of an `enqueue()` method, should the `produce()` call in `ctx::TD` just be in its constructor instead of its `begin()` method?

2021-03-19 19:51 UTC, PhilMiller commented on src/vt/serialization/messaging/serialized_messenger.impl.h
> +          theSched()->enqueue(msg, std::move(r));
Similar to my thought about callbacks, could this just be a call to the method that would be called if this message were just received?

2021-03-19 19:55 UTC, PhilMiller commented on src/vt/context/runnable_context/set_context.h
> + * components or users.
I have a rough sense that this class's behavior should probably be integral to `RunnableNew` itself, or perhaps it should always add it itself, rather than callers doing so.

2021-03-19 19:59 UTC, PhilMiller commented
I really like how this is coming along. We should talk on Tuesday about some of the more involved changes this makes.

2021-03-19 22:42 UTC, lifflander commented on src/vt/context/runnable_context/collection.impl.h
> +  vrt::collection::InsertContextHolder<IndexT>::set(&idx_, proxy_);
It's a historical misnomer. Before it was just used for insertions, but then I repurposed it more generally for the request Matt made to be able to access the current index/proxy. I will rename `InsertContextHolder` appropriately.

2021-03-19 22:43 UTC, lifflander commented on src/vt/context/runnable_context/lb_stats.impl.h
> +  theMsg()->addSendListener(std::move(listener));
I really like that idea. I will rework it.

2021-03-19 22:44 UTC, lifflander commented on src/vt/messaging/active.cc
> +  return theContext()->getNode();
Agreed, will do

2021-03-20 01:02 UTC, lifflander commented on src/vt/messaging/active.h
> +
Ah, yes that's a remnant of the past

2021-03-20 01:02 UTC, lifflander commented on src/vt/messaging/active.impl.h
> +    cur_stack_size > 0 ? epoch_stack_.top() : no_epoch
Yes, good point

2021-03-20 01:03 UTC, lifflander commented on src/vt/pipe/callback/handler_send/callback_send.impl.h
> +    r->run();
Yes, I think I chose the wrong path on this one. It should enqueue itself for the callback path.

2021-03-20 01:05 UTC, lifflander commented on src/vt/runnable/runnable.cc
> +  if (run_type == RunnableEnum::Collection) {
I think I can remove the `RunnableEnum` with the refactoring I did. All collections runnable should go through this overload for `setupHandlerElement`

2021-03-20 01:07 UTC, lifflander commented on src/vt/scheduler/priority_queue.h
> +    T elm = std::move(const_cast<T&>(impl_.top()));
Unfortunately, `std::priority_queue` is very limited and does not support move-only types. This is a "safe" workaround given that I've encapsulated it here. I think C++17 or 20 fixes this.

2021-03-20 01:10 UTC, lifflander commented on src/vt/serialization/messaging/serialized_messenger.impl.h
> +          theSched()->enqueue(msg, std::move(r));
Yes, we probably could abstract that out into a callsite. It's not the quite same as an active messenger message coming in, due to how the handlers are passed

2021-03-20 01:14 UTC, lifflander commented on src/vt/scheduler/thread_action.h
> +  explicit ThreadAction(ActionType in_action)
Resolved with TD

2021-03-20 01:15 UTC, lifflander commented on src/vt/context/context.cc
> +#include "vt/runnable/runnable.h"
Removed

2021-03-20 01:19 UTC, lifflander commented on src/vt/context/runnable_context/collection.h
> +  void resume() override;
Done, marked the methods and those classes final

2021-03-20 15:17 UTC, lifflander commented on src/vt/context/runnable_context/base.h
> + * \c ctx::Base is used to create contexts that are associated with tasks
Fixed

2021-03-20 15:21 UTC, lifflander commented on src/vt/context/runnable_context/collection.impl.h
> +  vrt::collection::InsertContextHolder<IndexT>::set(&idx_, proxy_);
Renamed

2021-03-20 15:48 UTC, lifflander commented on src/vt/context/runnable_context/lb_stats.impl.h
> +  theMsg()->addSendListener(std::move(listener));
Ok, I've done this refactoring. I was actually able to completely de-template `LBStats` also with this change.

2021-03-20 15:56 UTC, lifflander commented on src/vt/messaging/active.impl.h
> +    cur_stack_size > 0 ? epoch_stack_.top() : no_epoch
Removed

2021-03-20 15:58 UTC, lifflander commented on src/vt/messaging/active.h
> +
Removed

2021-03-20 16:07 UTC, lifflander commented on src/vt/pipe/callback/handler_send/callback_send.impl.h
> +    r->run();
Fixed

2021-03-20 16:18 UTC, lifflander commented on src/vt/context/runnable_context/set_context.h
> + * components or users.
Initially, I was thinking that was the better design. However, I really like the encapsulation this provides. Otherwise, we would have to implement all this behavior in `RunnableNew`, including tracking suspensions and the previous task that was set (along with restoring it back). I think having it as part of the context and having the logic isolated here is actually more natural.

So, for now, I'm going to leave it as is and maybe we can discuss it later when we delve into the broader impacts this has on VT.

2021-03-20 16:42 UTC, lifflander commented on src/vt/runnable/runnable.h
> +  void end();
Fixed

2021-03-20 16:51 UTC, lifflander commented on src/vt/runnable/runnable.cc
> +  if (run_type == RunnableEnum::Collection) {
Completely removed RunnableEnum which cleaned up the code quite a bit!

2021-03-20 16:52 UTC, lifflander commented on src/vt/runnable/runnable.cc
> +      vtAssert(false, "Must be auto handler");
Done, make it a `vtAbort`

2021-03-20 17:07 UTC, lifflander commented on src/vt/messaging/active.cc
> +  return theContext()->getNode();
Done!

2021-03-22 17:33 UTC, lifflander commented on src/vt/runnable/runnable.cc
> +  consumeEpochMsg();
Done, cleaned this up a ton!

2021-03-22 19:22 UTC, PhilMiller commented on src/vt/context/context.cc
> +    return theContext()->getTask()->get<ctx::Trace>()->getEvent();
Are we going to uphold an invariant that every task will be traced? I could easily see wanting to exclude some unimportant things from traces entirely, to limit overhead and trace size.

I think this should be like `FromNode`, where it checks whether there's a `Trace` context or not.

2021-03-22 19:29 UTC, PhilMiller commented on src/vt/context/runnable_context/base.h
> +  virtual void send(NodeType dest, MsgSizeType size, bool bcast) { }
Rather than passing the message size, would it make sense to pass the message pointer itself, so that a more sophisticated implementation could extract any info it wants for itself?

2021-03-22 19:30 UTC, lifflander commented on src/vt/context/runnable_context/base.h
> +  virtual void send(NodeType dest, MsgSizeType size, bool bcast) { }
You can't template this if it's virtual. If it's virtual, you can only pass `MsgSharedPtr<BaseMsgType>` so you won't have the actual message type and `sizeof(MsgT)` isn't valid.

2021-03-22 19:30 UTC, lifflander commented on src/vt/context/runnable_context/base.h
> +  virtual void send(NodeType dest, MsgSizeType size, bool bcast) { }
And if the message is serializable, you can't serialize without the actual type.

2021-03-22 19:34 UTC, PhilMiller commented on src/vt/context/runnable_context/lb_stats.cc
> +  theCollection()->setCurrentContext(cur_elm_id_);
It would be additional refactoring, but can we just do away with that entirely, and ask for this?

2021-03-22 19:35 UTC, PhilMiller commented on src/vt/context/runnable_context/collection.impl.h
> +  vrt::collection::CollectionContextHolder<IndexT>::set(&idx_, proxy_);
Would it be feasible to just keep things right here, and eliminate that entirely?

2021-03-22 19:38 UTC, PhilMiller commented on src/vt/context/runnable_context/set_context.cc
> +  ContextAttorney::setTask(nonowning_cur_task_);
Could we implement and use a simple `observer_ptr` wrapper, and not stick that information in the member name? I almost got confused below by the similarity between `nonowning_cur_task_` and `nonowning_prev_task_`

2021-03-22 19:41 UTC, PhilMiller commented on src/vt/context/runnable_context/td.h
> +   * \brief During begin \c TD will produce on the epoch and push it on the
The `produce` call is happening in the constructor now, not `begin()`

2021-03-22 19:42 UTC, PhilMiller commented on src/vt/context/runnable_context/td.h
> +   * \brief During end \c TD will consume on the epoch and pop it off the stack
Similarly, `consume` is in the dtor

2021-03-22 19:48 UTC, PhilMiller commented on src/vt/context/runnable_context/trace.h
> +  Trace(Args... args) {}
Want to take these by const or universal reference, so we're not copying `MsgT`?

2021-03-22 19:51 UTC, lifflander commented on src/vt/context/context.cc
> +    return theContext()->getTask()->get<ctx::Trace>()->getEvent();
FIxed

2021-03-22 19:54 UTC, PhilMiller commented on src/vt/context/runnable_context/base.h
> +  virtual void send(NodeType dest, MsgSizeType size, bool bcast) { }
Right, I forgot about those constraints.

2021-03-22 19:56 UTC, PhilMiller commented on src/vt/context/runnable_context/base.h
> +  virtual void send(NodeType dest, MsgSizeType size, bool bcast) { }
Would it make sense to move the calls to get this info to the interface to `MsgSharedPtr`, rather than having callers pass them in here?

2021-03-22 20:00 UTC, lifflander commented on src/vt/context/runnable_context/td.h
> +   * \brief During begin \c TD will produce on the epoch and push it on the
Fixed

2021-03-22 20:00 UTC, lifflander commented on src/vt/context/runnable_context/td.h
> +   * \brief During end \c TD will consume on the epoch and pop it off the stack
Fixed

2021-03-22 20:00 UTC, lifflander commented on src/vt/context/runnable_context/trace.h
> +  Trace(Args... args) {}
Done

2021-03-22 20:07 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +  HandlerType handler, NodeType from_node, bool is_void, TagType tag
The `from_node` argument is never being used, in any of these methods. Is it meant to be?

2021-03-22 20:10 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +  begin();
My remark about `RunnableNew` handling the context pointer itself was suggesting adding a simple call here:
`addContext<SetContext>(this)`

2021-03-22 20:11 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +  begin();
Before `begin()`, obviously.

2021-03-22 20:15 UTC, PhilMiller commented on src/vt/serialization/messaging/serialized_messenger.impl.h
> +      r->template addContext<ctx::Continuation>(action);
Would it make sense to `std::move(action)` here? Just in case it's captured something heavy?

2021-03-22 20:19 UTC, PhilMiller commented on src/vt/serialization/messaging/serialized_messenger.impl.h
>        if (is_valid_epoch) {
It would be nice if we could create and capture the `ctx::TD` or the entire `RunnableNew` outside this lambda, and just do away with the `is_valid_epoch` and associated `produce/consume` calls.

2021-03-22 20:29 UTC, lifflander commented on src/vt/runnable/runnable.cc
> +  HandlerType handler, NodeType from_node, bool is_void, TagType tag
Good point, I think that's a hold over from when that method handled trace stuff. I will remove it!

2021-03-22 20:37 UTC, lifflander commented on src/vt/context/runnable_context/set_context.cc
> +  ContextAttorney::setTask(nonowning_cur_task_);
Done, check out the implementation let me know what you think: https://github.com/DARMA-tasking/vt/pull/1322/commits/356a0090fc5596a574506cdc58c9e8f9e9231468

2021-03-22 20:51 UTC, lifflander commented on src/vt/runnable/runnable.cc
> +  begin();
Good point.. done

2021-03-22 20:51 UTC, lifflander commented on src/vt/runnable/runnable.cc
> +  HandlerType handler, NodeType from_node, bool is_void, TagType tag
Removed

2021-03-22 20:55 UTC, lifflander commented on src/vt/context/runnable_context/set_context.h
> + * components or users.
Resolved per later comment

2021-03-22 20:57 UTC, PhilMiller commented on src/vt/messaging/active.cc
> +      r->template addContext<ctx::TD>(base);
Could `ctx::TD` do the `is_term` check itself? It doesn't look like there's any type dependence there.

2021-03-22 21:01 UTC, PhilMiller commented on src/vt/pipe/callback/handler_send/callback_send.impl.h
> +    theSched()->enqueue(std::move(r));
This calls to attention that a no-message handler callback won't `Trace` back to the event that triggered it. Would it make sense to add one to the current event?

2021-03-22 22:11 UTC, lifflander commented on src/vt/context/runnable_context/lb_stats.cc
> +  theCollection()->setCurrentContext(cur_elm_id_);
Yep, working on that right now.

2021-03-22 22:11 UTC, lifflander commented on src/vt/context/runnable_context/collection.impl.h
> +  vrt::collection::CollectionContextHolder<IndexT>::set(&idx_, proxy_);
Same with this.

2021-03-22 22:59 UTC, lifflander commented on src/vt/context/runnable_context/lb_stats.cc
> +  theCollection()->setCurrentContext(cur_elm_id_);
Cleaned this up a ton!

2021-03-22 23:06 UTC, lifflander commented on src/vt/context/runnable_context/collection.impl.h
> +  vrt::collection::CollectionContextHolder<IndexT>::set(&idx_, proxy_);
I was able to refactor the `getCurrentContext`/`setCurrentContext` out for `LBStats`. For this one, there are times when the context is set outside of `RunnableNew`, specifically when the collection is being set up (and a handler is not running). So I don't think I can refactor this out quite yet. We might want to switch some of that setup to happen inside a `RunnableNew`, like the collection insertion and collection constructor. I think I'm going to leave that for later so I can start focusing on more of the threaded stuff.

2021-03-22 23:19 UTC, lifflander commented on src/vt/pipe/callback/handler_send/callback_send.impl.h
> +    theSched()->enqueue(std::move(r));
That's a good point. I'm not sure if I understand your solution.

2021-03-22 23:24 UTC, lifflander commented on src/vt/messaging/active.cc
> +      r->template addContext<ctx::TD>(base);
Actually, it does this check already: https://github.com/DARMA-tasking/vt/blob/fe1b7b4bb7503b5d5611987859924f74570fcd84/src/vt/context/runnable_context/td.impl.h#L63-L83

However the way `TD::begin()` and `TD::end()` are written they would push/pop `no_epoch` on the stack, which would be very confusing. I think it's better to just avoid having anything happen with respect to `ctx::TD` when it's a termination message as it's not valid to create an epoch context when it's a termination message. In essence, a termination message has no epoch and should never change any state related to epochs.

2021-03-22 23:32 UTC, lifflander commented on src/vt/serialization/messaging/serialized_messenger.impl.h
>        if (is_valid_epoch) {
Outside of this lambda we don't have `msg` because it hasn't arrived from `theMsg()->recvDataDirect(..)` yet to then be deserialized. Thus, we can't really create the runnable outside of it. The issue is that `recvDataDirect` does not know about epochs so we have to produce/consume to make sure TD doesn't happen early. It might be a good idea to have it produce/consume when it's called based on whatever is on the top of the epoch stack when it is called? Not sure if there are edge cases there were it's called outside of a handler though (not in this case, but other use cases). I think I would prefer to leave this as is for now. Also, it's probably possible to remove `is_valid_epoch` (because it should always be valid). We should sanity check the codebase that it's impossible to send a message with `no_epoch` because at the very least messages should have `term::any_epoch_sentinel` (which we should probably get rid of eventually). Anyway, I'm going to leave these things as an exercise for the future since they are only tangentially related to the matters this PR addresses.

2021-03-22 23:33 UTC, lifflander commented on src/vt/context/runnable_context/base.h
> +  virtual void send(NodeType dest, MsgSizeType size, bool bcast) { }
Are you thinking that when `MsgSharedPtr<T>` is created (before `T` is erased) that we should capture the size for when it is possibly type-erased in the future? I like that idea. Not sure if that should go with this PR

2021-03-23 02:43 UTC, lifflander commented on src/vt/serialization/messaging/serialized_messenger.impl.h
> +          theSched()->enqueue(msg, std::move(r));
OK--I think I have a pretty nice solution with `makeRunnable`.

2021-03-23 20:11 UTC, PhilMiller commented on src/vt/runnable/make_runnable.h
> +  RunnableMaker&& withTDMsg(bool is_term = false) {
Is this really `withTDEpochFromMessage`, essentially? While I understand that some messages are or aren't `EpochMsg`, that's not really relevant to the naming of this function.

2021-03-23 20:11 UTC, lifflander commented on src/vt/runnable/make_runnable.h
> +  RunnableMaker&& withTDMsg(bool is_term = false) {
Right, yes that is a more accurate name

2021-03-23 20:16 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +  addContext<ctx::SetContext>(this);
Given the builder now in use, does it make sense to move this call there?

2021-03-23 20:17 UTC, lifflander commented on src/vt/runnable/make_runnable.h
> +  template <typename IdxT, typename ElmT>
I can actually extract the `IdxT` from `ElmT`. No reason to have that manually specified here.

2021-03-23 20:18 UTC, PhilMiller commented on src/vt/runnable/runnable.h
> +
Obvious next step here is that this needs `suspend` and `resume` methods that call the associated methods of the contexts.

2021-03-23 20:22 UTC, PhilMiller commented on src/vt/scheduler/base_unit.cc
> +      // allocation doesn't disappear under the stack
Should we just have a container (`unordered_set`, maybe?) of suspended tasks, from which it can be moved back into the queue when it's resumed?

2021-03-23 21:58 UTC, lifflander commented on src/vt/runnable/make_runnable.h
> +  template <typename IdxT, typename ElmT>
Done, fixed

2021-03-23 21:59 UTC, lifflander commented on src/vt/context/runnable_context/collection.impl.h
> +  vrt::collection::CollectionContextHolder<IndexT>::set(&idx_, proxy_);
reference issue: https://github.com/DARMA-tasking/vt/issues/1339

2021-03-23 22:00 UTC, lifflander commented on src/vt/serialization/messaging/serialized_messenger.impl.h
> +      r->template addContext<ctx::Continuation>(action);
refer to issue: https://github.com/DARMA-tasking/vt/issues/1340

2021-03-23 22:01 UTC, lifflander commented on src/vt/serialization/messaging/serialized_messenger.impl.h
>        if (is_valid_epoch) {
refer to issue: https://github.com/DARMA-tasking/vt/issues/1341

2021-03-23 22:02 UTC, lifflander commented on src/vt/messaging/active.cc
> +      r->template addContext<ctx::TD>(base);
refer to issue: https://github.com/DARMA-tasking/vt/issues/1341

2021-03-23 22:03 UTC, lifflander commented on src/vt/pipe/callback/handler_send/callback_send.impl.h
> +    theSched()->enqueue(std::move(r));
refer to issue: https://github.com/DARMA-tasking/vt/issues/1342

2021-03-23 22:03 UTC, lifflander commented on src/vt/runnable/runnable.cc
> +  addContext<ctx::SetContext>(this);
Yes, I was thinking the same. Will do

2021-03-23 23:14 UTC, lifflander commented on src/vt/runnable/runnable.cc
> +  addContext<ctx::SetContext>(this);
Done

2021-03-24 01:08 UTC, PhilMiller commented on src/vt/scheduler/suspended_units.cc
> +  vtAbortIf(iter == units_.end(), "Must have valid thread ID to suspend");
To resume, presumably

2021-03-24 01:18 UTC, PhilMiller commented on src/vt/messaging/async_op_wrapper.cc
> +    theSched()->suspended_.resumeRunnable(tid_);
Why not add a method on theSched to do this, rather than making the member accessible?

2021-03-24 14:11 UTC, PhilMiller commented on src/vt/messaging/active.cc
> +    auto lb = theContext()->getTask()->get<ctx::LBStats>();
This should probably be a `send` method of context itself, with the loop over context instances, like `begin`, `end`, etc. Otherwise, why is there a `virtual Base::send`?

I could potentially see `Trace` and `TD` wanting to implement the method as well, for instance. `TD` could perhaps automatically call `produce` there, and maybe the `hangDetectSend` call seen above as well..

2021-03-24 14:32 UTC, PhilMiller commented on src/vt/vrt/collection/manager.impl.h
> +#endif
Can this `#if` be inside `withLBStats`, so it doesn't need to be repeated at call sites?

2021-03-24 14:35 UTC, PhilMiller commented on src/vt/context/runnable_context/continuation.h
> +      cont_();
This may need to be `theSched()->enquqeue(cont_)`, so that it doesn't execute in some inconsistent environment created by the other context `end()` methods being called in an unknown order.

2021-03-24 14:44 UTC, PhilMiller commented
OK, I think that's pretty much all I'm going to have to say about this set of changes. It would be nice to get the move of `AsyncOpMPI` from the tests to the source in, too.

2021-03-24 16:53 UTC, lifflander commented on src/vt/vrt/collection/manager.impl.h
> +#endif
Done

2021-03-24 16:57 UTC, lifflander commented on src/vt/scheduler/scheduler.h
> +
Done

2021-03-24 16:58 UTC, lifflander commented on src/vt/messaging/async_op_wrapper.cc
> +    theSched()->suspended_.resumeRunnable(tid_);
Done

2021-03-24 16:59 UTC, lifflander commented on src/vt/scheduler/suspended_units.cc
> +  vtAbortIf(iter == units_.end(), "Must have valid thread ID to suspend");
Fixed

2021-03-24 16:59 UTC, lifflander commented on src/vt/messaging/active.cc
> +    auto lb = theContext()->getTask()->get<ctx::LBStats>();
Good point

2021-03-24 18:04 UTC, lifflander commented on src/vt/messaging/active.cc
> +    auto lb = theContext()->getTask()->get<ctx::LBStats>();
Done

2021-03-24 18:05 UTC, lifflander commented on src/vt/context/runnable_context/continuation.h
> +      cont_();
For now I'm going to leave this as is, because the continuation is typically some cleanup action like a deleter.

2021-03-24 18:05 UTC, lifflander commented on src/vt/scheduler/base_unit.cc
> +      // allocation doesn't disappear under the stack
Done

2021-03-24 18:12 UTC, lifflander commented on src/vt/runnable/make_runnable.h
> +  RunnableMaker&& withTDMsg(bool is_term = false) {
Renamed

2021-03-24 18:13 UTC, lifflander commented on src/vt/scheduler/thread_action.cc
> +  destroy_fcontext_stack(stack);
I can't move that there because it has a jump at the end and we must deallocate the stack *afrer* that jump.

2021-03-24 18:15 UTC, lifflander commented on src/vt/context/runnable_context/base.h
> +  virtual void send(NodeType dest, MsgSizeType size, bool bcast) { }
refer to: https://github.com/DARMA-tasking/vt/issues/1344

2021-03-24 18:23 UTC, lifflander commented
> OK, I think that's pretty much all I'm going to have to say about this set of changes. It would be nice to get the move of `AsyncOpMPI` from the tests to the source in, too.

Done, added to the main code base.

2021-03-24 18:30 UTC, PhilMiller commented on src/vt/context/runnable_context/continuation.h
> +      cont_();
In that case, want to mention in the class comments that any continuation should not depend on other context?

2021-03-24 18:37 UTC, PhilMiller commented on src/vt/scheduler/thread_action.h
> +   * \brief Resume the thread were left offn
Typos
- where
- off

2021-03-24 18:38 UTC, PhilMiller commented on src/vt/scheduler/thread_action.h
> +   * \brief Keep yielding back to thread (resuming after suspension) unit the
Typo unit -> until

Also,  I think this is only suitable to call for testing purposes? When else would a just-suspended thread want to be resumed immediately?

2021-03-24 18:39 UTC, PhilMiller commented on src/vt/scheduler/thread_action.h
> +private:
Any reason for the mixed comment styles and multiple `private:` blocks here?

2021-03-24 18:55 UTC, PhilMiller commented on src/vt/runnable/make_runnable.h
> +struct RunnableMaker {
As written, this is going to pull in a ton of headers all over the place. Would it make sense to have a `RunnableMakerBase` that's not templated, containing the implementation of most of these?

Alternately, does the whole class actually need to be templated over MsgT, or can that safely be type erased at construction?

2021-03-24 19:08 UTC, lifflander commented on src/vt/scheduler/thread_action.h
> +   * \brief Keep yielding back to thread (resuming after suspension) unit the
Yes, just for testing.

2021-03-24 19:09 UTC, lifflander commented on src/vt/scheduler/thread_action.h
> +private:
Fixed

2021-03-24 19:10 UTC, lifflander commented on src/vt/scheduler/thread_action.h
> +   * \brief Resume the thread were left offn
Fixed

2021-03-24 19:11 UTC, PhilMiller approved these changes

2021-03-24 19:15 UTC, lifflander commented on src/vt/runnable/make_runnable.h
> +struct RunnableMaker {
This looks like a lot of inclusions, but most of the runnable context headers have fairly minimal includes (which I spent time minimizing). `lb_stats.impl.h` is probably the heaviest one because it has to include `elm_stats.h`. To remediate this dependency problem I don't include the `lb_stats.impl.h` in `lb_stats.h`, instead including it in `vrt/collection/manager.h` at the very end. Same with `collection.impl.h`, which has the heaver inclusions.

2021-03-24 19:17 UTC, lifflander commented on src/vt/runnable/make_runnable.h
> +struct RunnableMaker {
The one reason I can't type-erase `MsgT` is due to `withTraceIndex` which requires the non-type-erased message type to properly trace collection messages. I could have that pass in the message again, instead of holding on to it, but that would require some parameter duplication at those callsites. Do you think it's work it?

@PhilMiller

2021-03-24 19:19 UTC, PhilMiller commented on src/vt/runnable/make_runnable.h
> +struct RunnableMaker {
If that's the only reason we can't type-erase this, I think the parameter duplication is worthwhile.

2021-03-24 22:56 UTC, PhilMiller commented on src/vt/runtime/runtime_banner.cc
> +    auto f12 = opt_remove("--vt_diag_disable", f11);
Shouldn't this be `--vt_ult_disable_`?

2021-03-24 22:57 UTC, PhilMiller requested changes
See the option message comment

2021-03-24 22:58 UTC, lifflander commented on src/vt/runtime/runtime_banner.cc
> +    auto f12 = opt_remove("--vt_diag_disable", f11);
Oops, good catch

2021-03-24 22:58 UTC, lifflander commented on src/vt/runtime/runtime_banner.cc
> +    auto f12 = opt_remove("--vt_diag_disable", f11);
Fixed

2021-03-24 23:00 UTC, lifflander commented
Note that two of the CI targets have `fcontext` enabled so CI will be testing all the threading across one clang build and one GNU build.

2021-03-24 23:09 UTC, PhilMiller approved these changes
I'm happy with this. Your call whether you want to do the type erasure on `RunnableMaker` or not.

2021-03-25 02:07 UTC, merged