1317:  Memory leak exposed by address sanitizer in insertable_collection example
DARMA-tasking/vt pull request #1332
Opened 2021-03-18 12:46 UTC by cz4rs

fixes #1317

2021-03-18 14:36 UTC, cz4rs commented on ci/docker/ubuntu-18.04-gnu-cpp.dockerfile
> +ENV LSAN_OPTIONS=suppressions=/vt/tests/knowns_leaks.supp
FIXME: after verifying that CI works, this should be added to all dockerfiles

2021-03-18 20:04 UTC, cz4rs commented
In the end it's [`LSAN_OPTIONS`](https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer#flags) - there's a separate variable and slightly different file format for LeakSanitizer.

I have verified that this is enough to silence the error.
Note: if a suppression occurs, it will show up in `stdout` without failing the build:
```
-----------------------------------------------------
Suppressions used:
  count      bytes template
      1         64 MPIDI_CH3U_Receive_data_unexpected
-----------------------------------------------------
```

2021-03-19 16:23 UTC, lifflander requested changes
Instead of baking this into the dockerfiles (and thus the container images) I think it would be better to make it a variable that can be passed through from docker-compose. What do you think?

2021-03-19 16:45 UTC, cz4rs commented
> Instead of baking this into the dockerfiles (and thus the container images) I think it would be better to make it a variable that can be passed through from docker-compose. What do you think?

Sounds reasonable, it will allow to keep non-asan builds cleaner :+1:

2021-03-19 22:29 UTC, cz4rs commented on scripts/azure-workflow-template.yml
> +[% IF lsan_options %]  LSAN_OPTIONS: [% lsan_options %][% END %]
make sure that there is no trailing whitespace (`IF` works better here than enabling `TRIM` option or using `[% -%]`)

2021-03-19 23:54 UTC, cz4rs commented
@lifflander 
It should be good now, except for `gcc-7` build reaching it's limits again:
![image](https://user-images.githubusercontent.com/4639165/111852320-c6a63800-8916-11eb-9ad4-f1f8d5b1ff32.png)

2021-03-22 23:43 UTC, lifflander commented
> @lifflander
> It should be good now, except for `gcc-7` build reaching it's limits again:
> 
> _edit: the build has passed after a couple of re-runs_

When limitation was it hitting? Time limit or memory?

2021-03-22 23:43 UTC, lifflander approved these changes
Looks good!

2021-03-23 10:47 UTC, cz4rs commented
> > @lifflander
> > It should be good now, except for `gcc-7` build reaching it's limits again:
> > _edit: the build has passed after a couple of re-runs_
> 
> When limitation was it hitting? Time limit or memory?

It was disk space.

2021-03-23 11:33 UTC, merged