1376 improve lbargs for gossiplb
DARMA-tasking/vt pull request #1422
Opened 2021-05-03 19:34 UTC by nlslatt

Makes LB args for GossipLB more human readable, improves error handling, adds the (default) ability to have vt choose an appropriate fanout and number of gossiping rounds, makes asynchronous informs the default, and sets the number of trials to 1 (more lightweight) by default.

Closes #1376.

2021-05-03 20:05 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
> +    }
@lifflander @PhilMiller Please let me know your thoughts on this in particular.

2021-05-24 19:25 UTC, nlslatt commented
@lifflander @PhilMiller This still needs to be reviewed.

2021-05-25 16:42 UTC, PhilMiller commented on tests/unit/collection/test_lb.extended.cc
> +    auto lb_args = fmt::format("ordering=Arbitrary rollback=false");
Nitpick, this could just be the string literal now.

2021-05-25 16:44 UTC, PhilMiller commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +struct EnumConverter {
Other than the error messages, could this be a stand-alone utility class, separate from GossipLB?

2021-05-25 16:51 UTC, PhilMiller commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +using CriterionEnum = ::vt::vrt::collection::lb::CriterionEnum;
I think it may not be technically allowed to define these names in `namespace std`, as opposed to fully qualifying them in the specializations of `std::hash`

2021-05-25 20:32 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +struct EnumConverter {
Is there a particular place namespace where it makes sense to put it?  I'm poking around now.

2021-05-25 23:04 UTC, PhilMiller commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +struct EnumConverter {
If there isn't a `vt::utility` namespace somewhere, there probably ought to be.

2021-05-26 17:46 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +struct EnumConverter {
Making this stand-alone will be #1451.

2021-05-26 17:47 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +using CriterionEnum = ::vt::vrt::collection::lb::CriterionEnum;
Fixed for GossipLB, but not for other cases outside the scope of this PR.

2021-05-26 17:51 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +using CriterionEnum = ::vt::vrt::collection::lb::CriterionEnum;
Added #1452 to address other cases.

2021-05-26 17:53 UTC, nlslatt commented on tests/unit/collection/test_lb.extended.cc
> +    auto lb_args = fmt::format("ordering=Arbitrary rollback=false");
Addressed.

2021-05-26 23:50 UTC, lifflander requested changes

2021-05-26 23:50 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
If we feel like being extra careful, we could write tests now for this abort since it maps to a exception now when running tests. I'm personally not super concerned because this logic looks straight forward to me, but code coverage is complaining...

2021-05-26 23:50 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +  T getEnum(std::string s) const {
We should pass `std::string` by `const &` here.

2021-05-26 23:50 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +template <typename T>
I would like some very basic doxygen of what this class does. Especially if we move it to `vt/utils/*` as a general class that's usable.

2021-05-26 23:50 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +  T getFromSpec(balance::SpecEntry* spec, T def_value) const {
I understand why this method is here, but I feel like it makes it quite a bit less general. If we are moving it to utils, we should probably provide this thin helper function elsewhere.

2021-05-26 23:50 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +    return std::hash<uint8_t>()(static_cast<uint8_t>(in));
I would prefer using `std::underlying_type<T>` here instead of `uint8_t`. Basically, if we change the type that holds the enum this code must be modified also.

2021-05-27 16:15 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
It looks to me like throwing on abort is not enabled by default.  Does this mean that the test suite will fail by default on a non-CI build?

2021-05-27 16:17 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +template <typename T>
Addressed.

2021-05-27 16:17 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +  T getEnum(std::string s) const {
Fixed.

2021-05-27 16:29 UTC, JacobDomagala commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
We could add test, that runs only when 'throw_on_abort' is enabled:
```c++
#if vt_check_enabled(throw_on_abort)
  TEST_F(TestName, test_fail) {
    ASSERT_THROW(
      function_call(),
      std::runtime_error
    );
   }
#endif
```

2021-05-27 16:30 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +  T getFromSpec(balance::SpecEntry* spec, T def_value) const {
This class was really meant specifically for handling LB args.  I should have named it differently.  It easily generalizes to use with other LBs, but not trivially to more general purposes.

I could split it into a general enum conversion class and one that extends it with LB-specific functionality, but the error handling will need to be a lot more complicated in order to retain the most meaningful error messages.  It might be better to:

- rename EnumConverter to something that indicates that it's customized for handling enum conversions for LB args
- move that code out of the GossipLB subdirectory to make it available to all LBs, updating the error messages to not refer specifically to GossipLB
- create a new utility by the original name that only includes the generic enum conversion functions

What do you think?

2021-05-27 16:35 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
Thanks, @JacobDomagala!

2021-05-27 16:46 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
Unfortunately, using this approach kills gtest on my Mac.  It's probably the same issue that makes death tests not work.

2021-05-27 16:52 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
Either that or enabling throw_on_abort did not actually result in a thrown exception.  The code in the `#if` wasn't compiling it until I enabled it in cmake, so the feature should be correctly enabled.  Here's the output I'm getting:
```
[ RUN      ] TestGossipLB.test_enum_converter_fail
vt: [-1] 
vt: [-1]              Reason: GossipLB EnumConverter: enum 'DummyEnum' value '0' was not found in the map
vt: [-1]                Type: vtAbort() Invoked
vt: [-1]                Node: -1
vt: [-1]           Num Nodes: -1
vt: [-1]                File: src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
vt: [-1]                Line: 90
vt: [-1]            Function: getString
vt: [-1]                Code: 1
vt: [-1]           Build SHA: 9764b403f30509d11769b4d00ecbae679a431775
vt: [-1]           Build Ref: refs/heads/1376-improve-lbargs-for-gossiplb
vt: [-1]         Description: heads/1376-improve-lbargs-for-gossiplb-0-g9764b403f3
vt: [-1]            GIT Repo: *dirty*
```

2021-05-27 17:04 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
Actually, maybe we should enable throw_on_abort for all tests regardless of whether we are using CI or not.

2021-05-27 17:05 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +  T getFromSpec(balance::SpecEntry* spec, T def_value) const {
I think it makes sense to make it a utility class for just LBs, including renaming and moving it to indicate that.

2021-05-27 17:10 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
@JacobDomagala Would this be easy to do, just add that define for test compilation?

2021-05-27 17:23 UTC, JacobDomagala commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
@nlslatt  Make sure that this test is not a part of **nompi** test suite, as we need vt::runtime for proper handling of `vtAbort`. I've added the following test:

```c++
#if vt_check_enabled(throw_on_abort)
  TEST_F(TestLBStatsReader, test_fail) {
    using namespace vt::vrt::collection::lb;

    EnumConverter<InformTypeEnum> e("","", {});

    ASSERT_NO_THROW(
      e.getString(InformTypeEnum::AsyncInform)
    );
   }
#endif
```

and the output is:
![image](https://user-images.githubusercontent.com/9077677/119869577-af8c5380-bf20-11eb-9da4-bff20634be43.png)

2021-05-27 17:25 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
This is a nompi test.  @lifflander and I are discussing how we need to handle this use case (`CollectiveAnyOps::abort`) the same as the runtime does.

2021-05-27 18:40 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
Refer to the issue I created for addressing this problem: https://github.com/DARMA-tasking/vt/issues/1456

2021-05-27 19:15 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +  T getFromSpec(balance::SpecEntry* spec, T def_value) const {
I moved it and added tests of the spec-related functionality.

2021-05-27 20:39 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
Code coverage is no longer complaining due to the addition of another test, but I can still add throw tests when #1456 is resolved.

2021-05-27 20:42 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
> +    }
@lifflander @PhilMiller I'm still not sure if either of you looked over this chunk of code.  Do you think this is reasonable behavior?

2021-05-28 13:21 UTC, JacobDomagala commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
#1456 is now merged

2021-05-28 17:49 UTC, lifflander commented on src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
> +    }
This looks reasonable to me, based on what we discussed.

2021-05-28 17:53 UTC, lifflander approved these changes

2021-05-28 17:53 UTC, lifflander commented on src/vt/vrt/collection/balance/lb_args_enum_converter.h
> +  EnumToStrMap enum_to_str_;  //< 1 to 1 mapping of enumerated values to strings
Should these be private?

2021-05-28 17:56 UTC, nlslatt commented on src/vt/vrt/collection/balance/lb_args_enum_converter.h
> +  EnumToStrMap enum_to_str_;  //< 1 to 1 mapping of enumerated values to strings
Yes.  Fixed.

2021-05-28 17:57 UTC, nlslatt commented on src/vt/vrt/collection/balance/lb_args_enum_converter.h
> +  EnumToStrMap enum_to_str_;  //< 1 to 1 mapping of enumerated values to strings
Yes. Fixed.

2021-05-28 17:58 UTC, nlslatt commented on src/vt/vrt/collection/balance/gossiplb/gossip_enums.h
> +      auto err = fmt::format(
Thanks! I added throw tests.

2021-05-28 18:02 UTC, JacobDomagala approved these changes

2021-05-28 19:13 UTC, merged