1344 Avoid explicit message size in send() parameters
DARMA-tasking/vt pull request #1426
Opened 2021-05-04 14:56 UTC by MikolajZuzek

Fixes #1344

TODO:
- [ ] Create relevant tests or update existing ones;
- [ ] Analyze implications and potential issues, compare with applied solutions;
- [ ] Suggest solution;

2021-05-18 19:05 UTC, PhilMiller commented
Could we get a bit more description/comment on the `forceSize` uses? Everything else besides that looks great.

2021-05-25 00:32 UTC, MikolajZuzek commented
Thanks @PhilMiller, I've supplied comments at key change points - where we override default message size (also reduced `forceSize(newSize)` to constructor calls):
* [_vt/messaging/active.impl.h_](https://github.com/DARMA-tasking/vt/blob/1344-avoid-explicit-msg-size-in-send/src/vt/messaging/active.impl.h): we set the size explicitly provided in `ActiveMessenger::sendMsgSz()` and `ActiveMessenger::broadcastMsgSz()`;
* [_vt/messaging/active.cc_](https://github.com/DARMA-tasking/vt/blob/1344-avoid-explicit-msg-size-in-send/src/vt/messaging/active.cc): in `ActiveMessenger::finishPendingDataMsgAsyncRecv()`:
  * at start, we initialize message size with number of bytes detected by `MPI_Irecv()`,
  * at finish, we update the size - reducing it by the put size in case when `put_tag == PutPackedTag`.

There were other size updates in [_vt/messaging/active.cc_](https://github.com/DARMA-tasking/vt/blob/1344-avoid-explicit-msg-size-in-send/src/vt/messaging/active.cc) before `makeTraceCreationSend()` calls (compiled only with `vt_check_enabled(trace_enabled)`) that measured the message with `vt::serialization::MsgSizer<MsgT>::get()`. I don't quite follow why that was done: the new size obtained this way was only sent to `makeTraceCreationSend()` but not used in the followup calls (they operated on the original size). It seemed only like misleading the trace, so I removed those size updates - please let me know if I'm missing out something here.

2021-05-25 15:43 UTC, PhilMiller commented on src/vt/messaging/active.impl.h
> +  MsgSharedPtr<MsgT> msgptr(msg.msg_, msg_size); // Note: use explicitly proveded message size
Typo 'provided'

2021-05-25 15:44 UTC, PhilMiller commented on src/vt/messaging/active.impl.h
> +  MsgSharedPtr<MsgT> msgptr(msg.msg_, msg_size); // Note: use explicitly proveded message size
This is repeated in a few spots (probably copy/paste). Please grep and correct all of them.

2021-05-25 23:07 UTC, PhilMiller commented on src/vt/messaging/active.impl.h
>      if (not is_bcast) {
As discussed in today's call, the serialization sizing call will be moved here, and the result used in place of `msg.size()`, since we want to record the amount of data associated with the message to be sent over the network (i.e. with all arrays or other data structures it may point to), not just the size of the message structure itself.

2021-05-25 23:08 UTC, PhilMiller commented on src/vt/messaging/active.impl.h
>      if (not is_bcast) {
`auto msg_size = vt::serialization::MsgSizer<MsgT>::get(msgPtr.get());`

2021-05-25 23:11 UTC, PhilMiller commented on src/vt/messaging/active.impl.h
>      if (not is_bcast) {
Actually, I want to backtrack on this. Note that the argument `msg` is never used in this function. Thus, we should preferentially remove that `msg` argument rather than `msg_size`, de-template this function, and let the caller pass in the size based on that expression.

2021-05-26 21:18 UTC, MikolajZuzek commented on src/vt/messaging/active.impl.h
>      if (not is_bcast) {
On b00e3bc87a8c1a4648d4cf648793bcc3ef22df99 I removed `msg` argument from `ActiveMessenger::makeTraceCreationSend()`, reverted `msg_size` renaming it to `serialized_msg_size` to clarify the semantics and de-templated the method (moving the implementation to _active.cc_).

2021-05-26 21:43 UTC, MikolajZuzek commented on src/vt/messaging/active.cc
>        );
**Note:** We were sending `msg_size` with `sizeof<MsgT>` (passed here to `doMessageSend()` by `PendingSend`) to `makeTraceCreationSend()`, now we send serialized size obtained with `MsgSizer` (see the original [_vt/messaging/active.cc_](https://github.com/DARMA-tasking/vt/blob/4d5eac4e8b714e0239310ac508ca1351d0668a7c/src/vt/messaging/active.cc#L458-L461)).

2021-05-26 23:37 UTC, lifflander commented on src/vt/vrt/collection/manager.impl.h
> +    msgPtr, han, reg_type, false
This is where things get tricky. There needs to be a SFINAE overload (which I believe exists, but needs to be modified) that checks for a `serialize` method. If that exists, it should call the checkpoint sizer to get the size (which it does already). However, **if the serializer is not available**, it should just get the size from the `MsgSharedPtr`, like is done here.

2021-06-01 16:19 UTC, MikolajZuzek commented on src/vt/messaging/active.cc
>        );
I'm rolling this one back: calling `MsgSizer<BaseMsgType>` here on erased type would use `serialize()` from `BaseMsgType` instead of actual message type (since it's not virtual) and calculate incorrect size.  
If `makeTraceCreationSend()` is supposed to get correct serialized size for serializable messages here in `ActiveMessenger::doMessageSend()`, I suggest we create separate issue for that.

2021-06-01 16:44 UTC, MikolajZuzek commented on src/vt/vrt/collection/manager.impl.h
> +    msgPtr, han, reg_type, false
It seems like for `vt::serialization::MsgSizer` that is called here in [vt/vrt/collection/manager.impl.h](https://github.com/DARMA-tasking/vt/blob/develop/src/vt/vrt/collection/manager.impl.h), we have specializations for serializable and non-serializable messages that get serialized size and `sizeof(MsgT)` respectively (see in [_vt/serialization/sizer.h_](https://github.com/DARMA-tasking/vt/blob/9cd17e9700a2155fb3f4371f8df56e7f7e71ea0b/src/vt/serialization/sizer.h)).

We could change `MsgSizer::get(MsgT* msg)` to take `MsgSharedPtr` instead of the raw pointer and return the actual size carried by it for non-serializable messages - instead of `sizeof(MsgT)`.

2021-06-04 16:14 UTC, MikolajZuzek commented on src/vt/messaging/active.cc
>        );
There is no need to call `MsgSizer` here, as any serializable message would have been already handled and replaced with `SerialPayloadMsg` or `SerialEagerPayloadMsg`. Seems like no changes needed and no bug to be reported.
![always-serializable](https://user-images.githubusercontent.com/29018159/120832146-9dce3000-c560-11eb-975c-67d1b417abad.png)

2021-06-04 16:15 UTC, MikolajZuzek commented on src/vt/messaging/active.impl.h
> +  MsgSharedPtr<MsgT> msgptr(msg.msg_, msg_size); // Note: use explicitly proveded message size
Fixed

2021-06-08 15:49 UTC, PhilMiller commented on src/vt/vrt/collection/manager.impl.h
> +    msgPtr, han, reg_type, false
I think that's a good catch, and probably actually independent of this PR. There's no real connection to `makeTraceCreationSend()`, except for the discussion of it leading you to discover this.

If you build and run your proposed test case on the code in `develop`, does it fail as expected? If so, please open an issue and start a PR with that test case added, and we'll address it separately.

2021-06-11 17:26 UTC, MikolajZuzek commented on src/vt/vrt/collection/manager.impl.h
> +    msgPtr, han, reg_type, false
Created #1466 to address custom-sized message handling and #1471 to address message size logged with `makeTraceCreationSend()`. Let me know if you can think of any other issues.

2021-06-15 17:36 UTC, PhilMiller approved these changes

2021-06-15 17:44 UTC, PhilMiller requested changes
the boolean flags noted at https://github.com/DARMA-tasking/vt/pull/1473#pullrequestreview-684259541

2021-06-15 18:54 UTC, MikolajZuzek commented on src/vt/vrt/collection/manager.impl.h
> +    msgPtr, han, reg_type, false
Fixed accidentally changed `is_bcast` flags in `makeTraceCreationSend()` calls, see https://github.com/DARMA-tasking/vt/pull/1473#discussion_r652007079

2021-06-15 18:57 UTC, MikolajZuzek commented
> 
> 
> the boolean flags noted at [#1473 (review)](https://github.com/DARMA-tasking/vt/pull/1473#pullrequestreview-684259541)

Fixed!

2021-06-15 20:56 UTC, PhilMiller approved these changes

2021-06-15 20:58 UTC, PhilMiller commented
> **PR tests (clang-9, ubuntu, mpich)**
> 
> Build for [6e7944c](https://github.com/DARMA-tasking/vt/commit/6e7944cb78f2c8985ae16b2d663b7b0263f670c3)
> 
> ```
> 
> 
> The following tests FAILED:
>   155 - vt:*/TestNodeStatsDumper.test_node_stats_dumping_with_interval/*_proc_2 (Timeout)
> ```
> 
> [Build log](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=18322&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=28db5144-7e5d-5c90-2820-8676d630d9d2)

This is a sporadic failure, unrelated to this PR. Thus, I'm going ahead with merging.

2021-06-15 20:59 UTC, merged