1435: Print time units and adjust accordingly for LB times
DARMA-tasking/vt pull request #1436
Opened 2021-05-12 18:34 UTC by cz4rs

fixes #1435

2021-05-12 19:07 UTC, cz4rs commented
converting to a draft as there is more work in `BaseLB` to be done:

https://github.com/DARMA-tasking/vt/blob/f7cbf2beb07ed64de2692525ae9721e6e4cfcb3e/src/vt/vrt/collection/balance/baselb/baselb.cc#L169-L178

2021-05-13 13:32 UTC, cz4rs commented
Before:
```
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=0.00, min=0.00, sum=0.00, avg=0.00, var=0.00, stdev=0.00, nproc=64, cardinality=64 skewness=0.00, kurtosis=-1.25, npr=64, imb=0.88, num_stats=2
```
After:
```
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=103.5 ns, min=12.9 ns, sum=3.3 μs, avg=50.9 ns, var=0.0 ns, stdev=22.6 ns, nproc=64, cardinality=64 skewness=77.3 μs, kurtosis=-1060434.6 ns, npr=64, imb=1.0 ms, num_stats=2
```

FIXME: negative numbers are not handled correctly
```
kurtosis=-1060434.6 ns
```

2021-05-13 17:10 UTC, lifflander commented
@cz4rs @nlslatt I'm wondering if we should have a print out of how long each phase takes by default. If we are printing `finishedLB` anyway, we could also print a timer that could be very convenient for some apps.

2021-05-13 19:50 UTC, PhilMiller commented
I believe kurtosis and probably some of the other statistics are not in dimensions of time, and so shouldn't be printed that way. Imbalance is dimensionless

2021-05-13 20:34 UTC, cz4rs commented
> I believe kurtosis and probably some of the other statistics are not in dimensions of time, and so shouldn't be printed that way. Imbalance is dimensionless

Good catch, I've just followed the `TimeType` return type in `stats_msg.h` blindly.
Updated sample:
```
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=104.2 ns, min=12.6 ns, sum=3.3 μs, avg=51.4 ns, var=0.0 ns, stdev=22.9 ns, nproc=64, cardinality=64 skewness=0.10, kurtosis=-1.08, npr=64, imb=1.03, num_stats=2
```

2021-05-17 15:21 UTC, cz4rs commented
Duration of the phase:
```
vt: [0] (t) phase: PhaseManager::printSummary, phase=6, time=13.5 ms
```

Sample output from **TestLoadBalancer.test_load_balancer_1** test:
```
(...)
vt: Pass-through Arguments:
vt:     None. All arguments handled.
Testing lb GossipLB
Using lb_args f=1 k=2 trials=1 inform=1 ordering=0 rollback=0 targetpole=0
vt: [0] (t) lb: BaseLB: Statistic=P_l:  max=3.9 ms, min=3.9 ms, sum=3.9 ms, avg=3.9 ms, var=0.0 ns, stdev=0.0 ns, nproc=1, cardinality=1 skewness=0.00, kurtosis=0.00, npr=1, imb=0.00, num_stats=1
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=115.2 ns, min=22.2 ns, sum=3.9 μs, avg=61.5 ns, var=0.0 ns, stdev=22.8 ns, nproc=64, cardinality=64 skewness=0.05, kurtosis=-1.04, npr=64, imb=0.87, num_stats=2
vt: [0] (t) GossipLB: GossipLB::doLBStages: trial=0 final imb=0.0000
vt: [0] (t) GossipLB: GossipLB::doLBStages: chose trial=0 with imb=0.0000
vt: [0] (t) lb: BaseLB: Statistic=P_l:  max=3.9 ms, min=3.9 ms, sum=3.9 ms, avg=3.9 ms, var=0.0 ns, stdev=0.0 ns, nproc=1, cardinality=1 skewness=0.00, kurtosis=0.00, npr=1, imb=0.00, num_stats=2
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=115.2 ns, min=22.2 ns, sum=3.9 μs, avg=61.5 ns, var=0.0 ns, stdev=22.8 ns, nproc=64, cardinality=64 skewness=0.05, kurtosis=-1.04, npr=64, imb=0.87, num_stats=2
vt: [0] (t) lb: BaseLB::finalize: LB total time=3.0 ms, total migration count=0
vt: [0] (t) phase: PhaseManager::printSummary, phase=1, time=13.5 ms
vt: [0] (t) lb: BaseLB: Statistic=P_l:  max=4.0 ms, min=4.0 ms, sum=4.0 ms, avg=4.0 ms, var=0.0 ns, stdev=0.0 ns, nproc=1, cardinality=1 skewness=0.00, kurtosis=0.00, npr=1, imb=0.00, num_stats=1
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=115.2 ns, min=23.1 ns, sum=4.0 μs, avg=61.8 ns, var=0.0 ns, stdev=22.9 ns, nproc=64, cardinality=64 skewness=0.10, kurtosis=-1.05, npr=64, imb=0.86, num_stats=2
vt: [0] (t) GossipLB: GossipLB::doLBStages: trial=0 final imb=0.0000
vt: [0] (t) GossipLB: GossipLB::doLBStages: chose trial=0 with imb=0.0000
vt: [0] (t) lb: BaseLB: Statistic=P_l:  max=4.0 ms, min=4.0 ms, sum=4.0 ms, avg=4.0 ms, var=0.0 ns, stdev=0.0 ns, nproc=1, cardinality=1 skewness=0.00, kurtosis=0.00, npr=1, imb=0.00, num_stats=2
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=115.2 ns, min=23.1 ns, sum=4.0 μs, avg=61.8 ns, var=0.0 ns, stdev=22.9 ns, nproc=64, cardinality=64 skewness=0.10, kurtosis=-1.05, npr=64, imb=0.86, num_stats=2
vt: [0] (t) lb: BaseLB::finalize: LB total time=2.9 ms, total migration count=0
vt: [0] (t) phase: PhaseManager::printSummary, phase=2, time=13.3 ms
(...)
vt: [0] (t) lb: BaseLB: Statistic=P_l:  max=4.0 ms, min=4.0 ms, sum=4.0 ms, avg=4.0 ms, var=0.0 ns, stdev=0.0 ns, nproc=1, cardinality=1 skewness=0.00, kurtosis=0.00, npr=1, imb=0.00, num_stats=1
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=116.8 ns, min=22.6 ns, sum=4.0 μs, avg=62.9 ns, var=0.0 ns, stdev=23.4 ns, nproc=64, cardinality=64 skewness=0.02, kurtosis=-1.12, npr=64, imb=0.86, num_stats=2
vt: [0] (t) GossipLB: GossipLB::doLBStages: trial=0 final imb=0.0000
vt: [0] (t) GossipLB: GossipLB::doLBStages: chose trial=0 with imb=0.0000
vt: [0] (t) lb: BaseLB: Statistic=P_l:  max=4.0 ms, min=4.0 ms, sum=4.0 ms, avg=4.0 ms, var=0.0 ns, stdev=0.0 ns, nproc=1, cardinality=1 skewness=0.00, kurtosis=0.00, npr=1, imb=0.00, num_stats=2
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=116.8 ns, min=22.6 ns, sum=4.0 μs, avg=62.9 ns, var=0.0 ns, stdev=23.4 ns, nproc=64, cardinality=64 skewness=0.02, kurtosis=-1.12, npr=64, imb=0.86, num_stats=2
vt: [0] (t) lb: BaseLB::finalize: LB total time=3.0 ms, total migration count=0
vt: [0] (t) phase: PhaseManager::printSummary, phase=9, time=13.5 ms
vt: [-1] (t) trace: writeTracesFile: to_write=13997, already_written=0
vt: Total collective epochs processed: 177
vt: Total work units processed: 2339
vt: Runtime Finalizing
```

2021-05-17 16:37 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      Timing::getTimeWithUnits(total_time), global_count
This will be good for human readability, and bad for script consumption. We're extracting this from output files for plots in our current paper, indicating that it's something we at least potentially care about.

@nlslatt @lifflander thoughts on how to handle this? Perhaps we should have a command-line flag to tell `getTimeWithUnits` to always just print in seconds, and not scale?

2021-05-17 16:39 UTC, PhilMiller commented on src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
> +      avg, max, pole, imb, Timing::getTimeWithUnits(load/1000), should_lb
Do we want to format `avg, max, pole` too?

2021-05-17 18:27 UTC, lifflander commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      Timing::getTimeWithUnits(total_time), global_count
That's a good question. It will make scripts more difficult to parse correctly. Maybe we can have an option that keeps the units fixed (like always seconds or milliseconds?)

@nlslatt What do you think?

2021-05-17 19:19 UTC, nlslatt commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      Timing::getTimeWithUnits(total_time), global_count
Changing the units around on the fly would complicate the scripts greatly.  I'd like the option to force a single set of units for everything (and even that will require breaking changes to my scripts).

Even as a human reading the output, I dislike mixing units because then I have to convert units in my head to make sense of anything.  I'd rather just compare magnitudes directly.  Perhaps we should have a command-line option to specify the desired units for everything printed and just leave it at that?

Do we have any idea how much performance dynamic unit conversion is costing us?

2021-05-17 19:35 UTC, lifflander commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      Timing::getTimeWithUnits(total_time), global_count
I agree that an option like this is desirable. @cz4rs Can you implement that?

Regarding the overhead, I think dynamic unit selection probably costs on the order of tens to hundreds of cycles. If we have a ton of these prints each phase, it could impact performance depending on how large the phase is. We could make the dynamic unit selection an opt-in instead of an opt-out if that's preferable.

2021-05-18 15:55 UTC, cz4rs commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      Timing::getTimeWithUnits(total_time), global_count
1c00021 adds a runtime option (off by default). Note that all the `/1000` that I've added (converting back to seconds) cause the output to be changed anyways and can result in more `0.000000` values being printed.
```
vt: [0] (t) lb: BaseLB: Statistic=P_l:  max=0.003558, min=0.003558, sum=0.003558, avg=0.003558, var=0.000000, stdev=0.000000, nproc=1, cardinality=1 skewness=0.00, kurtosis=0.00, npr=1, imb=0.00, num_stats=2
vt: [0] (t) lb: BaseLB: Statistic=O_l:  max=0.000000, min=0.000000, sum=0.000004, avg=0.000000, var=0.000000, stdev=0.000000, nproc=64, cardinality=64 skewness=0.11, kurtosis=-1.04, npr=64, imb=1.00, num_stats=2
```

2021-05-18 16:14 UTC, nlslatt commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      Timing::getTimeWithUnits(total_time), global_count
Why can't we print with `%g` or something like that?

2021-05-18 17:50 UTC, cz4rs commented
DARMA weekly conclusion:
- wrap and store time values in a custom `struct`, create a custom formatter for that
- prohibit implicit conversion into `double`
- consider `std::chrono::duration` cooperability

2021-05-19 17:52 UTC, cz4rs commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      Timing::getTimeWithUnits(total_time), global_count
I will try to find the best format once all the infrastructure for printing / handling times is in place

2021-12-14 09:29 UTC, jstrzebonski commented on src/vt/timing/timing.h
>  struct Timing {
Do we need this struct? There's a `timing` namespace already, and both its member functions are static.

2021-12-14 17:15 UTC, cz4rs commented on src/vt/timing/timing.h
>  struct Timing {
Removed the `struct` :ok_hand:

2021-12-14 17:32 UTC, PhilMiller requested changes
I'd support scientific or engineering notation, but switching up units will make scripted consumption of the output needlessly difficult.

2022-01-07 19:10 UTC, PhilMiller approved these changes

2022-01-08 15:35 UTC, cz4rs commented
TODO: fix `vt-sample-project` build ([logs](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=26559&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=28db5144-7e5d-5c90-2820-8676d630d9d2)

2022-01-13 17:42 UTC, merged