#1294: tests: Compile perf tests
DARMA-tasking/vt pull request #1438
Opened 2021-05-14 15:16 UTC by JacobDomagala

Fixes #1294

2021-05-26 23:32 UTC, lifflander commented on tests/perf/common/scoped_timer.h
> +struct StopWatch {
I like the direction this is headed. I wonder if this might even be more general purpose and useful in other places in the system. Maybe in src/vt/utils?

2021-05-26 23:33 UTC, lifflander commented on tests/perf/common/scoped_timer.h
> +struct StopWatch {
Or scr/vt/timing

2021-06-05 12:55 UTC, JacobDomagala commented
### Node 0
[![](https://github.com/DARMA-tasking/vt/wiki/perf_tests/flame_heaptrack_jacobi_alloc_count_0.svg)](https://github.com/DARMA-tasking/vt/wiki/perf_tests/flame_heaptrack_jacobi_alloc_count_0.svg)
[![](https://github.com/DARMA-tasking/vt/wiki/perf_tests/flame_heaptrack_jacobi_alloc_size_0.svg)](https://github.com/DARMA-tasking/vt/wiki/perf_tests/flame_heaptrack_jacobi_alloc_size_0.svg)

### Node 1 
[![](https://github.com/DARMA-tasking/vt/wiki/perf_tests/flame_heaptrack_jacobi_alloc_count_1.svg)](https://github.com/DARMA-tasking/vt/wiki/perf_tests/flame_heaptrack_jacobi_alloc_count_1.svg)
[![](https://github.com/DARMA-tasking/vt/wiki/perf_tests/flame_heaptrack_jacobi_alloc_size_1.svg)](https://github.com/DARMA-tasking/vt/wiki/perf_tests/flame_heaptrack_jacobi_alloc_size_1.svg)

2021-06-23 21:06 UTC, lifflander commented
@JacobDomagala I really like your description at the top of this page. When we merge this in, can you add this info about the performance test harness/etc. to the wiki?

2021-06-23 21:10 UTC, lifflander commented
Is there a easy way to manually run this whole workflow (with the build-stats graph generation) and generate the graphs/data locally during development?

2021-06-23 21:33 UTC, lifflander requested changes
Overall this looks great. I have some suggestions for improvement along with some style suggestions.

2021-06-23 21:33 UTC, lifflander commented on ci/test_cpp.sh
> +ctest --output-on-failure -L unit_test | tee cmake-output.log
Does this also run the examples? Do we need to put those in a category also for consistency?

2021-06-23 21:33 UTC, lifflander commented on src/vt/epoch/epoch_window.cc
> +  vt_print(
Good catch. I accidentally committed this on develop and have been wanting to fix it!

2021-06-23 21:33 UTC, lifflander commented on tests/CMakeLists.txt
> +  GET_FILENAME_COMPONENT(
Prefer lower case here on `GET_FILENAME_COMPONENT` for consistency with other cmake function calls.

2021-06-23 21:33 UTC, lifflander commented on tests/CMakeLists.txt
> +  GET_FILENAME_COMPONENT(
```suggestion
  get_filename_component(
```

2021-06-23 21:33 UTC, lifflander commented on tests/perf/comm_cost_curve.cc
> -#include <vt/transport.h>
We may want to disable this performance test. It was never completed and originally intended to use to build communication weights as inputs to LBAF. I'm not sure of there there is any use for it now. Opinions from anyone?

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness.cc
> +      fmt::format("{:.6g}{}", std::get<1>(best_mem), std::get<0>(best_mem))));
Small whitespace change here to follow style guidelines (wrap parans to align with open).
```suggestion
      fmt::format("{:.6g}{}", std::get<1>(best_mem), std::get<0>(best_mem))
    )
  );
```

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness.cc
> +  std::function<void(OutputT&, InputT const&, std::size_t const)> populate) {
Another style suggestion:
```suggestion
  std::function<void(OutputT&, InputT const&, std::size_t const)> populate
) {
```

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness.h
> +  T mean_ = {};
I think we should add standard deviation or variance to these stats.

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness.h
> +  private:
```suggestion
private:
```

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness.h
> +  protected:
```suggestion
protected:
```

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness.h
> +  NodeType my_node_ = {};
Initialize these with the type sentinels:
```suggestion
  NodeType my_node_ = uninitialized_destination;
```

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness.h
> +  NodeType num_nodes_ = {};
```suggestion
  NodeType num_nodes_ = uninitialized_destination;
```

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness.h
> +  static CombinedResults combined_timings_;
It's preferable to avoid `static` variables here if possible. I think you might be able to turn this class into an VT objgroup, and then make the handlers non-static.

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness.h
> +  static CombinedResults combined_timings_;
You can look at a simple example here: https://github.com/DARMA-tasking/vt/blob/develop/examples/hello_world/objgroup.cc

You can allocate the harness yourself and then call `vt::theObjGroup()->makeCollective(this)` in the constructor for `PerfTestHarness`

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/timers.h
> +  private:
```suggestion
private:
```

2021-06-23 21:33 UTC, lifflander commented on tests/perf/common/test_harness_macros.h
> +          "\033[1mRunning test:\033[00m \033[32m{}\033[00m (Number of runs = " \
Maybe you can use the color functions here instead of using the control characters yourself.

2021-06-24 11:53 UTC, JacobDomagala commented on tests/perf/comm_cost_curve.cc
> -#include <vt/transport.h>
Both `comm_cost_curve` and `memory_checker` are disabled (see `EXCLUDED_PERF_TEST_FILES` vt/tests/CMakeListst.txt)
https://github.com/DARMA-tasking/vt/blob/71efd92973e1f947f9980e0f058dd972fccf5a48/tests/CMakeLists.txt#L209-L214

2021-06-24 11:54 UTC, JacobDomagala commented on tests/CMakeLists.txt
> +  GET_FILENAME_COMPONENT(
Updated all occurrences of this function call in our codebase, as it was mixture of uppercase and lowercase.

2021-06-24 11:56 UTC, JacobDomagala commented on ci/test_cpp.sh
> +ctest --output-on-failure -L unit_test | tee cmake-output.log
Good point, examples were skipped. I've added the label for them, and included them in test_cpp.sh

2021-06-24 12:11 UTC, JacobDomagala commented on tests/perf/common/test_harness_macros.h
> +          "\033[1mRunning test:\033[00m \033[32m{}\033[00m (Number of runs = " \
Good point

2021-06-24 17:36 UTC, lifflander commented on tests/CMakeLists.txt
> +  GET_FILENAME_COMPONENT(
Great, thanks!

2021-07-01 18:39 UTC, nlslatt commented
This is a great addition! The description in this PR is very useful.

Some of the files have lines far exceeding 80 columns. Can you please reformat?

2021-07-01 20:23 UTC, lifflander approved these changes
It looks like you have addressed my comments. This looks good to me!

2021-07-01 21:00 UTC, nlslatt approved these changes
Looks good

2021-07-02 07:52 UTC, merged