1469 Output LB statistics as JSON
DARMA-tasking/vt pull request #1475
Opened 2021-06-13 00:08 UTC by lifflander

Fixes #1469 

- [ ] Include new json library
- [ ] Include new compression library: brotli
- [ ] Write C++ wrapper for encoding streaming data using compression library
- [ ] Write output adaptor for the JSON library to stream output to compressed buffer
- [ ] Write C++ wrapper for decoding? Do we need this? Probably for the stats restart reader
- [ ] Adapt tests for new format
- [ ] Provide options to users to output JSON uncompressed?

Should we completely remove the old stat output or leave it as an option that the user can select until we decide to remove it?

2021-06-13 00:10 UTC, lifflander commented
@PhilMiller @JacobDomagala @jstrzebonski @ppebay @nlslatt 

I would like feedback on this PR!

2021-06-14 14:29 UTC, cz4rs commented on src/vt/utils/compress/compressor.h
> +#include <brotli/encode.h>
this could be replaced with a forward declaration of `BrotliEncoderState`

2021-06-14 15:06 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_stats.cc
> +#if CSV_STAT_FILE
is the CSV format going to be removed before merging this? (if not, runtime option would be preferred)

2021-06-14 15:10 UTC, jstrzebonski commented on src/vt/utils/json/output_adaptor.h
> +    }
You could just call `write_characters()` here.

2021-06-14 15:10 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_stats.h
> +#include "vt/utils/json/base_appender.h"
could be replaced with a forward declaration

2021-06-14 15:12 UTC, jstrzebonski commented on src/vt/vrt/collection/balance/node_stats.cc
> +
Maybe extract those two cases (`CSV_STAT_FILE` and `json`) into separate helper functions for better readability?

2021-06-14 15:16 UTC, jstrzebonski commented on src/vt/vrt/collection/balance/node_stats.h
> +  std::unique_ptr<util::json::BaseAppender> stat_writer_ = nullptr;
`stats_file_` and `stat_writer_` are not inside if-defs.

2021-06-14 18:06 UTC, nlslatt commented
@jliffla In response to whether or not we need a wrapper for decoding, we will need one for the LB testing and tuning drivers that I'm working on.  They currently read the old format and will break when we make this change.

2021-06-14 18:21 UTC, nlslatt commented on src/vt/utils/compress/compressor.impl.h
> +  vtAssert(enc_, "Must have a valid compressor");
This assert is redundant with the one in `writeImpl()`.

2021-06-14 18:22 UTC, nlslatt commented on src/vt/utils/compress/compressor.impl.h
> +  vtAssert(enc_, "Must have a valid compressor");
This assert is redundant with the one in `writeImpl()`.

2021-06-14 18:24 UTC, nlslatt commented
@lifflander Also, as to whether or not we keep the old format around for a while, I think it depends how quickly we'll have the new reader ready in LBAF.

2021-06-14 19:04 UTC, lifflander commented on src/vt/utils/compress/compressor.h
> +#include <brotli/encode.h>
That's a good point, but the library doesn't provide forward declarations for any of the types. I would have to declare it myself, which might not be best to maintain. I would also have to write the forward decl as a extern "C" since brotli is written in C.

I'm not super worried about this inclusion because `compressor.h` is very minimally included In fact, I think it's only included in one cc file and doesn't propagate very far.

2021-06-14 19:07 UTC, lifflander commented on src/vt/utils/json/output_adaptor.h
> +    }
Good point, fixed!

2021-06-14 19:16 UTC, lifflander commented on src/vt/vrt/collection/balance/node_stats.h
> +#include "vt/utils/json/base_appender.h"
The `BaseAppender` is a forward declaration (essentially). It doesn't include anything. I forgot to actually include that file when I pushed.

2021-06-14 19:17 UTC, lifflander commented on src/vt/vrt/collection/balance/node_stats.h
> +  std::unique_ptr<util::json::BaseAppender> stat_writer_ = nullptr;
Yes, I just have the ifdef as a temporary solution to test this version of the code. I need to decide if we are going to support both modes or just remove the old one.

2021-06-14 19:18 UTC, lifflander commented on src/vt/utils/compress/compressor.impl.h
> +  vtAssert(enc_, "Must have a valid compressor");
FIxed

2021-06-14 19:18 UTC, lifflander commented on src/vt/utils/compress/compressor.impl.h
> +  vtAssert(enc_, "Must have a valid compressor");
Fixed

2021-06-14 19:34 UTC, lifflander commented
I've created a related issue in LBAF for @marcinwrobel1986 to work on to support his new format with the Python bindings:
https://github.com/DARMA-tasking/LB-analysis-framework/issues/80

2021-06-14 20:40 UTC, cz4rs commented on src/vt/utils/compress/compressor.h
> +#include <brotli/encode.h>
Looks good, I didn't think of the impact of C for this.

2021-06-17 02:42 UTC, lifflander commented
@PhilMiller @nlslatt @marcinwrobel1986 @JacobDomagala @jstrzebonski @cz4rs 

I've finished implementing this along with adapting all the tests to use the new format! I've tested the input/output workflow with the StatsRestartReader to ensure that everything works properly.

2021-06-17 19:20 UTC, PhilMiller commented
In adding in the JSON and Brotli libraries, please make sure they can build into both static and dynamic libraries.

2021-06-17 19:27 UTC, lifflander commented
> In adding in the JSON and Brotli libraries, please make sure they can build into both static and dynamic libraries.

Brotli has both options. Which should I made the default? Currently, I have the dynamic ones by default linked with VT.

2021-06-17 19:27 UTC, lifflander commented
I'm in the hell right now of getting this to work with Intel/NVCC. I've worked around a lot of the errors, but had to make adjustments to the library's code

2021-06-17 19:31 UTC, PhilMiller commented
> > In adding in the JSON and Brotli libraries, please make sure they can build into both static and dynamic libraries.
> 
> Brotli has both options. Which should I made the default? Currently, I have the dynamic ones by default linked with VT.

I'm not too concerned about the defaults. Mostly, I just want to avoid us exacerbating the situation we have where libfort won't build a static library (so it's disabled in EMPIRE), and fcontext won't build a dynamic library (at least on nvcc), and so I have to static link everything when developing there. #1479

2021-06-17 20:17 UTC, lifflander commented
I found a patch for the warning on nvcc 11. This does not solve the major compile-time errors with nvcc 10

2021-06-18 16:52 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  std::size_t rank = name.find("%p");
duplicated code: this can be extracted into a helper function

2021-06-18 16:54 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  return vt_lb_stats_dir_in + "/" + name;
duplicated code: this can be extracted into a helper function

2021-06-18 16:58 UTC, cz4rs commented on src/vt/utils/compress/compressor.cc
> +//                           DARMA Toolkit v. 1.0.0
please remove all `DARMA Toolkit v. 1.0.0` lines (#1467 has been merged)

2021-06-18 17:31 UTC, cz4rs commented
@lifflander Can you add a sample JSON output somewhere? Either docs or even a unit test (so we are sure that it is always up to date).

2021-06-22 00:22 UTC, lifflander commented
I finally got the fix for nvcc 10.1 implemented. Rewrote half of their meta code before figuring out a somewhat simple fix. By swapping the template parameters of 4 trait classes, the bug goes away!

2021-06-22 00:23 UTC, lifflander commented
> @lifflander Can you add a sample JSON output somewhere? Either docs or even a unit test (so we are sure that it is always up to date).

Yes, will do.

2021-06-22 02:00 UTC, lifflander commented on src/vt/utils/compress/compressor.cc
> +//                           DARMA Toolkit v. 1.0.0
Ah, we need to fix the script `scripts/add-license-perl.pl` to properly put the template in. My elisp script generates the header using that script automatically when I create a new file.

2021-06-22 02:02 UTC, lifflander commented on src/vt/utils/compress/compressor.cc
> +//                           DARMA Toolkit v. 1.0.0
Oh, the license template was updated! When I rebased, I didn't rerun my script to regenerate based on the new template.

2021-06-22 21:44 UTC, lifflander commented on src/vt/configs/arguments/args.cc
> +  return vt_lb_stats_dir_in + "/" + name;
Fixed, extracted to helper function.

2021-06-22 21:52 UTC, nlslatt commented on lib/brotli/CMakeLists.txt
> +  # By default, brotli depends on undefined behavior, but setting
Does this comment concern you?

2021-06-22 22:03 UTC, lifflander commented on lib/brotli/CMakeLists.txt
> +  # By default, brotli depends on undefined behavior, but setting
I've implemented a fix for this to only build brotli in portable mode to avoid the undefined behavior.

2021-06-22 22:06 UTC, lifflander commented
I'm still working on the documentation update.

2021-06-24 17:38 UTC, lifflander commented
@nlslatt @JacobDomagala @jstrzebonski @cz4rs I would like more feedback on this issue if possible

2021-06-24 17:48 UTC, nlslatt commented on src/vt/vrt/collection/balance/stats_data.cc
> +            auto elm = ElementIDStruct{object, home, this_node};
Should this line use `node` (read from the json) instead of `this_node` (the current node, which will typically be the same as `node`)?

2021-06-24 17:49 UTC, nlslatt commented on src/vt/vrt/collection/balance/stats_data.cc
> +            auto elm = ElementIDStruct{object, home, this_node};
I guess allowing them to differ would require extra logic.  Looks like you already checked that they match.

2021-06-24 17:49 UTC, nlslatt commented on src/vt/vrt/collection/balance/stats_data.cc
> +          vtAssertExpr(node == theContext()->getNode());
You could use `this_node` here.

2021-06-24 18:54 UTC, nlslatt requested changes
I haven't reviewed all the code added to `lib/` (just your changes to the libraries), but overall I think this looks great.  Just some minor changes as indicated in the review comments.

2021-06-24 18:54 UTC, nlslatt commented on src/vt/utils/compress/decompressor.impl.h
> +      vtAssert(avail_in_ == 0, "Should not have more input if we need more");
Can you improve the error message here? It took me a minute to understand what this meant. Maybe something like "Brotli asked for more input even though we still had some."

2021-06-24 18:54 UTC, nlslatt commented on src/vt/utils/compress/decompressor.impl.h
> +        avail_out == 0, "Available output should be 0 if we need more output"
Same here. Maybe "Brotli asked for more output even though we still had some."

2021-06-24 18:54 UTC, nlslatt commented on docs/md/node-stats.md
> +The type of communication lines up the enum
Did you mean `lines up with the enum`?

2021-06-24 18:56 UTC, JacobDomagala approved these changes
Looks good to me.

2021-06-24 18:56 UTC, JacobDomagala commented on tests/unit/collection/test_lb.extended.cc
> +    EXPECT_EQ(len, num_phases);
This can be simplified to:
```c++
EXPECT_EQ(json["phases"].size(), num_phases);
```

2021-06-24 19:41 UTC, jstrzebonski commented on src/vt/vrt/collection/balance/stats_restart_reader.cc
> +    element_history.push_back(buffer);
Maybe it's over-optimization, but I think you could do `emplace_back(std::move(buffer))`.

2021-06-24 19:42 UTC, jstrzebonski commented on src/vt/vrt/collection/balance/stats_restart_reader.cc
> +    for (auto const& obj : sd->node_data_[phase]) {
Would you be able to convert this loop into for-each? Maybe something like this:
`for (auto const& nd : sd->node_data_) {`

2021-06-24 19:42 UTC, jstrzebonski commented on src/vt/vrt/collection/balance/stats_restart_reader.cc
> +  for (PhaseType phase = 0; phase < sd->node_data_.size(); phase++) {
Would you be able to convert this loop into for-each? Maybe something like this:
`for (auto const& nd : sd->node_data_) {`

2021-06-24 19:44 UTC, lifflander commented on src/vt/utils/compress/decompressor.impl.h
> +      vtAssert(avail_in_ == 0, "Should not have more input if we need more");
Good point, I definitely need to clarify this better in the messages.

2021-06-24 19:49 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.cc
> +            auto elm = ElementIDStruct{object, home, this_node};
Right now, the assertion is that they line up. Maybe I should assert that?

2021-06-24 19:51 UTC, nlslatt commented on src/vt/vrt/collection/balance/stats_data.cc
> +            auto elm = ElementIDStruct{object, home, this_node};
I think you already did that on line 182.  I hadn't noticed that when I posted the first comment.

2021-06-24 19:53 UTC, jstrzebonski commented on src/vt/utils/compress/compressor.cc
> +  out_buf_ = std::make_unique<uint8_t[]>(buf_size);
Just for consistency with the usage of members in this ctor:
```suggestion
  out_buf_ = std::make_unique<uint8_t[]>(buf_size_);
```

2021-06-24 20:06 UTC, jstrzebonski commented on src/vt/utils/compress/compressor.impl.h
> +  StreamLike& s, uint8_t const* buffer, std::size_t const size, bool finish_
I see the point in the usage of `finish_`, but to be honest, I'm not a fan of changing the behaviour of the function with a boolean variable. But from the top of my head, I don't have any clever idea of refactoring this function. So I'm fine with leaving it be.

2021-06-24 20:09 UTC, jstrzebonski commented on src/vt/utils/compress/compressor.impl.h
> +  return writeImpl(s, buffer, size, false);
Just for readability would you mind extracting this `false` into a well-named `constexpr` variable?
Maybe simply:
```cpp
constexpr auto finish = false;
```


And the same goes for the `finish()` function.

2021-06-24 20:12 UTC, jstrzebonski commented on src/vt/utils/compress/compressor.h
> +  );
BTW, why it's protected? The dtor is not virtual, and I don't see any suggestions to inheriting from this struct.

2021-06-24 20:24 UTC, jstrzebonski commented on src/vt/utils/json/decompression_input_container.impl.h
> +  len_ = d_->read(reinterpret_cast<uint8_t*>(output_buf_.get()), chunk_size_);
I see a lot of casting to `uint8_t`. Maybe `output_buf_` could be of type `u_ptr<uint8_t[]>`? That way you would have to do casting to `char` in `getCurrent()`, I don't if anywhere else..

2021-06-24 20:30 UTC, jstrzebonski commented on src/vt/utils/json/json_reader.cc
> +  }
Maybe this block could be extracted to a function `bool isFileCompressed()`?

2021-06-24 21:06 UTC, jstrzebonski commented on src/vt/vrt/collection/balance/stats_data.cc
> +                }
Couldn't you do something like `std::vector<uint64_t> arr = idx` or `arr = idx.get<std::vector<>>()`?

2021-06-24 21:12 UTC, jstrzebonski approved these changes
I left some minor notes and suggestions, but this looks really great!

2021-06-24 21:50 UTC, cz4rs commented on src/vt/vrt/collection/balance/stats_data.cc
> +  }
this makes me think that extracting some helpers could help readability

2021-06-24 21:59 UTC, cz4rs commented on src/vt/vrt/collection/balance/stats_data.cc
> +  std::unique_ptr<nlohmann::json> jin
is `unique_ptr` really needed here? what about simply passing a const reference instead?

2021-06-24 22:14 UTC, cz4rs commented on src/vt/vrt/collection/balance/stats_data.h
> +  static std::unique_ptr<StatsData> fromJson(std::unique_ptr<nlohmann::json> j);
We could simply return an object instead of `unique_ptr` - copy elision (and NRVO?) should let us avoid unnecessary copies. This would require change in `readIntoElementHistory`, but passing as a const ref should be good enough there.

2021-06-24 22:15 UTC, cz4rs commented on src/vt/vrt/collection/balance/stats_data.h
> +  static std::unique_ptr<StatsData> fromJson(std::unique_ptr<nlohmann::json> j);
Another thing is that it could simply become a constructor, but I don't have a strong opinion about this - static method works fine as well.

2021-06-24 23:27 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.cc
> +            auto elm = ElementIDStruct{object, home, this_node};
Ok, I've fixed this.

2021-06-24 23:28 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.cc
> +          vtAssertExpr(node == theContext()->getNode());
Fixed

2021-06-24 23:30 UTC, lifflander commented on src/vt/utils/compress/decompressor.impl.h
> +      vtAssert(avail_in_ == 0, "Should not have more input if we need more");
Fixed

2021-06-24 23:30 UTC, lifflander commented on src/vt/utils/compress/decompressor.impl.h
> +        avail_out == 0, "Available output should be 0 if we need more output"
Fixed

2021-06-24 23:31 UTC, lifflander commented on docs/md/node-stats.md
> +The type of communication lines up the enum
Yes, fixed

2021-06-24 23:33 UTC, lifflander commented on tests/unit/collection/test_lb.extended.cc
> +    EXPECT_EQ(len, num_phases);
Fixed

2021-06-24 23:34 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_restart_reader.cc
> +    element_history.push_back(buffer);
Done

2021-06-24 23:38 UTC, lifflander commented on src/vt/utils/compress/compressor.cc
> +  out_buf_ = std::make_unique<uint8_t[]>(buf_size);
Done

2021-06-24 23:39 UTC, lifflander commented on src/vt/utils/compress/compressor.impl.h
> +  StreamLike& s, uint8_t const* buffer, std::size_t const size, bool finish_
I initially had two different functions (one for finishing and one for incremental writes). The problem is that I have to duplicate basically this whole function so I combined them.

2021-06-24 23:41 UTC, lifflander commented on src/vt/utils/compress/compressor.impl.h
> +  return writeImpl(s, buffer, size, false);
Done!

2021-06-24 23:41 UTC, lifflander commented on src/vt/utils/compress/compressor.h
> +  );
Good point. I think it should just be `private`

2021-06-24 23:43 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.cc
> +  std::unique_ptr<nlohmann::json> jin
The reason I have to use `unique_ptr` is to avoid leaking the json headers all around VT. I don't really like using a pointer, but that's the only to avoid header propagation.

2021-06-24 23:44 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.h
> +  static std::unique_ptr<StatsData> fromJson(std::unique_ptr<nlohmann::json> j);
Same problem here. Then everything that includes `stats_data.h` will need the full json header which is massive. I only include the forward decls here.

2021-06-24 23:58 UTC, lifflander commented on src/vt/utils/json/json_reader.cc
> +  }
Done

2021-06-24 23:59 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.cc
> +                }
Good idea! Done

2021-06-25 00:15 UTC, lifflander commented on src/vt/utils/json/decompression_input_container.impl.h
> +  len_ = d_->read(reinterpret_cast<uint8_t*>(output_buf_.get()), chunk_size_);
Good idea, changed the type and now there's only one cast.

2021-06-25 00:21 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_restart_reader.cc
> +  for (PhaseType phase = 0; phase < sd->node_data_.size(); phase++) {
The problem is that `sd->node_data_` is an `unordered_map` but these need to be traversed in the correct order for `element_history` to be correct. So I can't use an iterator.

2021-06-25 11:14 UTC, cz4rs approved these changes
Looks good to me!

2021-06-25 12:27 UTC, cz4rs commented on src/vt/vrt/collection/balance/stats_data.h
> +  static std::unique_ptr<StatsData> fromJson(std::unique_ptr<nlohmann::json> j);
`fromJson` can probably be improved a bit, but now I see that returning a pointer with `toJson` is the way to go (to keep forward declarations).

I took a moment to check what can be done, please have a look at 4c112383a4dfbc9b53186f13787e683361e21ac3 and cherry-pick that if you like it.

2021-06-25 12:31 UTC, cz4rs commented on src/vt/vrt/collection/balance/stats_restart_reader.cc
> +    for (auto const& obj : sd->node_data_[phase]) {
While checking the possibility to pass const ref (from the other conversation), I have noticed that this can actually insert an element into node data the phase data is missing for some reason (`sd` is not `const`).

2021-06-25 20:27 UTC, nlslatt approved these changes
I'm okay with merging this after addressing the point that @cz4rs made about the LB stats reader.

2021-06-25 20:27 UTC, nlslatt commented on src/vt/vrt/collection/balance/stats_restart_reader.cc
> +    for (auto const& obj : sd->node_data_[phase]) {
I think the stats restart reader can operate with missing phases (where no LB migrations happened), so it would be a good idea to address this.

2021-06-28 18:01 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.h
> +  static std::unique_ptr<StatsData> fromJson(std::unique_ptr<nlohmann::json> j);
Looks good, I like your changes a lot!

2021-06-28 18:30 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_restart_reader.cc
> +    for (auto const& obj : sd->node_data_[phase]) {
@cz4rs's changes address this, which I have cherry-picked.

2021-06-28 21:56 UTC, merged