#1476: epoch guard
DARMA-tasking/vt pull request #1579
Opened 2021-10-12 16:49 UTC by nmm0

Closes #1476

2021-10-13 19:49 UTC, lifflander commented
> > Do you think we should do `finishedEpoch` also in the guard?
> 
> It does some weird to have `finishedEpoch` outside of it but I thought we decided not to do that. Maybe have it controlled by a boolean and also have a member function called .finish()?

I do think there are two use cases. One where the epoch is just being used inside a function and will be used in others. There is another use case where the epoch is created and should be finished all within a scope. Maybe for that one we should have a different guard that also creates the epoch? What do you think @PhilMiller?

2021-10-13 19:53 UTC, PhilMiller commented
I'd suggest grepping for use cases and see if there's a mix, or it's skewed all to one or the other.

I find the idea of a distinct type that will call finished mildly appealing, but I'd want to see how it would work out

2021-11-02 18:42 UTC, lifflander requested changes

2021-11-02 18:42 UTC, lifflander commented on src/vt/termination/epoch_guard.h
> +  public:
```suggestion
public:
```

2021-11-02 18:42 UTC, lifflander commented on src/vt/termination/epoch_guard.h
> +  private:
```suggestion
private:
```

2021-11-02 18:42 UTC, lifflander commented on src/vt/termination/epoch_guard.h
> +struct epoch_guard {
Can you add some doxygen for this class and the public functions?

2021-11-02 19:40 UTC, nmm0 commented on src/vt/termination/epoch_guard.h
> +struct epoch_guard {
Woops, mixing up all the naming conventions from my projects :P Fixed now.

2021-11-02 19:40 UTC, nmm0 commented on src/vt/termination/epoch_guard.h
> +  public:
Fixed, see #1592

2021-11-02 19:41 UTC, nmm0 commented on src/vt/termination/epoch_guard.h
> +struct epoch_guard {
Added doxygen documentation

2021-11-02 19:41 UTC, nmm0 commented on src/vt/termination/epoch_guard.h
> +  private:
Fixed, see #1592

2021-11-02 19:45 UTC, lifflander approved these changes
Looks good to me!

2021-11-05 15:07 UTC, cz4rs commented on src/vt/termination/epoch_guard.cc
> +#include "../messaging/active.h"
Consistency: we are using `#include "vt/messaging/active.h"` style everywhere else.

2021-11-05 15:12 UTC, cz4rs approved these changes
Looks good to me.

2021-11-09 00:15 UTC, nmm0 commented on src/vt/termination/epoch_guard.cc
> +#include "../messaging/active.h"
Fixed this and rebased on develop

2021-11-09 00:16 UTC, nmm0 commented
Rebased on develop

2021-11-09 09:36 UTC, cz4rs commented
> Rebased on develop

I think this is ready to merge, `clang-10` is a separate issue and Codacy seems to be getting stuck recently :|

2021-11-15 19:55 UTC, lifflander commented
> > Rebased on develop
> 
> I think this is ready to merge, `clang-10` is a separate issue and Codacy seems to be getting stuck recently :|

Agreed. @nmm0 can you rebase this again?

2021-11-17 23:14 UTC, nmm0 commented
> > > Rebased on develop
> > 
> > 
> > I think this is ready to merge, `clang-10` is a separate issue and Codacy seems to be getting stuck recently :|
> 
> Agreed. @nmm0 can you rebase this again?

Should be up to date!

2021-11-18 21:26 UTC, merged