1569 Model loads of potential object reassignment from load balancing
DARMA-tasking/vt pull request #1583
Opened 2021-10-20 19:35 UTC by PhilMiller

Fixes #1569 
Fixes #1568

2021-11-02 19:56 UTC, lifflander commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +    r.arrive_[obj_id] = load_summary;
Done

2021-11-02 19:56 UTC, lifflander commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      r.arrive_[obj_id] = getObjectLoads(
Ok, I've removed this so it adds it later

2021-11-02 19:56 UTC, lifflander commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +  pending_reassignment_ = std::make_unique<Reassignment>();
Moved to there

2021-11-02 21:54 UTC, lifflander commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      vtAbort(
Ok, I've addressed this.

2021-11-02 21:54 UTC, lifflander commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +      // The user has specified a migration neither on the send or receive side
```suggestion
      // The user has specified a migration neither on the send nor the receive side
```

2021-11-03 00:03 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +    if (migrate_other.size() > 0) {
Why is this `if` necessary? If `migrate_other` is empty, then the `for` loop will just not do anything.

2021-11-03 00:09 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +  auto& r = *pending_reassignment_.get();
Stylistically, could we not do this? Just say `pending_reassignment_->foo()` instead of `r.foo`

2021-11-03 00:09 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +   * sides regardless of how they are pass to \c migrateObjectTo
Typo: passed

2021-11-03 00:11 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +  void arriveLoadSummary(TransferMsg<DepartListType>* msg);
I'm not a fan of how these handlers and their message types are named. They pose issues of comprehension/readability regarding which side each of them runs on.

2021-11-03 00:12 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +  void arriveLoadSummary(TransferMsg<DepartListType>* msg);
That said, I'm satisfied that it will work as intended.

2021-11-18 06:22 UTC, PhilMiller commented
I still need to add a unit test suite for the new model implementation

2021-11-18 21:17 UTC, lifflander commented on src/vt/vrt/collection/balance/lb_common.h
> +using LoadMapType         = std::unordered_map<ElementIDStruct, LoadSummary>;
I think this begs the question should be include the communication also as part of the "LoadSummary"? Also, why is it a "summary"?

2021-11-18 21:17 UTC, lifflander commented on src/vt/vrt/collection/balance/lb_common.h
>    TimeType whole_phase_load_;
Since these have an underscore it would seem they are private, but they aren't. We should change that or add getters for them and use those throughout.

2021-11-18 21:17 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.cc
> +		  this->node_data_[id][elm].subphase_loads_.resize(
indentation..

2021-11-19 00:40 UTC, PhilMiller commented on src/vt/vrt/collection/balance/lb_common.h
> +using LoadMapType         = std::unordered_map<ElementIDStruct, LoadSummary>;
I wouldn't be averse to including stats on message counts and sizes, per subphase. That's still pretty light.

It's a summary because it doesn't describe the individual handlers or their invocations that contribute the load in question

2021-11-19 00:42 UTC, PhilMiller commented on src/vt/vrt/collection/balance/lb_common.h
> +using LoadMapType         = std::unordered_map<ElementIDStruct, LoadSummary>;
That level of communication data would allow models like CommOverhead and more sophisticated variants thereof to work without needing to capture the full communication graph

2021-11-19 00:44 UTC, PhilMiller commented on src/vt/vrt/collection/balance/lb_common.h
>    TimeType whole_phase_load_;
Oops, yeah, will fix. I had misapprehended the style guide

2021-11-23 19:13 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.h
>    );
Take `Reassignment` as an argument, and make this a `static` method rather than `instance`

2021-11-23 19:15 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +  for (auto&& transfer : transfers_) {
Skip this for now, to avoid further changes to strategies like Hierarchical and Greedy that communicate in terms of sampled object loads and not identities

2021-11-23 19:16 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +    if (migrate_other.size() > 0) {
Delete `if`

2021-11-23 19:17 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +  auto& r = *pending_reassignment_.get();
To change

2021-11-23 19:19 UTC, lifflander commented on src/vt/vrt/collection/balance/lb_common.h
> +using LoadMapType         = std::unordered_map<ElementIDStruct, LoadSummary>;
Let's do this in a later pull request (#1601)

2021-11-23 19:33 UTC, PhilMiller commented
Add unit testing on normalization

2021-11-24 20:48 UTC, PhilMiller commented
@lifflander Implementing the object iterator over the proposed reassignment directly was a huge pain in the ass. Decomposing it to filtering and concatenation made it rather easy.

2021-11-24 21:15 UTC, PhilMiller commented
And, I've got a way to get back the range `for` syntax, since I can just use `ObjectIterator{nullptr}` as the sentinel value.

2021-11-24 23:28 UTC, PhilMiller commented on src/vt/vrt/collection/balance/model/proposed_reassignment.cc
> +struct FilterIterator : public ObjectIteratorImpl
I may want to move this somewhere other code can use it, since it may be helpful in implementing iteration over just migratable objects

2021-11-24 23:40 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +}
This could now trivially move out of `BaseLB`

2021-11-24 23:41 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +}
#1568 in other words

2021-11-25 00:23 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +  for (auto&& transfer : transfers_) {
This could maybe go into #1601 at least in part

2021-11-29 22:57 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +  static void applyReassignment(const std::shared_ptr<const balance::Reassignment> &reassignment);
This became a free function over in `lb_common.cc`, so I should remove the prototype here.

```suggestion
```

2021-11-29 23:05 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +
```suggestion
```

2021-11-29 23:19 UTC, PhilMiller commented on src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
> +  // FIXME: Actually reduce over the reassignments
This needs to be addressed before merge

2021-11-29 23:23 UTC, PhilMiller commented on src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
> +  auto reassignment = strat->normalizeReassignments();
With two changes, the strategy invocation could be a single, self-contained function call that takes statistics, and returns a proposed reassignment:
* Move the `runInEpochCollective` call inside `startLB`
* Move the `normalizeReassignments` call inside `startLB`, and return its result.
I think I'll go ahead with that, since it's now such low hanging fruit to reach the design endpoint we'd been aiming for, of essentially a pure function.

2021-11-30 18:41 UTC, PhilMiller commented
Need to clean up some node stats reader/writer bits, to avoid inconsistency

2021-11-30 18:41 UTC, nlslatt commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +void BaseLB::notifyDeparting(TransferMsg<DepartListType>* msg) {
I find it very counter-intuitive for a call to `notifyDeparting` on a given rank to be telling that rank to expect arrivals, while `notifyArriving` tells the rank to expect departures.

2021-11-30 18:50 UTC, nlslatt commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +  void arriveLoadSummary(TransferMsg<DepartListType>* msg);
I agree, but I think they actually need to be renamed.

2021-11-30 20:46 UTC, nlslatt requested changes
It looks really close. In addition to the renaming mentioned previously, I think there is an unused variable to clean up. Also, there appear to be parts of this PR that deviate from the style guidelines.

2021-11-30 20:46 UTC, nlslatt commented on tests/unit/collection/test_model_select_subphases.nompi.cc
>    ProcSubphaseLoadMap proc_subphase_load = {
Is this needed anymore?

2021-11-30 20:46 UTC, nlslatt commented on tests/unit/collection/test_lb.extended.cc
> +            EXPECT_EQ(orig_load.subphase_loads, read_load.subphase_loads);
These checks were written out the long way before to provide useful debugging information in the event of a problem. While much more concise, this change will greatly increase the debugging effort required in the event of a test failure.

2021-11-30 21:02 UTC, PhilMiller commented on tests/unit/collection/test_model_select_subphases.nompi.cc
>    ProcSubphaseLoadMap proc_subphase_load = {
Nope, cleaned it out.

2021-11-30 21:26 UTC, PhilMiller commented on tests/unit/collection/test_lb.extended.cc
> +            EXPECT_EQ(orig_load.subphase_loads, read_load.subphase_loads);
With the changed representation of internal structures, there's no longer a possibility of having whole phase data for some object but no subphase data, so all of the checking that exactly the right set of things are found is now superfluous.

In the event of failure, GTest prints out the text of the expressions and their values, so mismatches in size or contained values in the subphase timing arrays should be visible.

For more detailed inspection, we can still run under `gdb` or `lldb` with `--gtest_break_on_failure`.

2021-11-30 23:35 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +void BaseLB::notifyDeparting(TransferMsg<DepartListType>* msg) {
Is the revised implementation clearer?

2021-11-30 23:52 UTC, PhilMiller commented on src/vt/vrt/collection/balance/lb_common.h
> +using ElementIDMemberType = vt::vrt::collection::balance::ElementIDType;
These type aliases should probably not appear in `namespace std`. I'm just going to inline them

2021-12-01 00:07 UTC, lifflander approved these changes
The new changes to the normalization look good to me

2021-12-01 18:04 UTC, PhilMiller commented
Looking ahead, I realize the interface to the LB strategies is perhaps a bit over-simplified. If we want to run multiple strategies or configurations thereof concurrently, we need them to be asynchronous from the caller's perspective. This may not be that hard for the caller to achieve, since it could just make each strategy call in a separate handler invocation.

2021-12-01 19:18 UTC, nlslatt approved these changes
Just a little cleanup as previously discussed

2021-12-01 19:18 UTC, nlslatt commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +                      &BaseLB::notifyCurrentHostNodeOfObjectsDeparting>
Wrapping

2021-12-01 19:18 UTC, nlslatt commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +    using ArriveListMsgType = TransferMsg<ObjDestinationListType>;
I'm not thrilled with the name here but can live with it.

2021-12-01 19:18 UTC, nlslatt commented on src/vt/vrt/collection/balance/lb_invoke/lb_manager.h
> +                         bool comm_collectives, PhaseType phase);
Wrapping

2021-12-01 19:18 UTC, nlslatt commented on src/vt/vrt/collection/balance/model/load_model.h
>                          std::unordered_map<PhaseType, CommMapType> const* proc_comm) = 0;
Wrapping

2021-12-01 19:18 UTC, nlslatt commented on src/vt/vrt/collection/balance/model/proposed_reassignment.h
> +                       std::shared_ptr<const Reassignment> reassignment);
Wrapping

2021-12-01 19:18 UTC, nlslatt commented on tests/unit/collection/test_model_select_subphases.nompi.cc
> +    return {std::make_unique<LoadMapObjectIterator>(proc_load_->at(0).begin(), proc_load_->at(0).end())};
Really long line

2021-12-01 22:07 UTC, lifflander commented
Ok, I have adjusted the formatting.

2021-12-01 23:54 UTC, merged

2021-12-07 02:29 UTC, PhilMiller commented on src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
If I just make `cb` an argument to `computeStatistics` and pass this from the call site, then we can easily generalize to multiple candidate LB runs and distinguish them.