#1589 Read in communication data from json files
DARMA-tasking/vt pull request #1603
Opened 2021-11-08 19:52 UTC by nlslatt

Fixes #1589

2021-11-15 20:06 UTC, lifflander requested changes

2021-11-15 20:06 UTC, lifflander commented on tests/unit/collection/test_lb.extended.cc
> +  //vt::runInEpochCollective([=]{
Should we remove this line?

2021-11-15 20:06 UTC, lifflander commented on tests/unit/collection/test_lb.extended.cc
> +      vtAbort(fmt::format(
Normally, I would use `EXPECT_EQ` here, but it is nice to have the a good error message. `EXPECT_EQ` allows the test infrastructure to keep going instead of just failing the whole process out. Can we make these just prints when it's not equal?

2021-11-16 18:59 UTC, nlslatt commented on tests/unit/collection/test_lb.extended.cc
> +  //vt::runInEpochCollective([=]{
Removed.

2021-11-16 18:59 UTC, nlslatt commented on tests/unit/collection/test_lb.extended.cc
> +      vtAbort(fmt::format(
Fixed.

2021-11-16 19:05 UTC, nlslatt commented on tests/unit/collection/test_lb.extended.cc
> +  // @todo: clean up files
@lifflander Do you think it's important to clean up the files this test produces before merging?

2021-11-17 02:22 UTC, lifflander requested changes

2021-11-17 02:22 UTC, lifflander commented on tests/unit/collection/test_lb.extended.cc
> +  using JSONAppender = vt::util::json::Appender<std::ofstream>;
I would recommend that we do this in-memory to avoid any file system issues:

```C++
StatsData getStatsDataForPhase(vt::PhaseType phase,  vt::vrt::collection::balance::StatsData in) {
  using JSONAppender = vt::util::json::Appender<std::stringstream>;
  using vt::util::json::DecompressionInputContainer;
  using vt::vrt::collection::balance::StatsData;
  using json = nlohmann::json;
  std::stringstream ss{std::ios_base::out | std::ios_base::in};
  auto ap = std::make_unique<JSONAppender>("phases", std::move(ss), false);
  auto j = in.toJson(phase);
  ap->addElm(*j);
  ss = ap->finish();
  //fmt::print("{}\n", ss.str());
  auto c = DecompressionInputContainer{
    DecompressionInputContainer::AnyStreamTag{}, std::move(ss)
  };
  return StatsData{json::parse(c)};
}
```

2021-11-17 02:22 UTC, lifflander commented on tests/unit/collection/test_lb.extended.cc
> +  // @todo: clean up files
I think we should just do this in memory. I have a snippet below to do this..

2021-11-18 19:50 UTC, nlslatt commented on tests/unit/collection/test_lb.extended.cc
> +  using JSONAppender = vt::util::json::Appender<std::ofstream>;
I couldn't get this to compile using decompression, so my incorporation of this does not include compression. The json is fairly small so I don't think it's a big deal.

2021-11-18 19:51 UTC, nlslatt commented on tests/unit/collection/test_lb.extended.cc
> +  // @todo: clean up files
I incorporated a slightly modified version of your snippet that does not include compression/decompression.

2021-11-18 20:41 UTC, lifflander approved these changes
Looks good to me now!

2021-11-29 23:55 UTC, lifflander commented
@nlslatt Can you rebase this PR so we can merge it?

2021-11-30 17:07 UTC, merged