#1636 add API for temporarily enabling/disabling debug prints
DARMA-tasking/vt pull request #1658
Opened 2022-01-14 11:50 UTC by jstrzebonski

Fixes #1636

2022-01-14 15:45 UTC, jstrzebonski commented
@nmm0 Is it something that might come in handy for your use cases?

2022-01-17 19:20 UTC, nmm0 commented
> @nmm0 Is it something that might come in handy for your use cases (take a look at simplified usage in unit tests)?

Yes, this is perfect, especially the scoped version. In my use cases I often want to get the prints from a specific function.

2022-01-17 19:22 UTC, nmm0 approved these changes
Looks good to me! Only thing I'd want to add is some documentation just to make developers aware of the feature.

2022-01-18 13:51 UTC, jstrzebonski commented
> Looks good to me! Only thing I'd want to add is some documentation just to make developers aware of the feature.

Documentation added.

2022-01-18 14:16 UTC, JacobDomagala approved these changes

2022-01-18 16:10 UTC, cz4rs commented on src/vt/configs/debug/debug_print.h
> +  ::vt::debug::preConfigRef()->vt_debug_##opt = true
I wonder if it makes sense to use `preConfigRef()` instead of simply `theConfig() here.

2022-01-18 16:14 UTC, cz4rs commented on src/vt/configs/debug/debug_print.h
> +  ::vt::debug::preConfigRef()->vt_debug_##opt = true
If we stick with this, consider following scenario:
```cpp
vt_debug_temp_enable_opt(all);

vt::initialize();

EXPECT_EQ(theConfig()->vt_debug_all, true); // or false? vt::initialize might overwrite the value with default
```

2022-01-19 18:26 UTC, jstrzebonski commented on src/vt/runtime/runtime_get.cc
> +arguments::AppConfig* preConfigRef() {
This whole change is now reverted.

2022-01-19 18:27 UTC, jstrzebonski commented on src/vt/configs/debug/debug_print.h
> +  ::vt::debug::preConfigRef()->vt_debug_##opt = true
I'm using `theConfig()` instead of `preConfigRef()`, and I added comment about necessity of vt initialization.

2022-01-20 16:15 UTC, cz4rs approved these changes
Looks good to me!

2022-01-20 20:12 UTC, lifflander requested changes
This looks great to me. The only change I would suggest is checking to see if VT is live, and then printing an appropriate error/exception/abort if it isn't.

2022-01-24 18:45 UTC, jstrzebonski commented
> This looks great to me. The only change I would suggest is checking to see if VT is live, and then printing an appropriate error/exception/abort if it isn't.

Done

2022-01-24 18:46 UTC, jstrzebonski commented on src/vt/configs/debug/debug_print.cc
> +    if (not curRT) {                                                           \
Is there a better way to tell if vt's been initialized already?

2022-01-25 00:38 UTC, lifflander commented on src/vt/configs/debug/debug_print.cc
> +    if (not curRT) {                                                           \
You could just check `if (vt::theConfig())` which might make a little more sense in this context.

2022-01-25 00:39 UTC, lifflander requested changes

2022-01-25 00:39 UTC, lifflander commented on src/vt/configs/debug/debug_print.h
> +  theConfig()->vt_debug_##opt = true
We need to qualify all of these calls to `theConfig()` with `::vt::theConfig()` because they might not be in the VT namespace for application code.

2022-01-25 10:11 UTC, jstrzebonski commented on src/vt/configs/debug/debug_print.h
> +  theConfig()->vt_debug_##opt = true
Done.

2022-01-25 10:15 UTC, jstrzebonski commented on src/vt/configs/debug/debug_print.cc
> +    if (not curRT) {                                                           \
I agree, checking that looks better in this context, but internally it uses two pointers before it returns config, so if vt is not initialized, I think the program would (at best) segfault.

```cpp
vt::arguments::AppConfig *theConfig() { return &CUR_RT->theArgConfig->config_; }
```

2022-01-25 13:04 UTC, jstrzebonski commented
There are still some funky compilation errors with fcontext and unity build enabled.

2022-01-25 18:13 UTC, lifflander approved these changes
Looks good once we can get CI passing!

2022-02-01 22:29 UTC, merged