#1550 allow passing appconfig to vt during init
DARMA-tasking/vt pull request #1674
Opened 2022-02-15 09:58 UTC by jstrzebonski

Fixes #1550 

---
TODO:
- [ ] print options overwritten by CLI arguments

2022-02-16 21:14 UTC, jstrzebonski commented
Printing options predefined in source code, that are overwritten by CLI arguments:

![image](https://user-images.githubusercontent.com/14062470/154358175-72bac390-4460-4e0f-a47c-62ccc8b814e4.png)

![image](https://user-images.githubusercontent.com/14062470/154358248-feb97564-1902-4bfc-8e2b-473d3f60352b.png)

2022-02-17 14:58 UTC, cz4rs commented on tests/unit/runtime/test_initialization.cc
> +  // CLI args should overwritten hardcoded appConfig
`should overwrite` / `should have overwritten`

2022-02-17 14:58 UTC, cz4rs commented
@jstrzebonski This functionality should be mentioned in documentation and the precedence should be described explicitly (`test_initialization.cc` helps too :+1:).

2022-02-17 15:10 UTC, jstrzebonski commented on tests/unit/runtime/test_initialization.cc
> +  // CLI args should overwritten hardcoded appConfig
Done.

2022-02-22 17:58 UTC, cz4rs requested changes
Please add a short description into docs (basically a more user-friendly way to tell users what you wrote in unit tests - `  // CLI args should overwrite hardcoded appConfig`).

2022-02-22 18:00 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  );
This was not added in this PR, but I wonder whether this works / is used somewhere?

2022-02-23 17:52 UTC, jstrzebonski commented on src/vt/configs/arguments/args.cc
> +  );
Documented and covered by unit tests.

2022-02-23 17:54 UTC, jstrzebonski commented
CLI11 parses configuration file before command-line arguments. I added appropriate documentation and two new unit tests covering this behavior.

2022-02-23 20:11 UTC, cz4rs approved these changes
👍

2022-02-24 19:03 UTC, lifflander approved these changes
Looks good to me!

2022-03-01 20:55 UTC, nlslatt commented
Note that the automatic rebase feature doesn't retain signatures. I'll fix it.

2022-03-01 21:09 UTC, jstrzebonski commented
> Note that the automatic rebase feature doesn't retain signatures. I'll fix it.

No problem, I've just force-pushed.

2022-03-02 00:29 UTC, merged