[WIP] 1672: Implement the total work LB algorithm in TemperedLB
DARMA-tasking/vt pull request #1695
Opened 2022-03-08 14:11 UTC by cz4rs

fixes #1672

2022-03-23 05:58 UTC, lifflander commented
Looks good so far!

2022-03-30 17:49 UTC, PhilMiller commented on src/vt/vrt/collection/balance/model/load_model.h
> +  virtual TimeType getLoad(ElementIDStruct object, PhaseOffset when) = 0;
If we're renaming this anyway, let's go fully abstract, and make it clear that it's just "the quantity that load-balancing strategies should try to balance": `getLoadMetric`

2022-04-06 16:52 UTC, cz4rs commented on src/vt/elm/elm_stats.h
> +  TimeType getLoadMetric(PhaseType const& phase) const;
TODO: these methods got caught by `sed` renaming, but maybe they should remain as they were

2022-04-19 19:32 UTC, nlslatt reviewed
Most of this looks great. I do see some TODO comments that I'm not sure if you plan to address right away. Have you added a test to check making the graph symmetric?

A significant difference between the two tempered versions is that `TemperedLB` has the concept of overloaded vs underloaded ranks whereas the total work version should not. I don't see that reflected in this PR.

2022-04-20 17:04 UTC, cz4rs commented on src/vt/elm/elm_stats.h
> +  TimeType getLoadMetric(PhaseType const& phase) const;
Keeping the `getLoadMetric` for the sake of consistency.

2022-04-20 17:08 UTC, cz4rs commented on src/vt/vrt/collection/balance/temperedlb/temperedlb.h
> +  std::mt19937 gen_propagate_;
TODO: this should remain private

2022-04-20 17:09 UTC, cz4rs commented
> Most of this looks great. I do see some TODO comments that I'm not sure if you plan to address right away. Have you added a test to check making the graph symmetric?
> 
> A significant difference between the two tempered versions is that `TemperedLB` has the concept of overloaded vs underloaded ranks whereas the total work version should not. I don't see that reflected in this PR.

Thanks for the review, I will address the TODOs and add the test.

2022-04-20 17:17 UTC, ppebay requested changes

2022-04-20 17:17 UTC, ppebay commented on src/vt/elm/elm_stats.cc
> +    return getLoadMetric(phase);
I am not convinced by the `Metric` naming.

2022-04-20 17:17 UTC, ppebay commented on src/vt/vrt/collection/balance/greedylb/greedylb.cc
> +  auto const& obj_time_milli = loadMilli(load_model_->getLoadMetric(obj_id, {balance::PhaseOffset::NEXT_PHASE, balance::PhaseOffset::WHOLE_PHASE}));
Are you sure this is really `Load` (and not  rather `Work`).

2022-04-20 17:19 UTC, ppebay commented on src/vt/elm/elm_stats.cc
> +    return getLoadMetric(phase);
It should be rather `getModeledLoad` @cz4rs

2022-04-20 17:36 UTC, PhilMiller commented on src/vt/elm/elm_stats.cc
> +    return getLoadMetric(phase);
... The values from elm_stats are raw timing data, not modeled load, I think. At this level, it should not even be referred to as LoadMetric.

2022-04-21 18:13 UTC, cz4rs commented on src/vt/vrt/collection/balance/model/raw_data.cc
> +  // TODO: consider subphases (?)
Question: should we consider subphases here? (as is done in `CommOverhead` Load Model)

2022-04-21 18:20 UTC, cz4rs commented on src/vt/vrt/collection/balance/model/load_model.h
> +  virtual TimeType getLoad(ElementIDStruct object, PhaseOffset when) = 0;
Going with `getModeledLoad` in the end, as discussed at LB meeting.

2022-04-21 18:21 UTC, cz4rs commented on src/vt/elm/elm_stats.cc
> +    return getLoadMetric(phase);
Makes sense. Reverting to `getLoad` here and keeping the `getModeledLoad` everywhere else, where it's related to Load Models.

2022-04-21 18:26 UTC, cz4rs commented on src/vt/vrt/collection/balance/model/raw_data.cc
> +  // TODO: consider subphases (?)
https://github.com/DARMA-tasking/vt/blob/3e362c4bc3545c0332d1a9208eb2cef49264d7b3/src/vt/vrt/collection/balance/model/comm_overhead.cc#L78-L84

(notice the old `todo` here as well)

2022-04-27 18:02 UTC, cz4rs commented on tests/unit/collection/test_lb.extended.cc
> +TEST_F(TestLoadBalancerOther, test_make_graph_symmetric) {
Seems like there is an issue with `makeGraphSymmetric` (running on 4 nodes here):
```
Testing lb TemperedWMin
Using lb_args ordering=Arbitrary rollback=false

before:
makeGraphSymmetric: comm_map.size=2
makeGraphSymmetric: from=(1,0,0,false), to=(5,1,1,false)
makeGraphSymmetric: from=(1,0,0,false), to=(9,2,2,false)

makeGraphSymmetric: comm_map.size=3
makeGraphSymmetric: from=(9,2,2,false), to=(1,0,0,false)
makeGraphSymmetric: from=(9,2,2,false), to=(5,1,1,false)
makeGraphSymmetric: from=(9,2,2,false), to=(d,3,3,false)

makeGraphSymmetric: comm_map.size=2
makeGraphSymmetric: from=(5,1,1,false), to=(1,0,0,false)
makeGraphSymmetric: from=(5,1,1,false), to=(d,3,3,false)

makeGraphSymmetric: comm_map.size=1
makeGraphSymmetric: from=(d,3,3,false), to=(5,1,1,false)

after:
test_make_graph_symmetric: comm_map.size=4
test_make_graph_symmetric: from=(5,1,1,false), to=(1,0,0,false)
test_make_graph_symmetric: from=(1,0,0,false), to=(5,1,1,false)
test_make_graph_symmetric: from=(9,2,2,false), to=(1,0,0,false)
test_make_graph_symmetric: from=(1,0,0,false), to=(9,2,2,false)

test_make_graph_symmetric: comm_map.size=5
test_make_graph_symmetric: from=(9,2,2,false), to=(5,1,1,false)
test_make_graph_symmetric: from=(1,0,0,false), to=(5,1,1,false)
test_make_graph_symmetric: from=(5,1,1,false), to=(1,0,0,false)
test_make_graph_symmetric: from=(d,3,3,false), to=(5,1,1,false)
test_make_graph_symmetric: from=(5,1,1,false), to=(d,3,3,false)

test_make_graph_symmetric: comm_map.size=4
test_make_graph_symmetric: from=(1,0,0,false), to=(9,2,2,false)
test_make_graph_symmetric: from=(9,2,2,false), to=(1,0,0,false)
test_make_graph_symmetric: from=(9,2,2,false), to=(5,1,1,false)
test_make_graph_symmetric: from=(9,2,2,false), to=(d,3,3,false)

test_make_graph_symmetric: comm_map.size=3
test_make_graph_symmetric: from=(9,2,2,false), to=(d,3,3,false)
test_make_graph_symmetric: from=(5,1,1,false), to=(d,3,3,false)
test_make_graph_symmetric: from=(d,3,3,false), to=(5,1,1,false)
```
I will investigate this further and improve the test to actually verify the "before" and "after".

2022-04-27 18:02 UTC, ppebay approved these changes

2022-04-27 18:25 UTC, cz4rs commented on tests/unit/collection/test_lb.extended.cc
> +  //   "test_make_graph_symmetric -> makeGraphSymmetric",
it would be better to prepare `comm_data` manually and run `makeGraphSymmetric` directly instead of it being called by a running load balancer

2022-04-29 17:30 UTC, cz4rs commented on src/vt/vrt/collection/balance/temperedlb/temperedlb.cc
> +            cur_objs_[obj] = getTotalWork(obj);
Done.

2022-05-27 17:59 UTC, nlslatt reviewed
Some questions occurred to me while reviewing this that I'd like for a group of us to discuss, the most important being where to compute modeled comm and modeled work.

2022-05-27 17:59 UTC, nlslatt commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +  explicit CommMsg(lb::BaseLB::ElementCommType in_comm) : comm_(in_comm) { }
Should the argument be a const ref?

2022-05-27 17:59 UTC, nlslatt commented on src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
> +    {balance::PhaseOffset::NEXT_PHASE, balance::PhaseOffset::WHOLE_PHASE}));
Can you please move the `));` to the following line to follow our style guidelines?

2022-05-27 17:59 UTC, nlslatt commented on src/vt/vrt/collection/balance/model/raw_data.cc
> +TimeType RawData::getModeledComm(ElementIDStruct object, PhaseOffset when) {
I'm not sure that the `RawData` model is the right place to compute and return modeled communication. Any thoughts, @PhilMiller?

2022-05-27 17:59 UTC, nlslatt commented on tests/unit/lb/test_temperedlb.nompi.cc
> +  orderUsingOverloadAndVerify(order, over_avg, soln);
I think this will test `TemperedLB` and not `TemperedWMin`. I don't see any way for `use_tempered_wmin` to be set to true when `orderAndVerify` is called.

2022-05-27 17:59 UTC, nlslatt commented on tests/unit/collection/test_lb.extended.cc
> +    );
I feel like the correctness checks here are a little weak. It would pass with two comms from this to the next or two from the previous to this, right?

Because it's only two different things you're expecting, you could set two booleans and make sure both conditions are met by some comm entry. It would also be good to check the number of bytes.

2022-05-27 17:59 UTC, nlslatt commented on tests/unit/collection/test_lb.extended.cc
> +void runTest(std::string const& lb_name, const int phases = num_phases) {
Is this additional argument ever used?

2022-05-27 17:59 UTC, nlslatt commented on src/vt/vrt/collection/balance/temperedwmin/temperedwmin.cc
> +}
Should this be implemented as a new load model instead of integrated into the load balancer? Load models can be composed, so you'd still be able to plug in whatever model you wanted for the loads.

Having the formula integrated into the LB makes it impossible for vt to compute post-LB statistics following the formula. What we dump to the LB statistics json file post-LB would be incorrect but I'm not sure if it would have any other immediate consequences. I think it might break the (not yet implemented) capability to run multiple load balancers and use the most effective result.

What do you think, @PhilMiller and @ppebay?

2022-05-27 17:59 UTC, nlslatt commented on src/vt/vrt/collection/balance/model/raw_data.cc
> +  return std::max(incoming, outgoing);
Why does only the max matter and not the sum?

2022-05-27 17:59 UTC, nlslatt commented on src/vt/vrt/collection/balance/lb_type.h
> +#include "vt/configs/features/features_defines.h"
Are you confident that nothing important is lost in this change of include?

2022-05-30 11:23 UTC, cz4rs commented on tests/unit/collection/test_lb.extended.cc
> +void runTest(std::string const& lb_name, const int phases = num_phases) {
Removed.

2022-05-31 12:22 UTC, cz4rs commented on scripts/post-commit
> +
Normally you would expect the hook to only trigger after `git commit ...`. This prevents it from running after every commit during rebase.

2022-05-31 13:18 UTC, cz4rs commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +  explicit CommMsg(lb::BaseLB::ElementCommType in_comm) : comm_(in_comm) { }
Done.

2022-05-31 13:18 UTC, cz4rs commented on src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
> +    {balance::PhaseOffset::NEXT_PHASE, balance::PhaseOffset::WHOLE_PHASE}));
Done.

2022-05-31 13:35 UTC, cz4rs commented on tests/unit/collection/test_lb.extended.cc
> +    );
Done.

2022-05-31 14:30 UTC, cz4rs commented on tests/unit/lb/test_temperedlb.nompi.cc
> +  orderUsingOverloadAndVerify(order, over_avg, soln);
Done (bcb1e846f151f167960cc16111ef6ec30171c16a).
I have picked `test...ordering_elmid` and `test...ordering_smallobjects_largest` somewhat randomly to provide some coverage. What I could also do is to type-parametrize all tests here and run them for both `TemperedLB` and `TemperedWMin`.

2022-05-31 23:09 UTC, nlslatt commented on scripts/post-commit
> +
To clarify, does this mean skip it completely during rebase or trigger it only once for a rebase, after the final commit?

2022-06-01 18:20 UTC, cz4rs commented on src/vt/vrt/collection/balance/temperedwmin/temperedwmin.cc
> +}
To be continued in  #1838. No clear design direction for this at the moment.

2022-06-01 18:55 UTC, cz4rs commented on scripts/post-commit
> +
Reverted, I'll resubmit that in a separate PR if needed.

2022-06-01 20:27 UTC, merged