#1701: Adding a 3D example program based on the 2D version.
DARMA-tasking/vt pull request #1719
Opened 2022-03-25 02:23 UTC by keitat

I am adding a new example program.  See #1701 .

2024-05-10 16:58 UTC, lifflander requested changes

2024-05-10 16:58 UTC, lifflander commented on examples/collection/jacobi3d_vt.cc
> +  void exchange(VecMsg *msg) {
Please change to use the new interface rather than sending a message.

```C++
void exchange(IndexType from_index, std::vector<double> const& val, size_t nx, size_t ny, size_t nz) {
```

2024-05-10 16:58 UTC, lifflander commented on examples/collection/jacobi3d_vt.cc
> +  void doIter(BlankMsg *msg) {
Remove `BlankMsg`

2024-05-21 13:24 UTC, thearusable commented on examples/collection/jacobi3d_vt.cc
> +  void doIter(BlankMsg *msg) {
Removed

2024-05-21 13:25 UTC, thearusable commented on examples/collection/jacobi3d_vt.cc
> +  void exchange(VecMsg *msg) {
Ok, Updated. Thanks for the code snippet 👍

2024-05-28 16:39 UTC, lifflander requested changes

2024-05-28 16:39 UTC, lifflander commented on examples/collection/jacobi3d_vt.cc
> +  struct BlankMsg : vt::CollectionMessage<LinearPb3DJacobi> { };
Can we remove these messages?

2024-05-31 12:01 UTC, thearusable commented on examples/collection/jacobi3d_vt.cc
> +  struct BlankMsg : vt::CollectionMessage<LinearPb3DJacobi> { };
Sure, removed.

2024-06-04 16:40 UTC, merged