1265 stats replay without collection
DARMA-tasking/vt pull request #1720
Opened 2022-03-25 18:30 UTC by nlslatt

This PR allows replaying LB data (workloads) read from json files. It does not correctly handle communications and thus will not work with comm-aware load models or load balancers. To handle communications correctly, a vt refactor where communications are treated analogously to load data by the `ProposedReassignment` load model and the `LBManager` would likely be the best approach.

Closes #1265

2023-10-17 20:26 UTC, nlslatt commented
This PR includes an executable `tools/workload_replay/simulate_replay` that can be used to replay an application run from stored json files but allowing new LB decisions. I will provide more details on how to use the tool later.

Due to the vt refactor that moved printing the phase summary (including LB statistics) out of the LB manager and into the phase manager, there are currently no phase summaries being printed from the replay tool (due to only simulating phases, not truly advancing through them). I'm looking into fixing that.

2023-10-18 21:06 UTC, nlslatt commented
I added code to print the phase summary. It requires modifying private members of the LB manager. I added accessors to do this, but we should consider a refactor.

2023-10-18 21:19 UTC, nlslatt commented
**Using the replay tool**

- First run the application as usual, dumping LB data files using the command-line option `--vt_lb_data`. For example:
```
mpirun -np 4 ./examples/collection/lb_iter 128 1 20 --vt_lb_data --vt_lb_data_dir="lbiter" --vt_lb_data_file="lbdata.%p.json.br" --vt_lb --vt_lb_name=HierarchicalLB --vt_lb_interval=5
```
where `20` is the number of phases to run.
- Then, replay from the LB data files using the replay tool with the command-line option `--vt_lb_data_in`. For example:
```
mpirun -np 4 ./tools/workload_replay/simulate_replay 0 20 --vt_lb_data_in --vt_lb_data_dir_in="lbiter" --vt_lb_data_file_in="lbdata.%p.json.br" --vt_lb --vt_lb_name="TemperedLB" --vt_lb_interval=2
```
where `0` is the initial phase to run and `20` is the number of phases to run. It is also possible to start replay well into the run, for example:
```
mpirun -np 4 ./tools/workload_replay/simulate_replay 12 8 --vt_lb_data_in --vt_lb_data_dir_in="lbiter" --vt_lb_data_file_in="lbdata.%p.json.br" --vt_lb --vt_lb_name="TemperedLB" --vt_lb_interval=2
```
which runs 8 phases, starting with phase 12.

2023-11-07 20:10 UTC, lifflander requested changes

2023-11-07 20:10 UTC, lifflander commented on src/vt/vrt/collection/balance/workload_replay.cc
> +    theCollective()->barrier();
Can we remove this barrier? I don't think it's needed

2023-11-07 20:15 UTC, nlslatt commented on CMakeLists.txt
> +#
Based on my bad experiences with Trilinos options, I think it is case sensitive. If I change this, I should change the existing `VT_BUILD_TESTS` too. Are we ready to make that breaking change?

2023-11-07 20:16 UTC, nlslatt commented on tools/CMakeLists.txt
> +### @todo Add command-line arguments for testing
Are you okay with not testing the tool itself? We have unit tests of the base functionality but not of the driver.

2023-11-07 20:18 UTC, nlslatt commented on CMakeLists.txt
> +#
And should I move `VT_BUILD_TESTS` to `cmake/configure_options.cmake` too?

2023-11-07 20:24 UTC, lifflander commented on CMakeLists.txt
> +#
I'm think we shouldn't change `VT_BUILD_TESTS` and `VT_BUILD_EXAMPLES` right now, but should create an issue for that. Those variables were created a very long time ago, before we adopted the lower-case convention. Really I think we should have all the options in configure_options.cmake if possible. I see there are still a handful in top-level CMakeLists. If you want to move them, that would be great unless there is some reason they can't be moved.

2023-11-07 20:25 UTC, lifflander commented on tools/CMakeLists.txt
> +### @todo Add command-line arguments for testing
If we run the tool itself (beyond the tests you wrote), we need input files and other configuration, right? I think for now the tests you have are sufficient to merge this.

2023-11-07 21:57 UTC, nlslatt commented on tools/CMakeLists.txt
> +### @todo Add command-line arguments for testing
Removed.

2023-11-07 21:57 UTC, nlslatt commented on CMakeLists.txt
> +#
I'm changing it to lowercase and leaving the move to the other cmake file as part of a separate issue.

2023-11-07 21:58 UTC, nlslatt commented on src/vt/vrt/collection/balance/workload_replay.cc
> +    theCollective()->barrier();
Removed.

2023-11-09 18:45 UTC, nlslatt commented on CMakeLists.txt
> +#
The new issue is #2214.

2023-11-09 18:55 UTC, lifflander approved these changes

2023-11-09 18:55 UTC, lifflander commented on src/vt/vrt/collection/balance/workload_replay.cc
> +  for (auto &phase_data : sd->node_data_) {
A minor improvement would be to conditionalize these loops on `if (theConfig()->vt_debug_replay) {`

2023-11-09 22:32 UTC, merged