1723 Include user-defined fields in json LB data files
DARMA-tasking/vt pull request #1728
Opened 2022-04-01 18:10 UTC by nlslatt

This PR adds the ability to dump items stored in collection elements as user-defined data in LB data json files. I also added a commit that removes some stale lines of code from an existing unit test.

Closes #1723

2022-04-05 18:13 UTC, lifflander requested changes

2022-04-05 18:13 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.h
> +#include <nlohmann/json.hpp>
Can we avoid this include here? I see you are using `nlohmann::json` later in the file, could we make that a unique pointer or something? I've so far avoided all inclusions of `json.hpp` in any VT header files due to the burden.

2022-04-05 18:13 UTC, lifflander commented
Overall, looks great!

2022-04-05 22:04 UTC, nlslatt commented on src/vt/vrt/collection/balance/stats_data.h
> +#include <nlohmann/json.hpp>
I'm not sure how a unique pointer is supposed to help. I tried changing back the include and changing the data structure to be
```
  std::unordered_map<PhaseType, std::unordered_map<
    ElementIDStruct, std::unique_ptr<nlohmann::json>
  >> user_defined_json_;
```
but it fails to compile even if I comment out all code that actually uses `user_defined_json_`.

2022-04-06 16:18 UTC, lifflander commented on src/vt/vrt/collection/balance/stats_data.h
> +#include <nlohmann/json.hpp>
Oh, maybe we need to move the serializer?

2022-04-06 17:03 UTC, nlslatt commented on src/vt/vrt/collection/balance/stats_data.h
> +#include <nlohmann/json.hpp>
I even had the line in the serializer commented out.

2022-04-06 17:50 UTC, nlslatt commented on src/vt/vrt/collection/balance/stats_data.h
> +#include <nlohmann/json.hpp>
I got it to compile with `shared_ptr`.

2022-04-06 22:12 UTC, lifflander approved these changes
Looks good to me!

2022-04-12 17:39 UTC, lifflander approved these changes
Looks good to me!

2022-05-02 18:58 UTC, merged