1716 rename lb stats files to data files
DARMA-tasking/vt pull request #1731
Opened 2022-04-05 15:52 UTC by stmcgovern

Fixes #1716. No changes to file names or command line flags.

2022-04-05 17:49 UTC, nlslatt commented
@stmcgovern The failed test writes a file and then reads it. Just looking over the code, it seems like the file write may not have been committed when the read started (despite the barrier). I remember @lifflander mentioning having bad experiences with writing to files in CI, so I'm re-running the macosx test to see if it passes this time.

2022-04-12 17:07 UTC, jstrzebonski commented on src/vt/configs/arguments/args.cc
> +  auto xy = app.add_option("--vt_lb_stats_file_in", appConfig.vt_lb_data_file_in, lb_data_file_in,lbs);
Do we want to add additional options matching the new terminology (apart from leaving old ones for backward compatibility with scripts, as mentioned in the issue description)?

2022-04-13 17:38 UTC, nlslatt commented on docs/md/node-stats.md
>  with statistics for each object (computation time and communication load).
This should say data, not statistics. Also, the filename still contains `stats`.

2022-04-13 17:44 UTC, nlslatt commented on src/vt/vrt/collection/balance/node_stats.cc
>      "NodeStats::createStatsFile: file={}\n", file_name
The class name, filename, and other names involving `Stats` are no longer appropriate.

2022-04-13 17:45 UTC, nlslatt commented on src/vt/vrt/collection/balance/stats_restart_reader.cc
>  void StatsRestartReader::startup() {
The class name and filename are no longer appropriate.

2022-04-13 18:13 UTC, stmcgovern commented
> This is a good start, but the changes are not extensive enough

@nlslatt Thanks for clarifying. I took a conservative approach, and I will now expand based on your comments.

2022-04-21 17:58 UTC, nlslatt requested changes
I haven't reviewed yet for anything that got changed in error, but I wanted to start with the small number of things that got missed. There are two review comments plus what's below.

I think `\ref proc-stats` in `docs/md/collection.md` should be pointing to `node-lb-data` instead.

Also, we need to rename `StatsMapLB` (and the associated files) to something more appropriate. I've started a discussion here: https://darmatalk.slack.com/archives/C01SEK9R3M1/p1650563842991169

2022-04-21 17:58 UTC, nlslatt commented on src/vt/runnable/make_runnable.h
> +   * \brief Add LB data for instrumentation directly with element ID and stats
The second instance of `stats` here also refers to `LB data`.

2022-04-21 17:58 UTC, nlslatt commented on src/vt/runnable/make_runnable.h
> +    impl_->template addContext<ctx::LBData>(stats, elm_id);
`stats` and `StatsT` here both refer to LB data and so should be renamed to something more appropriate.

2022-04-21 23:50 UTC, stmcgovern commented on src/vt/runnable/make_runnable.h
> +    impl_->template addContext<ctx::LBData>(stats, elm_id);
Thank you. This file was a little unclear to me.

2022-04-28 17:32 UTC, nlslatt reviewed
Amost there!
`baselb.cc` line 97: `load stats size` --> `load data size`.
`temperedlb.cc` line 229: `from vt stats` --> `from lb data`.

2022-04-28 17:32 UTC, nlslatt commented on src/vt/vrt/collection/balance/lb_type.h
> +  , OfflineLB       = 5
Please maintain alignment.

2022-04-28 18:54 UTC, nlslatt commented
> Amost there! `baselb.cc` line 97: `load stats size` --> `load data size`. `temperedlb.cc` line 229: `from vt stats` --> `from lb data`.

I made these changes myself so we can get this merged before we get more merge conflicts.

2022-04-28 19:28 UTC, nlslatt approved these changes

2022-04-28 21:25 UTC, merged