#1747: change const pointer to pointer to const IndexT
DARMA-tasking/vt pull request #1750
Opened 2022-04-27 18:14 UTC by stmcgovern

Fixes #1747.

2022-04-27 19:23 UTC, PhilMiller approved these changes

2022-04-27 19:43 UTC, lifflander commented on src/vt/vrt/collection/holders/collection_context_holder.h
> +  static void set(const IndexT* set_idx, VirtualProxyType const& set_proxy) {
The style guidelines prefer const on the other side of the pointer:
`IndexT const* set_idx`

2022-04-27 19:43 UTC, lifflander commented on src/vt/vrt/collection/holders/collection_context_holder.h
> +  static const IndexT* index() {
```suggestion
  static IndexT const* index() {
```

2022-04-27 19:44 UTC, lifflander commented on src/vt/vrt/collection/holders/collection_context_holder.h
> +  static void set(const IndexT* set_idx, VirtualProxyType const& set_proxy) {
```suggestion
  static void set(IndexT const* set_idx, VirtualProxyType const& set_proxy) {
```

2022-04-27 19:45 UTC, lifflander commented on src/vt/vrt/collection/holders/collection_context_holder.h
> +  static void set(const IndexT* set_idx, VirtualProxyType const& set_proxy) {
This is because types in C/C++ are read from right-to-left. So this statement `T const* const x;` is read like this: "X is a const pointer to a const T"

2022-04-27 19:48 UTC, stmcgovern commented on src/vt/vrt/collection/holders/collection_context_holder.h
> +  static void set(const IndexT* set_idx, VirtualProxyType const& set_proxy) {
OK, I will change to use “East const” style.

2022-04-27 19:49 UTC, lifflander requested changes
Pl. change order of const.

2022-04-28 00:09 UTC, lifflander approved these changes
Looks good!

2022-04-28 00:09 UTC, lifflander commented
Rebase and this should be good to merge!

2022-04-28 00:40 UTC, stmcgovern commented
> Rebase and this should be good to merge!

All set.

2022-04-28 02:31 UTC, merged