1715 allow labels on object collections and groups
DARMA-tasking/vt pull request #1754
Opened 2022-05-02 20:21 UTC by jstrzebonski

Fixes #1715

2022-05-02 21:50 UTC, lifflander commented on src/vt/vrt/collection/param/construct_params.h
> +  const std::string& label
I think we should make this optional

2022-05-06 18:29 UTC, jstrzebonski commented on src/vt/vrt/collection/param/construct_params.h
> +  const std::string& label
Done.

2022-05-06 18:38 UTC, jstrzebonski commented on src/vt/vrt/collection/manager.h
> +    std::string const& file_base
I think here label should also be optional.

2022-05-06 18:38 UTC, jstrzebonski commented on src/vt/vrt/collection/manager.h
> +    DistribConstructFn<ColT> cons_fn
I think here label should also be optional.

2022-05-11 22:43 UTC, lifflander requested changes

2022-05-11 22:43 UTC, lifflander commented on src/vt/objgroup/manager.cc
> +  labels_.emplace(proxy, label);
I think we are missing the deletion of the label.

2022-05-11 22:43 UTC, lifflander commented on src/vt/vrt/collection/manager.h
> +  construct(
Since we are going to be deprecating these calls, we probably don't really need to add them here. But.. it's fine as long as we don't also break the interface.

2022-05-11 22:43 UTC, lifflander commented on src/vt/vrt/collection/manager.h
> +  construct(
This looks like a breaking change to me.

2022-05-11 22:43 UTC, lifflander commented on src/vt/vrt/collection/manager.h
> +    typename ColT::IndexType range, std::string const& file_base,
Instead of providing the label here, shouldn't we just write/read it from the file? I think it should be included in the checkpoint and then restored.

2022-05-11 22:43 UTC, lifflander commented on src/vt/vrt/collection/manager.h
> +  template <typename ColT>
We should probably make this call typeless `VirtualProxyType` since it doesn't rely on the type at all.

2022-05-11 22:43 UTC, lifflander commented on src/vt/vrt/collection/manager.h
> +  std::unordered_map<VirtualProxyType, std::string> labels_;
This should be stored in the `TypelessHolder` or `BaseHolder`

2022-05-11 22:43 UTC, lifflander commented on src/vt/vrt/collection/manager.impl.h
>      theCollection()->constructGroup<ColT>(proxy);
Insertion can happen here into the typeless holder.

2022-05-16 12:12 UTC, jstrzebonski commented on src/vt/objgroup/manager.cc
> +  labels_.emplace(proxy, label);
Done.

2022-05-16 12:17 UTC, jstrzebonski commented on src/vt/vrt/collection/manager.h
> +  construct(
Done.

2022-05-16 12:17 UTC, jstrzebonski commented on src/vt/vrt/collection/manager.h
> +  construct(
Done.

2022-05-16 12:22 UTC, jstrzebonski commented on src/vt/vrt/collection/manager.h
> +  template <typename ColT>
Done.

2022-05-16 12:22 UTC, jstrzebonski commented on src/vt/vrt/collection/manager.h
> +    typename ColT::IndexType range, std::string const& file_base,
Done.

2022-05-16 12:22 UTC, jstrzebonski commented on src/vt/vrt/collection/manager.h
> +  std::unordered_map<VirtualProxyType, std::string> labels_;
Done.

2022-05-16 12:22 UTC, jstrzebonski commented on src/vt/vrt/collection/manager.impl.h
>      theCollection()->constructGroup<ColT>(proxy);
Done.

2022-05-18 16:59 UTC, nlslatt reviewed
Most of it looks great, but there might be one problem.

2022-05-19 10:46 UTC, jstrzebonski commented on tests/perf/common/test_harness.cc
> +    "PerfTestHarness::SyncResults()", this
This calls that overload:
```cpp
template <typename ObjT, typename... Args>
ProxyType<ObjT> makeCollective(std::string const& label, Args&&... args);
```

I think that maybe, with some funny usage of SFINAE, it could be possible to convert it to `ProxyType<ObjT> makeCollective(Args&&... args);`, and try to either extract the last parameter if it's a `std::string label`, or assume that default label (`""`) should be used. The problem is if `args` contain `std::string` for `ObjT` creation, how would one know if that's the case?

That's why this overload doesn't have a label as the last and optional parameter.

We could maybe add a tag to have a clear difference between `std::string` used as an ObjT's constructor parameter vs objgroup label, but IMHO it would burden interfaces too much.

Maybe others have a different opinion on this?

2022-05-20 17:42 UTC, nlslatt commented on tests/perf/common/test_harness.cc
> +    "PerfTestHarness::SyncResults()", this
I think it's probably okay. I hadn't noticed that the template parameter type and pointer type were different, so I had been looking at the overload that accepts a raw pointer.

2022-05-20 17:47 UTC, nlslatt approved these changes
Looks good to me.

2022-05-20 18:09 UTC, PhilMiller commented on tests/unit/collection/test_checkpoint.extended.cc
> +  std::string const expected_label{"test_checkpoint_1"};
I just noticed, you're a fan of "east `const`". I'm ambivalent about which way to go, but it definitely reads weird to me in this form.

That said, please don't make another push to change this.

2022-05-20 18:16 UTC, PhilMiller commented on src/vt/messaging/collection_chain_set.impl.h
> +    this, "CollectionChainSet::CollectionChainSet()"
Minor nitpick, I don'think the label should describe the object, not the particular constructor, where it's not material to the resulting instance. This appears in a few cases.

2022-05-20 18:17 UTC, PhilMiller commented on src/vt/messaging/collection_chain_set.impl.h
> +    this, "CollectionChainSet::CollectionChainSet()"
Various managers, maps, etc.

2022-05-20 18:17 UTC, PhilMiller commented on src/vt/messaging/collection_chain_set.impl.h
> +    this, "CollectionChainSet::CollectionChainSet()"
In the tests, I largely don't care. Just in the main runtime source code.

2022-05-20 18:17 UTC, PhilMiller commented
I'm fine with merging as is, but if we're open to a small revision, see my remark about the chosen labels for runtime class instances.

2022-05-24 19:09 UTC, nlslatt commented on tests/unit/collection/test_mapping.cc
> +    madeProxy.get()->proxy = proxy;
```suggestion
    madeProxy.get()->proxy = madeProxy;
```

2022-05-26 17:51 UTC, nlslatt commented on src/vt/messaging/collection_chain_set.impl.h
> +    this, "CollectionChainSet::CollectionChainSet()"
I agree since we are labeling the object and now how it came into existence.

2022-05-31 16:47 UTC, jstrzebonski commented on src/vt/messaging/collection_chain_set.impl.h
> +    this, "CollectionChainSet::CollectionChainSet()"
Done.

2022-05-31 16:49 UTC, jstrzebonski commented on src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
> +  auto proxy = theObjGroup()->makeCollective<LB>(lb_name);
Or maybe let's add a function `std::string getName() const` to load balancers, and call it here to get a name instead of passing it as an argument?

2022-05-31 20:49 UTC, nlslatt commented on src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
> +  auto proxy = theObjGroup()->makeCollective<LB>(lb_name);
There's a data structure in `src/vt/vrt/collection/balance/lb_type.cc` that has the names of all the LBs in it.

2022-06-01 05:53 UTC, jstrzebonski commented on src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
> +  auto proxy = theObjGroup()->makeCollective<LB>(lb_name);
Done.

2022-06-01 19:35 UTC, nlslatt approved these changes
Looks good!

2022-06-01 20:29 UTC, nlslatt commented
Unfortunately, there are now merge conflicts. This can be merged once the conflicts are resolved.

2022-06-02 17:01 UTC, merged