#1786: condition link flag on library's presence
DARMA-tasking/vt pull request #1787
Opened 2022-05-09 15:06 UTC by stmcgovern

Fixes #1786. Follow-up to issue #1691.

2022-05-09 18:35 UTC, cz4rs requested changes
To make sure that this is working as intended, we could have one of the builds running without `libunwind`. Maybe Alpine? Removing this line should be enough:
https://github.com/DARMA-tasking/vt/blob/00b1297c4aeacc36bd86b5ff80d0ee1d6f1f5307/ci/docker/alpine-cpp.dockerfile#L23

Looks good otherwise :+1:

2022-05-09 22:27 UTC, stmcgovern commented
Thanks @cz4rs. Done.

2022-05-09 22:48 UTC, lifflander approved these changes
Looks good to me!

2022-05-10 12:30 UTC, cz4rs approved these changes

2022-05-10 14:58 UTC, merged