1902: upgrade `CLI11` to `v2.2.0`
DARMA-tasking/vt pull request #1904
Opened 2022-08-09 11:24 UTC by cz4rs

Upgrade `CLI11` to the latest release.
Note: this keeps the added `namespace vt` in the header.

fixes #1902

2022-08-09 11:27 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  auto v  = app.add_option("--vt_lb_name", appConfig.vt_lb_name, lb_name)->capture_default_str();
New feature reduces the code duplication: default value will be read from `AppConfig::vt_lb_name`.

2022-08-09 14:41 UTC, PhilMiller reviewed
This all looks very nice. 

Could you confirm that all of the defaults actually matched?

2022-08-09 17:15 UTC, nmm0 approved these changes
Looks good to me, also fixes C++17 compile issue

2022-08-09 17:17 UTC, PhilMiller requested changes
Please work around the Intel CI failure before merging, so that we don't just see that failure on every PR going forward

2022-08-09 17:18 UTC, PhilMiller commented
```
FAILED: src/CMakeFiles/vt.dir/Unity/unity_0_cxx.cxx.o 
/usr/bin/ccache /usr/local/bin/mpicxx -DJSON_USE_IMPLICIT_CONVERSIONS=1 -DVT_NO_COLOR_ENABLED -I/vt/lib/CLI -I/build/vt/release -I/vt/src -I/vt/lib/json/include -I/vt/lib/brotli/c/include -I/vt/lib/libfort/lib -isystem /vt/lib/fmt/include -isystem /vt/lib/EngFormat-Cpp/include -isystem /build/checkpoint/install/include -isystem /build/detector/install/include -O3 -DNDEBUG -Wall -pedantic -Wshadow -Wno-unknown-pragmas -Wsign-compare -Werror -fPIC -std=c++14 -MD -MT src/CMakeFiles/vt.dir/Unity/unity_0_cxx.cxx.o -MF src/CMakeFiles/vt.dir/Unity/unity_0_cxx.cxx.o.d -o src/CMakeFiles/vt.dir/Unity/unity_0_cxx.cxx.o -c /build/vt/src/CMakeFiles/vt.dir/Unity/unity_0_cxx.cxx
In file included from /vt/src/vt/configs/arguments/args.cc(54),
                 from /build/vt/src/CMakeFiles/vt.dir/Unity/unity_0_cxx.cxx(9):
/vt/lib/CLI/CLI/CLI11.hpp(8143): error #3280: declaration hides variable "optarg" (declared at line 36 of "/usr/include/x86_64-linux-gnu/bits/getopt_core.h")
                      std::string optarg = args.back();
                                  ^
```

2022-08-10 17:37 UTC, cz4rs commented on lib/CLI/CLI/CLI11.hpp
> +                    std::string cli_optarg = args.back();
I think that's better than adding `Wno-shadow` for icpc.
Btw this is already fixed at `main` branch of CLI11.

2022-08-10 17:39 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  auto mm = app.add_option("--vt_memory_reporters",          appConfig.vt_memory_reporters, mem_desc)->capture_default_str();
`true` here meant that the default value was already captured.

2022-08-10 17:42 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  auto m = app.add_option("--vt_stack_mod",     appConfig.vt_stack_mod,       mod)->capture_default_str();
Difference:
https://github.com/DARMA-tasking/vt/blob/e8ca3b556b5cb98d82b92c31b75cd084ddc799b4/src/vt/configs/arguments/app_config.h#L117

2022-08-10 17:43 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  auto q  = app.add_option("--vt_trace_mod",             appConfig.vt_trace_mod,               tmod)->capture_default_str();
Difference:
https://github.com/DARMA-tasking/vt/blob/e8ca3b556b5cb98d82b92c31b75cd084ddc799b4/src/vt/configs/arguments/app_config.h#L129

2022-08-10 17:45 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  auto xx = app.add_option("--vt_lb_data_dir_in", appConfig.vt_lb_data_dir_in, lb_data_dir_in)->capture_default_str();
https://github.com/DARMA-tasking/vt/blob/e8ca3b556b5cb98d82b92c31b75cd084ddc799b4/src/vt/configs/arguments/app_config.h#L149

2022-08-10 17:46 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  auto xy = app.add_option("--vt_lb_data_file_in", appConfig.vt_lb_data_file_in, lb_data_file_in)->capture_default_str();
https://github.com/DARMA-tasking/vt/blob/e8ca3b556b5cb98d82b92c31b75cd084ddc799b4/src/vt/configs/arguments/app_config.h#L151

2022-08-10 17:49 UTC, cz4rs commented
> This all looks very nice.
> 
> Could you confirm that all of the defaults actually matched?

I have double-checked and noted the differences in the comments.

2022-08-11 15:18 UTC, cz4rs commented
Rebased on top of `develop`.
All the differences regarding default values should only make the `--vt_help` output more accurate (the ones in `args.cc` were out of sync).

2022-08-11 15:39 UTC, PhilMiller approved these changes

2022-08-11 15:43 UTC, merged