#1908: Disable preConfig
DARMA-tasking/vt pull request #1924
Opened 2022-08-23 19:12 UTC by stmcgovern

Closes #1908.

2022-08-23 19:52 UTC, stmcgovern commented
From grouped PR, see:
https://github.com/DARMA-tasking/vt/pull/1916#discussion_r952919356

2022-08-24 00:08 UTC, PhilMiller requested changes
Could you pick up my suggestion from the earlier combined PR?

2022-08-24 00:40 UTC, PhilMiller commented on src/vt/configs/debug/debug_print.h
> +  do { if (false) vt_force_use(__VA_ARGS__); } while (false);
The point of using do-while in a macro is that it forces the caller to treat it like a full statement, with a following semicolon. That only works if the macro definition leaves it off

2022-08-24 16:15 UTC, stmcgovern commented on src/vt/configs/debug/debug_print.h
> +  do { if (false) vt_force_use(__VA_ARGS__); } while (false);
Yes - fixed.

2022-08-24 16:33 UTC, PhilMiller approved these changes

2022-08-30 18:59 UTC, merged