1933: Add spec file for LB
DARMA-tasking/vt pull request #1982
Opened 2022-09-27 16:19 UTC by JacobDomagala

Fixes #1933

2022-10-04 16:07 UTC, nlslatt commented
@JacobDomagala You'll need to re-push now that you've marked this as ready in order for the full PR testing to run.

2022-10-05 16:56 UTC, nlslatt approved these changes
Looks good to me

2022-10-05 17:15 UTC, JacobDomagala commented on src/vt/configs/arguments/args.cc
> +  auto lbspecfile = app.add_option("--vt_lb_spec_file", appConfig.vt_lb_spec_file,           lb_spec_file)->capture_default_str();
Trace spec file was also missing this check, so I added it aswell

2022-10-05 17:41 UTC, nmm0 requested changes
Can you add documentation for the format and its usage? I think it is also important in the documentation to highlight how this is different from the "LB Specification File" (`--vt_lb_file_name`)

2022-10-05 17:41 UTC, nmm0 commented on src/vt/configs/arguments/args.cc
> +  auto lbspec = app.add_flag("--vt_lb_spec",            appConfig.vt_lb_spec,                lb_spec);
This is slightly confusing, because the [documentation(https://darma-tasking.github.io/docs/html/lb-manager.html#lb-specification-file) refers to a "LB specification file" (the cli arg is `--vt_lb_file_name`) which is used to control what LB is used where. Maybe this should be `--vt_lb_trace_spec`?

2022-10-05 17:53 UTC, nmm0 commented on src/vt/configs/arguments/args.cc
> +  auto lbspec = app.add_flag("--vt_lb_spec",            appConfig.vt_lb_spec,                lb_spec);
I brought this up to @lifflander and @nlslatt that we should change "LB specification file" in the documentation to "LB Config File". We can do that in another PR though https://github.com/DARMA-tasking/vt/issues/1987

2022-10-07 21:41 UTC, JacobDomagala commented on src/vt/configs/arguments/args.cc
> +  auto lbspec = app.add_flag("--vt_lb_spec",            appConfig.vt_lb_spec,                lb_spec);
Created https://github.com/DARMA-tasking/vt/pull/1989

2022-10-11 17:17 UTC, nmm0 approved these changes
Looks good to me!

2022-10-12 17:42 UTC, merged