1938 remove unneeded calls to mpi wtime in trace and lb
DARMA-tasking/vt pull request #1998
Opened 2022-10-18 16:40 UTC by stmcgovern

Closes #1938.
~~Pass the current time from the scheduler to LB and Trace contexts.~~ 
This has been modified to allow the scheduler to hold a `current_sched_time_` and then the appropriate runnable contexts (here LB and Trace) can query their start time from the scheduler. This change was primarily the result of not wanting to force all runnable contexts to take a time (even in contexts where that is inappropriate). Still targets the issue by reducing calls to MPI_Wtime (although increased dereferencing of the `theSched()`)

2022-10-25 01:04 UTC, PhilMiller commented on src/vt/event/event.h
> +  void testEventsTrigger(int const& num_events = num_check_actions, TimeType current_time=0.0);
I'm a bit uncomfortable with an internal interface like this having a default argument. Are there call sites that are being left unmodified, for which the default value would be is sensible to pass?

2022-10-25 01:07 UTC, PhilMiller commented on src/vt/runnable/runnable.cc
> +void RunnableNew::begin(TimeType current_time) {
Not relevant to this PR, but I realize that we should probably not have methods named `begin/end` that are unrelated to getting the relevant iterators of a container-like class. Perhaps we should consider renaming them to something like `start/finish`

2022-10-25 01:08 UTC, PhilMiller commented on src/vt/runnable/runnable.h
> +  void begin(TimeType current_time = 0.0);
Same comment about default values

2022-10-25 01:14 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +  start_time_ = current_time;
This assignment makes sense, but I don't see why it's being passed down the lb stack any further. There are no uses of it, and the strategies can all access the member assigned here anyway.

2022-10-25 01:17 UTC, PhilMiller commented on src/vt/vrt/collection/manager.cc
> +    auto  current_time = thePhase()->getStartTime();
Is the beginning of the phase the right time to be passing in as the start of the LB? Is this getting called just after the phase manager ticks forward? Since it's in an End hook, isn't that not the case?

2022-10-25 01:26 UTC, PhilMiller commented
I would approve the first 3 commits of this PR as resolving 1938 (modulo my comments about default parameters). The latter two commits seem to be less motivated, and less clearly correct.

2022-10-25 16:22 UTC, stmcgovern commented
Thanks for your comments @PhilMiller. I'll drop the last 2 commits and see about the default arguments.

2022-11-29 03:04 UTC, lifflander submitted a review, later dismissed
Looks good!

2022-11-29 05:14 UTC, PhilMiller requested changes
Frankly, I was much happier with the approach of just passing a time down the call stack.

This PR now adds a bunch of calls to `timing::getCurrentTime`, though I haven't checked whether they're in specifically cold paths.

This change in approach may have been discussed, but that discussion is supposed to be memorialized in comments here. I'll note that the PR description no longer quite matches the code.

Let's talk about this in the meeting this week.

2022-11-29 18:18 UTC, PhilMiller commented on src/vt/scheduler/scheduler.cc
> +      runProgress(msg_only, current_sched_time_);
This may not be worth changing, but since `runProgress` is a sibling member, it doesn't need to take `current_sched_time_` as an argument, since it can access it directly.

2022-11-29 20:06 UTC, stmcgovern commented
> Frankly, I was much happier with the approach of just passing a time down the call stack.
> 
> This PR now adds a bunch of calls to `timing::getCurrentTime`, though I haven't checked whether they're in specifically cold paths.
> 
> This change in approach may have been discussed, but that discussion is supposed to be memorialized in comments here. I'll note that the PR description no longer quite matches the code.
> 
> Let's talk about this in the meeting this week.

Thanks @PhilMiller. Yes, the idea was to just pass time down the call stack. After removing the default arguments (per your first review), then a time argument needed to be passed through to any runnable (`void RunnableNew::run()`. Aside from complicating the `RunnableNew` interface, @lifflander remarked that not all runnables need a time. Then the change of tactic to have the scheduler store a time and allow the appropriate runnable contexts (in particular LB and trace) to ask for a start time was adopted. 

`theTrace()->beginProcessing` called `timing::getCurrentTime` by default. Removing this implicit use required getting the current time explicitly at certain call sites. 

I'll update the PR description to reflect these changes.

2022-11-29 21:51 UTC, PhilMiller commented on src/vt/runnable/invoke.h
> +  return theTrace()->beginProcessing(trace_id, 0, trace_event, from_node, timing::getCurrentTime());
This may actually illustrate a case for why I like the 'pass the time as an argument to contexts' approach better - if we want to add LB attribution for methods called through `invoke`, we would want to share this timer call for the start time, rather than have it reference the scheduler's recorded time, or need another new interface for the divergent case.

2023-01-11 22:54 UTC, stmcgovern commented
Status Update: PR uses a recent time held by the scheduler which is passed down to runnables that need a time. Currently only LB context uses this (Trace is TODO). Consider how to test for basic correctness confirmation.

2023-01-31 18:52 UTC, PhilMiller commented on src/vt/parameterization/parameterization.h
> +      theTrace()->beginProcessing(ep, msg_size, event, from_node, timing::getCurrentTime());
@lifflander Should we be create a `Runnable` here?

2023-01-31 18:56 UTC, PhilMiller commented on src/vt/scheduler/scheduler.cc
> +
Stray new line.
```suggestion
```

2023-02-07 23:23 UTC, PhilMiller commented on src/vt/scheduler/base_unit.cc
> +    theSched()->setRecentTimeToStale();
Should this be outside the `if / else if`, or duplicated in both arms? Why shouldn't the time be updated after we've run stuff in a thread?

2023-02-07 23:24 UTC, PhilMiller commented on src/vt/parameterization/parameterization.h
> +      theTrace()->beginProcessing(ep, msg_size, event, from_node, timing::getCurrentTime());
Code's going away, so we don't care.

2023-02-08 01:09 UTC, PhilMiller commented
I think I'm generally ok with this, and just need to see the couple comments addressed.

This does need to be run through the same fine-grain overhead benchmarks we used to identify time calls as a concern to begin with. I'd like to be confident that added calls to `theSched()` aren't losing us whatever ground we're gaining, or even a large fraction of it. If they are, then I'd push for accepting that every context is going to take a time argument, useful or not, and shifting the logic for when to check the clock and what time to pass down the stack more thoroughly into the scheduler.

2023-02-09 17:24 UTC, stmcgovern commented on src/vt/scheduler/scheduler.cc
> +
fixed

2023-02-09 17:32 UTC, stmcgovern commented on src/vt/scheduler/base_unit.cc
> +    theSched()->setRecentTimeToStale();
Yeah, it's in the run function (runnable.cc line 183). Should we just pull it out to here (outside the if/else)?

2023-02-14 18:50 UTC, PhilMiller commented
Some runs of the microbenchmark were getting ~30% reduction in time, directly attributable to reduced time spent in `PMPI_Wtime`. So, I think we're good on achieving the goal here.

2023-02-14 23:23 UTC, lifflander approved these changes

2023-02-14 23:57 UTC, stmcgovern commented on src/vt/scheduler/base_unit.cc
> +    theSched()->setRecentTimeToStale();
Left as is, since the runnable branch will also need to get a finish time.

2023-02-15 00:00 UTC, stmcgovern commented
Improvements to the tests will be pursued in VT #2017

2023-02-15 18:28 UTC, merged