2037 - Remove workers from vt
DARMA-tasking/vt pull request #2058
Opened 2023-01-02 13:34 UTC by thearusable

Closes #2037

2023-01-03 18:11 UTC, lifflander commented on src/vt/pool/header/pool_header.cc
> +  view.layout->prealloc.alloc_worker = worker_id_comm_thread;
Can you remove this field from the header?

2023-01-03 18:12 UTC, lifflander commented on src/vt/pool/pool.cc
>    auto const& alloc_worker = HeaderManagerType::getHeaderWorker(buf_char);
This can be removed

2023-01-03 18:13 UTC, lifflander commented on .github/workflows/macosx-clang-mpich.yml
>        VT_USE_OPENMP: 0
This can be removed also.

2023-01-03 18:17 UTC, lifflander commented
There should also be some removals from documentation.

2023-01-05 14:31 UTC, thearusable commented
@lifflander Should I also remove the `fcontext`?

2023-01-05 19:51 UTC, PhilMiller requested changes
Definitely don't remove fcontext. We're using that for real application work, and actively developing and improving it

2023-01-06 15:04 UTC, thearusable commented on src/vt/pool/header/pool_header.cc
> +  view.layout->prealloc.alloc_worker = worker_id_comm_thread;
Sure, removed

2023-01-06 15:04 UTC, thearusable commented on src/vt/pool/pool.cc
>    auto const& alloc_worker = HeaderManagerType::getHeaderWorker(buf_char);
Removed

2023-01-09 21:02 UTC, cz4rs commented
```
The following tests FAILED:
	395 - vt:TestPreconfig.test_vt_assert_no_mpi (SEGFAULT)
```
I think this might be an independent failure caused by a newer `intel/oneapi` image available. I'll try to reproduce this on `develop` and create a separate issue if needed.

2023-01-09 21:10 UTC, cz4rs commented on cmake/threading_config.cmake
>  endfunction(config_no_threading)
I think this file could probably be removed completely? Now we end up with:
```
if(vt_fcontext_enabled)
  set(vt_fcontext_enabled "1" PARENT_SCOPE)
else()
  set(vt_fcontext_enabled "0" PARENT_SCOPE)
endif()
```
which seems redundant.

2023-01-09 21:12 UTC, cz4rs commented on docs/md/context.md
> -kernel threading/ULT information if worker threads are enabled. The context also
This could still be relevant for `fcontext`.

2023-01-09 21:14 UTC, cz4rs commented on docs/md/vt.md
> +  - Built-in interoperability with MPI and threading libraries (e.g., Kokkos)
```suggestion
  - Built-in interoperability with MPI and threading libraries (e.g. Kokkos, fcontext)
```

2023-01-10 13:46 UTC, thearusable commented on cmake/threading_config.cmake
>  endfunction(config_no_threading)
Thanks, good point. I removed that file and moved it's content to `load_threading_package.cmake`

2023-01-10 13:47 UTC, thearusable commented on docs/md/context.md
> -kernel threading/ULT information if worker threads are enabled. The context also
Ok, I reverted that change

2023-01-10 23:27 UTC, lifflander requested changes

2023-01-10 23:27 UTC, lifflander commented on src/vt/configs/debug/debug_masterconfig.h
>  #define vt_threading_enabled                                             \
Can you delete this macro? For fcontext, this a different macro is used to test if it's enabled.

2023-01-10 23:27 UTC, lifflander commented on src/vt/runtime/runtime.cc
> +void Runtime::initializeWorkers() {
Let's rename this to `initializeTDCallbacks()`

2023-01-10 23:27 UTC, lifflander commented on src/vt/runtime/runtime_get.cc
> +#define IS_COMM_THREAD true
We can remove all of this. Change the uses below of `CUR_RT_TS` to just `curRT`

2023-01-10 23:27 UTC, lifflander commented on src/vt/utils/container/process_ready_buffer.h
> +  void attach(ProcessFnType fn) {
Let's delete this entire file (`process_ready_buffer.h`). In `context_vrtinfo.h`, change `msg_buffer_` to a `std::vector`; in `context_vrtinfo.cc`, make `msg_buffer_.push(msg);` `msg_buffer_.push_back(msg);` and change `msg_buffer.attach` to a for-loop over `msg_buffer` that just calls `enqueueWorkUnit` on all the messages

2023-01-12 10:36 UTC, thearusable commented on src/vt/configs/debug/debug_masterconfig.h
>  #define vt_threading_enabled                                             \
Sure, deleted

2023-01-12 10:36 UTC, thearusable commented on src/vt/runtime/runtime.cc
> +void Runtime::initializeWorkers() {
Renamed

2023-01-12 10:38 UTC, thearusable commented on src/vt/runtime/runtime_get.cc
> +#define IS_COMM_THREAD true
Ok removed.

2023-01-12 10:38 UTC, thearusable commented on src/vt/utils/container/process_ready_buffer.h
> +  void attach(ProcessFnType fn) {
Ok I deleted that file and made code changes as you requested.

2023-01-12 23:21 UTC, lifflander approved these changes
Looks good to me!

2023-01-12 23:22 UTC, lifflander commented
The failing pipelines seem to have nothing to do with this PR.

2023-01-13 00:41 UTC, PhilMiller commented
The commit signatures will need to be fixed

2023-01-13 00:48 UTC, PhilMiller commented on cmake/load_threading_package.cmake
> +endfunction(config_no_threading)
Are these functions having any effect, or can we delete them entirely? They're called based on the value of `vt_fcontext_enabled` as it existed when these functions are about to be called.

2023-01-13 00:51 UTC, lifflander commented
> The commit signatures will need to be fixed

There's no problem with them. The github action is being very unstable.

2023-01-13 00:51 UTC, lifflander commented on cmake/load_threading_package.cmake
> +endfunction(config_no_threading)
Yes, I think this can just be deleted

2023-01-13 00:56 UTC, PhilMiller commented on src/vt/utils/atomic/atomic.h
>  namespace vt { namespace util { namespace atomic {
Can the atomic utility also go away, since it's no longer our concern?

2023-01-13 00:57 UTC, PhilMiller commented on src/vt/utils/mutex/mutex.h
>  using NullMutexType = NullMutex;
Ditto on our own wrapped mutex utility

2023-01-13 00:59 UTC, PhilMiller commented on tests/unit/atomic/test_atomic.cc
> -#endif
If the atomics go away, then the test for them can get deleted too

2023-01-13 01:00 UTC, PhilMiller approved these changes
Other than maybe some left-over bits that can also be deleted, this looks good to me.

2023-01-13 16:36 UTC, thearusable commented on cmake/load_threading_package.cmake
> +endfunction(config_no_threading)
Ok I deleted it

2023-01-13 16:37 UTC, thearusable commented on src/vt/utils/atomic/atomic.h
>  namespace vt { namespace util { namespace atomic {
Sure, I removed it.

2023-01-13 16:38 UTC, thearusable commented on src/vt/utils/mutex/mutex.h
>  using NullMutexType = NullMutex;
Ok null_mutex is removed.

2023-01-13 16:38 UTC, thearusable commented on tests/unit/atomic/test_atomic.cc
> -#endif
Removed

2023-01-13 19:04 UTC, cz4rs commented
> ```
> The following tests FAILED:
> 	395 - vt:TestPreconfig.test_vt_assert_no_mpi (SEGFAULT)
> ```
> 
> I think this might be an independent failure caused by a newer `intel/oneapi` image available. I'll try to reproduce this on `develop` and create a separate issue if needed.

This runs fine on my machine with IntelLLVM 2023.0.0
```
-- The C compiler identification is IntelLLVM 2023.0.0
-- The CXX compiler identification is IntelLLVM 2023.0.0
```
```
vt  build  ctest -R TestPreconfig.test_vt_assert_no_mpi
Test project /home/cz4rs/code/vt/build
    Start 995: vt:TestPreconfig.test_vt_assert_no_mpi
1/1 Test #995: vt:TestPreconfig.test_vt_assert_no_mpi ...   Passed    0.00 sec

100% tests passed, 0 tests failed out of 1
```
I'll try running it inside container :shrug:

2023-01-14 01:15 UTC, PhilMiller commented on cmake/load_threading_package.cmake
> +  set(vt_fcontext_enabled "1")
This can go away too, can't it? `if (X) set(X)`?

2023-01-14 01:17 UTC, PhilMiller commented on src/vt/utils/mutex/mutex.h
Do we need this file at all anymore either?

2023-01-14 01:17 UTC, PhilMiller commented on src/vt/utils/mutex/mutex.h
Or any of `src/vt/utils/mutex/`?

2023-01-16 11:43 UTC, thearusable commented on cmake/load_threading_package.cmake
> +  set(vt_fcontext_enabled "1")
Ah yes! removed.

2023-01-16 11:43 UTC, thearusable commented on src/vt/utils/mutex/mutex.h
Indeed they are not needed anymore. Removed

2023-01-17 18:20 UTC, merged