#2130: Add spec for skipped and identical phases
DARMA-tasking/vt pull request #2137
Opened 2023-04-25 16:16 UTC by thearusable

Closes #2130

2023-05-03 23:53 UTC, lifflander approved these changes
I think this looks good. The next step is to use this data to determine for LBDataRestartReader when a phase is identical or skipped and use to to orchestrate the object distribution.

2023-05-09 22:26 UTC, nlslatt requested changes
There are test failures that need to be resolved.

2023-05-09 22:26 UTC, nlslatt commented on tests/unit/collection/test_lb_data_holder.cc
> +  for (PhaseType i = 0; i < 2; i++) {
Why are you using `PhaseType` here?

2023-05-09 22:26 UTC, nlslatt commented on tests/unit/collection/test_lb_data_holder.cc
> +  ASSERT_EQ(testObj.count_, 0);
Why is this `0` instead of `num_phases`? `addPhasesDataToJson()` should be adding all 10, right?

2023-05-09 22:26 UTC, nlslatt commented on tests/unit/collection/test_lb_data_holder.cc
> +  ASSERT_EQ((*outJsonPtr)["count"], 0);
Why is this `0` instead of `num_phases`? If there were 10 before and nothing is flagged as skipped or identical, where did those phases go?

2023-05-10 08:45 UTC, thearusable commented on tests/unit/collection/test_lb_data_holder.cc
> +  ASSERT_EQ((*outJsonPtr)["count"], 0);
Yes. I pushed a change in code but forgot to push an update in tests.

2023-05-10 08:59 UTC, thearusable commented on tests/unit/collection/test_lb_data_holder.cc
> +  for (PhaseType i = 0; i < 2; i++) {
It's not really needed, I've changed to `unsigned`

2023-05-10 15:42 UTC, nlslatt approved these changes
Should all the checks in the tests really be `ASSERT_*` or should some be `EXPECT_*`? I recommend only using `ASSERT_*` when the checks that follow are no longer valid (and might segfault or do something else bad). Using `EXPECT_*` gives the opportunity to see what independent checks are failing later on in the test.

2023-05-16 22:34 UTC, merged