#2074: support sparse OfflineLB maps
DARMA-tasking/vt pull request #2145
Opened 2023-05-09 16:12 UTC by thearusable

Closes #2074 

Depends on #2137

2023-05-23 20:47 UTC, nlslatt commented on tests/unit/lb/test_lb_reader.nompi.cc
> +  std::string file_name = "test_lb_read_3.txt";
I think we try to make I/O filenames consistent with the test name so that we don't have multiple tests trying to use the same disk file.

2023-05-23 20:47 UTC, nlslatt commented on tests/unit/lb/test_offlinelb.cc
> +  phasesMetadata["skipped"]["range"] = {{2,3}};
Was it deliberate to put phase 2 in both categories?

2023-05-23 20:47 UTC, nlslatt commented on src/vt/vrt/collection/balance/offlinelb/offlinelb.cc
>  }
If `phase_  + 1` was skipped, does this new logic grab `phase_ + 2` if it exists (whether explicitly described in the file or listed as identical) as a surrogate?

@lifflander Is this the desired behavior or do we want to disallow running OfflineLB when we're missing information about the phase?

2023-05-23 20:47 UTC, nlslatt commented on src/vt/vrt/collection/balance/lb_data_restart_reader.cc
> +      next = findNextPhase(curr);
Similar to my other question, do we want to allow OfflineLB to operate over data from non-consecutive phases (where one is explicitly listed as skipped as opposed to just identical)?

2023-06-05 10:39 UTC, thearusable commented on tests/unit/lb/test_lb_reader.nompi.cc
> +  std::string file_name = "test_lb_read_3.txt";
Good point, fixed

2023-06-05 10:44 UTC, thearusable commented on tests/unit/lb/test_offlinelb.cc
> +  phasesMetadata["skipped"]["range"] = {{2,3}};
No, it was a leftover from development, I updated that now.

2023-06-05 11:12 UTC, thearusable commented on src/vt/vrt/collection/balance/offlinelb/offlinelb.cc
>  }
Yes exactly, it will grab `phase_ + 2` or whatever is the next existing phase.

2023-06-12 14:57 UTC, thearusable commented on src/vt/vrt/collection/balance/offlinelb/offlinelb.cc
>  }
@nlslatt I changed the behavior to disallow running of OfflineLB when the phase is skipped.

2023-06-13 11:55 UTC, thearusable commented on src/vt/vrt/collection/balance/lb_data_restart_reader.cc
> +      next = findNextPhase(curr);
@nlslatt I updated that to operate only on consecutive phases.

2023-10-19 14:01 UTC, thearusable commented
@nlslatt, @lifflander - I rebased this PR and fixed all conflicts. PR is ready for review.

2023-11-06 18:26 UTC, nlslatt requested changes
The testing still needs work.

2023-11-06 18:26 UTC, nlslatt commented on tests/unit/lb/test_offlinelb.cc
> +    "6 NoLB\n";
I think this configuration, coupled with your choice of which phases are identical to previous, means that `OfflineLB` by definition has nothing to migrate (for example, phase 1 is said to be identical to phase 0, so nothing should migrate when `OfflineLB` runs on phase 0). As such, this does not appear to be a good test of the sparse functionality.

Also, I think the phases that you have defined as identical to previous contradict what was loaded into the `LBDataHolder` (e.g., phase 1 is marked as identical to phase 0, but the `LBDataHolder` content indicates that they are not identical).

2023-11-06 18:26 UTC, nlslatt commented on src/vt/vrt/collection/balance/lb_data_restart_reader.h
> +   * \return pointer to elements assigned to this node, guaranted to be not null
Typo, should be `guaranteed`

2023-11-29 13:57 UTC, thearusable commented on tests/unit/lb/test_lb_reader.nompi.cc
> +  std::string file_name = "test_lb_read_3_with_offline_lb.txt";
Thanks for the suggestion! I wasn't aware of this helper function.

2023-11-29 13:57 UTC, thearusable commented on tests/unit/lb/test_offlinelb.cc
> +  theConfig()->vt_lb_file_name = "test_offlinelb_2.txt";
Fixed.

2023-11-29 13:57 UTC, thearusable commented on tests/unit/lb/test_offlinelb.cc
> +    if (m->iter == 0 or m->iter == 1 or m->iter == 2 or m->iter == 3 or m->iter == 4 or m->iter == 5 or m->iter == 6) {
Updated.

2023-11-29 13:57 UTC, thearusable commented on src/vt/vrt/collection/balance/lb_data_restart_reader.h
> +   * \return pointer to elements assigned to this node, guaranted to be not null
Fixed.

2023-11-29 13:57 UTC, thearusable commented on tests/unit/lb/test_offlinelb.cc
> +  std::string file_name = "test_offlinelb_2.txt";
Done.

2023-11-30 18:17 UTC, thearusable commented on tests/unit/lb/test_offlinelb.cc
> +    "6 NoLB\n";
Ok, I updated the configuration for this test so the `OfflineLB` will be able to do some migrations. Also I removed unnecessary phases from `LBDataHolder`. 
If you have more suggestions, please let me know.

2024-02-29 14:29 UTC, thearusable commented
I updated this PR to work correctly after removal of the `count_` property from `LBDataHolder`

2024-03-06 16:11 UTC, nlslatt commented
@thearusable Can you please rebase this?

2024-03-06 16:19 UTC, thearusable commented
@nlslatt Ok, rebased.

2024-03-18 20:13 UTC, nlslatt requested changes
As mentioned before, running this load balancer on skipped phases should not be allowed, as there is no data about the placement of tasks on skipped phases. I think that means that `test_offlinelb_2`, as currently written, must fail in order to be correct, as it seems to call the load balancer on all phases. Please revise the testing to make sure LB succeeds across pairs of phases where both have explicit data, either the starting or ending phase was listed as identical to some other phase, and, if possible, to verify that illegal cases are caught and handled appropriately.

2024-03-26 15:00 UTC, thearusable commented
> As mentioned before, running this load balancer on skipped phases should not be allowed, as there is no data about the placement of tasks on skipped phases. I think that means that `test_offlinelb_2`, as currently written, must fail in order to be correct, as it seems to call the load balancer on all phases. Please revise the testing to make sure LB succeeds across pairs of phases where both have explicit data and either the starting or ending phase was listed as identical to some other phase; also, if possible in testing or at least by inspection, verify that illegal cases are caught and handled appropriately.

@nlslatt Sorry I somehow missed that when doing the last update.

Now I updated it to not allow to run on skipped phases - doing so will result in triggering of vtAssert.  Other than that mixing normal and identical phases seems to work fine.

2024-03-26 15:53 UTC, nlslatt requested changes
This looks much better, but is segfaulting for me. I think the new `ReadLBConfig::hasOfflineLB()` needs to be tied into `LBDataRestartReader::needsLB()`.

2024-03-27 15:17 UTC, thearusable commented
@nlslatt I've added an additional check to see if `LBDataRestartReader` can run `OfflineLB` even if it was requested in the config file. That was the only way I was able to provoke a crash.

Please let me know if that fixes crashing on your end.

2024-04-19 13:29 UTC, thearusable commented
@nlslatt - I made a fix for the crash you had. Please check if this doesn't happen to you anymore.

I've added test cases to cover different combinations of parameters when initializing vt so this PR can be reviewed.

2024-05-21 16:02 UTC, nlslatt requested changes
Most of it looks great, but I think there's an issue with some of the tests.

2024-05-21 16:02 UTC, nlslatt commented on tests/unit/runtime/test_initialization.cc
> +void preapreLBDataFiles(const std::string file_name_without_ext) {
Typo in name. I'm also confused a little by this function. In the example `something.%p.json`, The `%p` is a placeholder for the rank number. There should be one file per rank. It looks like the number of files might be hard-coded to 9 (is that per rank?) and that the rank number is added in an inappropriate location. Please let me know if you want to discuss this further.

2024-05-23 15:42 UTC, thearusable commented on tests/unit/runtime/test_initialization.cc
> +void preapreLBDataFiles(const std::string file_name_without_ext) {
I fixed the typo. Ah yes, Indeed I was creating 9 files for each rank by accident. Now this is cleaned up - also adding the rank number is removed. 
Please let me know if there is anything else that I should fix.

2024-05-23 17:16 UTC, nlslatt requested changes
Your recent changes look good. One last thing to address, I think. It segfaults when `OfflineLB` is requested but the user forgets to also use the command-line argument `--vt_lb_data_in`. We need to give a usable error message instead.

2024-05-24 12:22 UTC, thearusable commented
> Your recent changes look good. One last thing to address, I think. It segfaults when `OfflineLB` is requested but the user forgets to also use the command-line argument `--vt_lb_data_in`. We need to give a usable error message instead.

Thanks for catching that issue! Looks like it also happens on the `develop`.

Instead of showing the error message I changed the code to allow for more relaxed `OfflineLB` related configuration. 
With latest changes we will check if we need `LBDataRestartReader` to be created when we supply one or more of those parameters:
`--vt_lb_data_in`, `--vt_lb_name`, `--vt_lb_file_name`.
Then we will check if the `--vt_lb_file_name` exists and if it requires the `OfflineLB` to be run.

```
bool data_in = arg_config_->config_.vt_lb_data_in;
bool requested_offline_lb = arg_config_->config_.vt_lb_name == get_lb_names()[LBType::OfflineLB];
bool has_file = arg_config_->config_.vt_lb_file_name != "";

if (data_in || requested_offline_lb || has_file) {
  auto& config_file = arg_config_->config_.vt_lb_file_name;
  if (config_file != "") {
    bool const has_spec = ReadLBConfig::openConfig(config_file);
    if (has_spec) {
      return ReadLBConfig::hasOfflineLB();
    }
  }
  return true;
}
```

Please let me know if that is ok to you or do you prefer to show a message that vt is not configured properly to run `OfflineLB`.

2024-05-29 18:02 UTC, nlslatt commented
> > Your recent changes look good. One last thing to address, I think. It segfaults when `OfflineLB` is requested but the user forgets to also use the command-line argument `--vt_lb_data_in`. We need to give a usable error message instead.
> 
> Thanks for catching that issue! Looks like it also happens on the `develop`.
> 
> Instead of showing the error message I changed the code to allow for more relaxed `OfflineLB` related configuration. With latest changes we will check if we need `LBDataRestartReader` to be created when we supply one or more of those parameters: `--vt_lb_data_in`, `--vt_lb_name`, `--vt_lb_file_name`. Then we will check if the `--vt_lb_file_name` exists and if it requires the `OfflineLB` to be run.
> 
> ```
> bool data_in = arg_config_->config_.vt_lb_data_in;
> bool requested_offline_lb = arg_config_->config_.vt_lb_name == get_lb_names()[LBType::OfflineLB];
> bool has_file = arg_config_->config_.vt_lb_file_name != "";
> 
> if (data_in || requested_offline_lb || has_file) {
>   auto& config_file = arg_config_->config_.vt_lb_file_name;
>   if (config_file != "") {
>     bool const has_spec = ReadLBConfig::openConfig(config_file);
>     if (has_spec) {
>       return ReadLBConfig::hasOfflineLB();
>     }
>   }
>   return true;
> }
> ```
> 
> Please let me know if that is ok to you or do you prefer to show a message that vt is not configured properly to run `OfflineLB`.



> > Your recent changes look good. One last thing to address, I think. It segfaults when `OfflineLB` is requested but the user forgets to also use the command-line argument `--vt_lb_data_in`. We need to give a usable error message instead.
> 
> Thanks for catching that issue! Looks like it also happens on the `develop`.
> 
> Instead of showing the error message I changed the code to allow for more relaxed `OfflineLB` related configuration. With latest changes we will check if we need `LBDataRestartReader` to be created when we supply one or more of those parameters: `--vt_lb_data_in`, `--vt_lb_name`, `--vt_lb_file_name`. Then we will check if the `--vt_lb_file_name` exists and if it requires the `OfflineLB` to be run.
> 
> ```
> bool data_in = arg_config_->config_.vt_lb_data_in;
> bool requested_offline_lb = arg_config_->config_.vt_lb_name == get_lb_names()[LBType::OfflineLB];
> bool has_file = arg_config_->config_.vt_lb_file_name != "";
> 
> if (data_in || requested_offline_lb || has_file) {
>   auto& config_file = arg_config_->config_.vt_lb_file_name;
>   if (config_file != "") {
>     bool const has_spec = ReadLBConfig::openConfig(config_file);
>     if (has_spec) {
>       return ReadLBConfig::hasOfflineLB();
>     }
>   }
>   return true;
> }
> ```
> 
> Please let me know if that is ok to you or do you prefer to show a message that vt is not configured properly to run `OfflineLB`.



> > Your recent changes look good. One last thing to address, I think. It segfaults when `OfflineLB` is requested but the user forgets to also use the command-line argument `--vt_lb_data_in`. We need to give a usable error message instead.
> 
> Thanks for catching that issue! Looks like it also happens on the `develop`.
> 
> Instead of showing the error message I changed the code to allow for more relaxed `OfflineLB` related configuration. With latest changes we will check if we need `LBDataRestartReader` to be created when we supply one or more of those parameters: `--vt_lb_data_in`, `--vt_lb_name`, `--vt_lb_file_name`. Then we will check if the `--vt_lb_file_name` exists and if it requires the `OfflineLB` to be run.
> 
> ```
> bool data_in = arg_config_->config_.vt_lb_data_in;
> bool requested_offline_lb = arg_config_->config_.vt_lb_name == get_lb_names()[LBType::OfflineLB];
> bool has_file = arg_config_->config_.vt_lb_file_name != "";
> 
> if (data_in || requested_offline_lb || has_file) {
>   auto& config_file = arg_config_->config_.vt_lb_file_name;
>   if (config_file != "") {
>     bool const has_spec = ReadLBConfig::openConfig(config_file);
>     if (has_spec) {
>       return ReadLBConfig::hasOfflineLB();
>     }
>   }
>   return true;
> }
> ```
> 
> Please let me know if that is ok to you or do you prefer to show a message that vt is not configured properly to run `OfflineLB`.



> > Your recent changes look good. One last thing to address, I think. It segfaults when `OfflineLB` is requested but the user forgets to also use the command-line argument `--vt_lb_data_in`. We need to give a usable error message instead.
> 
> Thanks for catching that issue! Looks like it also happens on the `develop`.
> 
> Instead of showing the error message I changed the code to allow for more relaxed `OfflineLB` related configuration. With latest changes we will check if we need `LBDataRestartReader` to be created when we supply one or more of those parameters: `--vt_lb_data_in`, `--vt_lb_name`, `--vt_lb_file_name`. Then we will check if the `--vt_lb_file_name` exists and if it requires the `OfflineLB` to be run.
> 
> ```
> bool data_in = arg_config_->config_.vt_lb_data_in;
> bool requested_offline_lb = arg_config_->config_.vt_lb_name == get_lb_names()[LBType::OfflineLB];
> bool has_file = arg_config_->config_.vt_lb_file_name != "";
> 
> if (data_in || requested_offline_lb || has_file) {
>   auto& config_file = arg_config_->config_.vt_lb_file_name;
>   if (config_file != "") {
>     bool const has_spec = ReadLBConfig::openConfig(config_file);
>     if (has_spec) {
>       return ReadLBConfig::hasOfflineLB();
>     }
>   }
>   return true;
> }
> ```
> 
> Please let me know if that is ok to you or do you prefer to show a message that vt is not configured properly to run `OfflineLB`.

@lifflander and I discussed it, and we prefer just showing an error message when `OfflineLB` is requested but `--vt_lb_data_in` is not specified. Automatically enabling `--vt_lb_data_in` has undesirable consequences.

2024-06-04 15:50 UTC, thearusable commented
@nlslatt Ok, I changed it to abort when VT is misconfigured.

2024-06-04 16:23 UTC, nlslatt commented
> @nlslatt Ok, I changed it to abort when VT is misconfigured.

@thearusable Your check only covers one of two mechanisms for enabling OfflineLB. Perhaps first check if OfflineLB is enabled by any mechanism, and then abort if the necessary flag was not passed.

2024-06-04 16:26 UTC, thearusable commented
@nlslatt Ah, yes, right! I'll update that

2024-06-11 16:47 UTC, nlslatt commented on src/vt/runtime/runtime.cc
> +    vtAbort("VT cannot run OfflineLB without '--vt_lb_data_in' parameter.");
While I am seeing your `vtAbort()` at runtime, I'm also getting a segfault. I'm not sure yet what's going wrong.

```
vt: Caught SIGSEGV signal: 11 
vt: [-1] ------------------------------------------------------------------------------------------------------------------------
vt: [-1] ------------------------------------------- Runtime Error: System Aborting! --------------------------------------------
vt: [-1] ------------------------------------------------ Fatal Error on Node -1 ------------------------------------------------
vt: [-1] ------------------------------------------------------------------------------------------------------------------------
vt: [-1] 
vt: [-1]              Reason: VT cannot run OfflineLB without '--vt_lb_data_in' parameter.
vt: [-1]                Type: vtAbort() Invoked
vt: [-1]                Node: -1
vt: [-1]           Num Nodes: -1
vt: [-1]                File: /Users/nlslatt/work/vt/vt-pr/src/vt/runtime/runtime.cc
vt: [-1]                Line: 441
vt: [-1]            Function: needLBDataRestartReader
vt: [-1]                Code: 1
```

2024-06-25 22:37 UTC, nlslatt approved these changes
Looks good!

2024-06-25 22:38 UTC, merged