#2183: LDMS: add stream for phase data
DARMA-tasking/vt pull request #2184
Opened 2023-08-10 23:36 UTC by lifflander

Fixes #2183

2023-10-03 13:11 UTC, JacobDomagala commented
Code used for reading the data:
```c++
#include <ldms/ldms.h>
#include <ldms/ldmsd_stream.h>
#include <ovis_util/util.h>

int stream_handler(ldmsd_stream_client_t c, void *ctxt,
                    ldmsd_stream_type_t stream_type,
                    const char *data, size_t data_len,
                    json_entity_t entity)
{
    // Process the received data
    printf("%.*s\n", (int)data_len, data);

    return 0;
}

int main()
{
    ldms_init(256);
    ldms_t ldms = ldms_xprt_new_with_auth("sock", "none", NULL);
    int rc = ldms_xprt_connect_by_name(ldms, "localhost", "10444", NULL, NULL);
    if(!rc){
      printf("Error code %d \n", rc);
    }
    ldmsd_stream_subscribe("LB_data", stream_handler, NULL);
    while (1){
         // Keep running to continue receiving data
    }
    ldms_xprt_put(ldms);
    return 0;
}
``` 

Config file:
export HOSTNAME=localhost
export COMPONENT_ID=1
```
load name=hello_sampler
config name=hello_sampler producer=${HOSTANAME} instance=${HOSTNAME}/hello_sampler component_id=${COMPONENT_ID} stream=LB_data
```

Script to launch the LDMS deamon:
```bash
#!/bin/bash

TOP=/ovis/LDMS_install
export LD_LIBRARY_PATH=$TOP/lib/:$TOP/lib:$LD_LIBRARY_PATH
export LDMSD_PLUGIN_LIBPATH=$TOP/lib/ovis-ldms
export ZAP_LIBPATH=$TOP/lib/ovis-ldms
export PATH=$TOP/sbin:$TOP/bin:$PATH
export PYTHONPATH=$TOP/lib/python2.7/site-packages


ldmsd -x sock:10444 -c /ldmsd.conf -l /tmp/demo_ldmsd_log -v DEBUG -r $(pwd)/ldmsd.pid

```

2025-07-21 17:27 UTC, cz4rs commented
@Logan590 Please fix the commit message for ca0cdd3 (just start it with `#2183:`).

https://github.com/DARMA-tasking/vt/wiki/Pull-Requests#commit-formatting

2025-07-21 17:32 UTC, cz4rs commented on scripts/workflow-azure-template.yml
> +  VT_LDMS: [% vt_ldms %]
Let's just drop the Azure changes, we'll be removing all this soon.

2025-07-21 17:39 UTC, cz4rs commented on src/vt/configs/arguments/app_config.h
> +#include <cstdint>
Remove this if there are no other changes in the file.

2025-07-21 17:41 UTC, cz4rs commented on src/vt/configs/arguments/app_config.h
> +#include <cstdint>
Unless it's actually necessary :thinking: Never mind.

2025-07-21 17:42 UTC, cz4rs commented on src/vt/utils/compress/decompressor_base.h
> +#include <cstdint>
Ok, this one is clearly redundant (see line 48).

2025-07-23 07:29 UTC, Logan590 commented on scripts/workflow-azure-template.yml
> +  VT_LDMS: [% vt_ldms %]
Okay, I deleted this line so.

2025-07-23 07:31 UTC, Logan590 commented on src/vt/utils/compress/decompressor_base.h
> +#include <cstdint>
Yes, my bad, I deleted this line.

2025-07-25 11:44 UTC, Logan590 commented
@lifflander, there are many versions of LDMS. I'm currently using the version 4.3.5 to work on this issue. Does it seem good to you ?

2025-07-25 13:33 UTC, cz4rs commented on ci/azure/azure-clang-10-ubuntu-mpich.yml
> +  VT_LDMS: 0
This needs to be removed from all workflows. Remove from template and use `scripts/generate-workflow.pl` to regenerate all files.

2025-07-25 13:37 UTC, cz4rs commented on ci/build_cpp.sh
> +      -Dvt_ldms_includes="${VT_LDMS_INCLUDES_DIR:-/opt/ovis/LDMS_install/include/}" \
Make sure that this is in sync with https://github.com/DARMA-tasking/workflows/pull/31.

2025-07-25 20:03 UTC, cz4rs commented on docker-bake.hcl
> +        vt_ldms = 1
We need to add a new build based on `amd64-ubuntu-20-04-gcc-9-ldms-cpp` image instead. Requires https://github.com/DARMA-tasking/workflows/pull/31 to be merged first.

2025-07-25 20:10 UTC, cz4rs requested changes

2025-07-25 20:10 UTC, cz4rs commented on ci/build_cpp.sh
> +      -Dvt_fcontext_build_tests_examples="${VT_FCONTEXT_BUILD_TESTS_EXAMPLES:-1}" \
Is that change necessary?

2025-07-25 20:10 UTC, cz4rs commented on ci/build_cpp.sh
> +      -Dvt_ldms_enabled="${VT_LDMS_ENABLED:-1}" \
Should it be enabled by default?

2025-07-25 20:10 UTC, cz4rs commented on ci/deps/ldms.sh
> +#!/usr/bin/env bash
Remove.

2025-07-25 20:10 UTC, cz4rs commented on docker-bake.hcl
> +  tags = ["vt:amd64-ubuntu-24.04-gcc-13-cpp"]
Remove.

2025-07-25 20:10 UTC, cz4rs commented on ci/docker/vt.dockerfile
> +WORKDIR /build/examples/collection
Doesn't seem to be used anywhere. Remove?

2025-07-31 15:10 UTC, JacobDomagala commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +#include <fmt-vt/core.h>
This will fail when we use external `fmt`, please change to `#include INCLUDE_FMT_CORE` or `#include INCLUDE_FMT_FORMAT`

2025-07-31 18:37 UTC, Logan590 commented
LDMS Test Procedure Summary
===========================

Here’s the step-by-step process I followed to test LDMS integration with the VT workflow project.

1. Launching the Workflow Docker Image
--------------------------------------

After cloning the workflow project:

    sudo docker buildx bake amd64-ubuntu-20-04-gcc-9-ldms-cpp

    sudo docker run -it --rm \
      --network=host \
      --pid=host \
      lifflander1/vt:wf-amd64-ubuntu-20.04-gcc-9-ldms-cpp bash

Inside the container:

    git clone https://github.com/DARMA-tasking/vt.git
    cd vt
    git checkout 2183-create-ldma-stream-publish-for-phase-data

    ./ci/build_cpp.sh /vt/ /vt/build/ install 20 

    export VT_LDMS_XPTR=sock
    export VT_LDMS_PORT=411
    export VT_LDMS_HOSTNAME=localhost
    export VT_LDMS_AUTH=none

2. Running the LDMS Daemon (Second Terminal)
--------------------------------------------

    sudo docker run --rm -it \
      --network=host \
      --pid=host \
      --privileged \
      --entrypoint /bin/bash \
      ovishpc/ldms-samp

Inside the container:

    cat <<EOF > /tmp/ldmsd.conf
    load name=stream
    listen xprt=sock port=411
    auth name=none
    EOF

    ldmsd -x sock:411 -a none

3. Running the LDMS Aggregator (Third Terminal)
-----------------------------------------------

    sudo docker run -it --rm \
      --network=host \
      --pid=host \
      --entrypoint /bin/bash \
      ovishpc/ldms-agg

Then launch the LDMS control interface:

    ldmsctl -x sock -a none -h localhost -p 411

4. Running the VT Example (Back in First Terminal)
--------------------------------------------------

Inside the workflow Docker container:

    LD_LIBRARY_PATH=/opt/ldms/lib \
    mpirun -n 4 /vt/build/vt/examples/collection/lb_iter

5. Checking the Stream Status (Third Terminal)
----------------------------------------------

In the LDMS Aggregator container, use:

    stream_status

This allows you to confirm if the stream was correctly published and received.

Here is an example of what you should get if it works:
<img width="844" height="209" alt="image" src="https://github.com/user-attachments/assets/b5228b20-6b4a-4a08-95db-b76e6b8781b5" />

2025-07-31 21:52 UTC, cz4rs requested changes

2025-07-31 21:52 UTC, cz4rs commented on ci/docker/vt.dockerfile
> +        fi
GitHub complains about missing newline at the end of file. Make sure that there are no changes here.

2025-07-31 21:52 UTC, cz4rs commented on ci/deps/ldms.sh
> +
Remove this, we should be able to use LDMS installation from the `wf-amd64-ubuntu-20.04-gcc-9-ldms-cpp` image.

2025-07-31 21:52 UTC, cz4rs commented on CMakeLists.txt
> +endif()
Move this to `cmake/configure_options.cmake` and use `define_option` helper there. See the line for `vt-tv` for example.

2025-07-31 21:52 UTC, cz4rs commented on CMakeLists.txt
> +endif()
Also use `vt_ldms_enabled` for consistency.

2025-07-31 21:52 UTC, cz4rs commented on CMakeLists.txt
> +  include_directories(SYSTEM /opt/ldms/include)
This should not be necessary when we have `target_include_directories` and `target_link_directories` in `link_vt.cmake`.

2025-07-31 21:52 UTC, cz4rs commented on cmake/configure_options.cmake
> +        message(STATUS "Using user provided vt_ldms_libs=${vt_ldms_libs}")
Those should be debug messages.

2025-07-31 21:52 UTC, cz4rs commented on docker-bake.hcl
> +    VT_LDMS_ENABLED                = vt_ldms(item)
You need to enable it somewhere (create a workflow based on `wf-amd64-ubuntu-20.04-gcc-9-ldms-cpp` image).

2025-07-31 21:52 UTC, cz4rs commented on scripts/workflows-azure.ini
There should be no changes here.

2025-07-31 21:52 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  if (auto ldms_freq = getenv("VT_LDMS_MILLI_FREQ")) {
There's no mention of this variable anywhere else.

2025-07-31 21:52 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  const auto xPtr = getenv("VT_LDMS_XPTR");
Typo: name should match ldms function call bellow.
```suggestion
  const auto xPtr = getenv("VT_LDMS_XPRT");
```

2025-07-31 21:52 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  const auto xPtr = getenv("VT_LDMS_XPTR");
Fix variable name as well.

2025-07-31 21:52 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  vtWarnIf(returnCode == 0, fmt::format("ldms_xprt_connect_by_name failed with code {} \n", returnCode));
Extract LDMS initialization into a helper method.

2025-07-31 21:52 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.h
> +  void writeJSONToLDMS(nlohmann::json& j);
Can you make the argument a const ref?

2025-07-31 21:52 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  ldms_ = ldms_xprt_new_with_auth(xPtr, NULL, auth, NULL);
Do we need any kind of `finalize` / clean-up at the end for this?

2025-07-31 22:05 UTC, cz4rs commented
@Logan590 
Finish you docker configuration so you don't have to use `sudo` every time: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user.

---

> After cloning the workflow project:
> 
> ```
> sudo docker buildx bake amd64-ubuntu-20-04-gcc-9-ldms-cpp

This image is already available on DockerHub, you can use:
```
docker pull lifflander1/vt:wf-amd64-ubuntu-20.04-gcc-9-ldms-cpp
```

---

> ```
> sudo docker run -it --rm \
>   --network=host \
>   --pid=host \
>   lifflander1/vt:wf-amd64-ubuntu-20.04-gcc-9-ldms-cpp bash
> ```

Add another bake target (as mentioned in the review) and you should be able to use `docker buildx bake ...` as usual.

---

> ```
> LD_LIBRARY_PATH=/opt/ldms/lib \
> mpirun -n 4 /vt/build/vt/examples/collection/lb_iter
> ```

If we need to modify `LD_LIBRARY_PATH` we should do this in the `workflows` repositoy (`icpc` image already does this). It seems that the build stage does work without this though?

2025-08-03 15:04 UTC, Logan590 commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  if (auto ldms_freq = getenv("VT_LDMS_MILLI_FREQ")) {
Should I remove it ?

2025-08-03 15:15 UTC, Logan590 commented on docker-bake.hcl
> +    VT_LDMS_ENABLED                = vt_ldms(item)
I created a new workflow in docker-bake.hcl

2025-08-04 13:11 UTC, cz4rs commented
@Logan590 Please respond directly in the conversation after you've addressed the comments, it makes it easier to track changes and resolve discussion.

2025-08-04 13:14 UTC, cz4rs requested changes
`ldms` is not enabled during CMake configuration, see https://github.com/DARMA-tasking/vt/actions/runs/16706479964/job/47285324827?pr=2184#step:7:804. Add an argument in `vt.dockerfile` so the configuration from `docker-bake.hcl` is passed correctly to build script.

2025-08-04 13:14 UTC, cz4rs commented on CMakeLists.txt
> +  target_compile_definitions(${VIRTUAL_TRANSPORT_LIBRARY} PUBLIC VT_LDMS_ENABLED=1)
`#if vt_check_enabled(ldms)` uses `vt_feature_cmake_ldms`, so I don't think there's a need to add this as well.

2025-08-04 13:14 UTC, cz4rs commented on CMakeLists.txt
> +  target_compile_definitions(${VIRTUAL_TRANSPORT_LIBRARY} PUBLIC VT_LDMS_ENABLED=1)
Remove.

2025-08-04 13:14 UTC, cz4rs commented on CMakeLists.txt
> +  target_compile_definitions(${VIRTUAL_TRANSPORT_LIBRARY} PUBLIC VT_LDMS_ENABLED=0)
Remove.

2025-08-04 13:14 UTC, cz4rs commented on CMakeLists.txt
> +  target_link_directories(${VIRTUAL_TRANSPORT_LIBRARY} PRIVATE "${vt_ldms_libs}")
This should go to `link_vt.cmake`.

2025-08-04 13:19 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  if (auto ldms_freq = getenv("VT_LDMS_MILLI_FREQ")) {
Nope, we should just document this option.

2025-08-05 14:39 UTC, Logan590 commented on CMakeLists.txt
> +  target_link_directories(${VIRTUAL_TRANSPORT_LIBRARY} PRIVATE "${vt_ldms_libs}")
I removed all the lines.

2025-08-05 16:43 UTC, Logan590 commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  vtWarnIf(returnCode == 0, fmt::format("ldms_xprt_connect_by_name failed with code {} \n", returnCode));
This part is done.

2025-08-05 16:43 UTC, Logan590 commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  if (auto ldms_freq = getenv("VT_LDMS_MILLI_FREQ")) {
I added a comment.

2025-08-05 16:56 UTC, cz4rs commented
@Logan590 Please do a rebase instead of merging `develop` into this branch.

2025-08-05 21:25 UTC, cz4rs commented
@Logan590 GitHub still shows `The branch has conflicts that must be resolved` and CI got stuck and is not running anything. Fix the conflicts, make sure that history is good and run `git pull --rebase origin develop` at the end to sync with the latest changes.

2025-08-11 23:35 UTC, cz4rs commented on ci/docker/vt.dockerfile
> +ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH
This (and corresponding `docker-bake.hcl` code) can be removed after https://github.com/DARMA-tasking/workflows/issues/34 is merged.

2025-08-11 23:37 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.cc
> +  const auto port = getenv("VT_LDMS_PORT");
Those variables should be documented along with the LDMS test procedure described earlier. Maybe a wiki page?

2025-08-12 14:04 UTC, cz4rs commented
@JacobDomagala Can you please have a look?

2025-08-12 14:25 UTC, JacobDomagala commented on src/vt/vrt/collection/balance/node_lb_data.h
> +  void writeJSONToLDMS(const nlohmann::json& j);
For consistency we should not expose this function when `ldms` is not enabled.

2025-08-12 14:27 UTC, JacobDomagala commented on src/vt/vrt/collection/balance/node_lb_data.h
> +  void initializeLDMS();
I think we should move the declaration of `initializeLDMS()` near `writeJSONToLDMS()` and we could add doxygen expplaining what env variables it uses.

2025-08-12 14:40 UTC, JacobDomagala commented on src/vt/vrt/collection/balance/node_lb_data.h
> +  void writeJSONToLDMS(const nlohmann::json& j);
This will also make the `codecov` happy (it's complaining `writeJSONToLDMS` is not being called)

2025-08-12 15:08 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.h
> +  void writeJSONToLDMS(const nlohmann::json& j);
Done.

2025-08-12 15:09 UTC, cz4rs commented on src/vt/vrt/collection/balance/node_lb_data.h
> +  void initializeLDMS();
I moved it closer, but kept it in the `private` section. Documentation added, abusing `/param` for clarity.

2025-08-12 15:11 UTC, JacobDomagala approved these changes
Looks good!

2025-08-12 15:21 UTC, cz4rs approved these changes
Looks good to me in the parts I haven't touched.

2025-08-12 19:29 UTC, lifflander reviewed
Looks good to me!

2025-08-12 19:29 UTC, merged