#2195: termination: make actions run consistently in a runnable
DARMA-tasking/vt pull request #2196
Opened 2023-09-28 18:58 UTC by lifflander

Fixes #2195

2023-10-02 15:21 UTC, Matthew-Whitlock requested changes

2023-10-02 15:21 UTC, Matthew-Whitlock commented on src/vt/termination/term_action.cc
> +      .withTDEpoch(theTerm()->getEpoch())
One runnable per action would also solve the issue of potentially non-deterministic action ordering, since any actions blocking on eg `runSchedulerThrough` would allow the scheduler to run other actions as normal.

2023-10-02 16:16 UTC, lifflander commented on src/vt/termination/term_action.cc
> +      .withTDEpoch(theTerm()->getEpoch())
> We're setting every action to run within `getEpoch` at the time the epoch finishes, which is nondeterministic.
> 
> The epoch should be set to `getEpoch` at the time of `addActionEpoch` below and in `addActionUnique` [here](https://github.com/DARMA-tasking/vt/blob/9b8df4fd8568699b2b37e6398c39902124526df2/src/vt/termination/term_action.impl.h#L57), so it'd probably be best to make the runnable at those points and store the un-enqueued runnables if that's possible.

Good point! Initially I was creating the runnable right away, but forgot to move the epoch call.

2023-10-02 23:02 UTC, lifflander commented on src/vt/termination/term_action.cc
> +      .withTDEpoch(theTerm()->getEpoch())
I believe this should be fixed now.

2023-10-02 23:05 UTC, lifflander commented
A test still needs to be written for this.

2023-10-03 18:34 UTC, Matthew-Whitlock approved these changes

2023-10-04 21:29 UTC, lifflander commented on src/vt/termination/term_action.cc
> +void TermAction::produceOn(EpochType epoch) const {
This is called from the function in `term_action.impl.h` which can't call produce directly due to a header dependency.

2023-10-04 23:58 UTC, lifflander commented on src/vt/termination/term_action.cc
> +    theTerm()->produce(encapsulated_epoch);
I've created an issue to address this. Right now, this isn't quite possible due to how addDepenency is implemented. #2197

2023-10-04 23:58 UTC, merged