#2171: Implement addUserDefinedData function to PhaseManager
DARMA-tasking/vt pull request #2199
Opened 2023-10-13 14:59 UTC by JacobDomagala

Fixes #2171

2023-10-31 16:39 UTC, lifflander approved these changes
Looks good to me

2023-11-06 17:19 UTC, nlslatt requested changes
Please see concern below.

2023-11-06 17:19 UTC, nlslatt commented on src/vt/phase/phase_manager.h
> +  theNodeLBData()->getLBData()->user_per_phase_json_[phase] = j;
Does this approach limit the user-defined data to a single key-value pair? I think we should allow as much as the application wants to provide.

2023-11-07 08:36 UTC, JacobDomagala commented on src/vt/phase/phase_manager.h
> +  theNodeLBData()->getLBData()->user_per_phase_json_[phase] = j;
Updated

2023-11-07 16:31 UTC, nlslatt approved these changes
Looks good

2023-11-07 16:32 UTC, merged