#2200: Link to documentation for other libraries
DARMA-tasking/vt pull request #2202
Opened 2023-10-17 19:10 UTC by cwschilly

Fixes #2200

2023-10-18 17:30 UTC, lifflander requested changes

2023-10-18 19:27 UTC, cwschilly commented on docs/md/mainpage.md
> +| HPC Serialization                  | @m_span{m-text m-success} DARMA/checkpoint @m_endspan (Checkpointing and Serialization Library)     | [Github](https://github.com/DARMA-tasking/checkpoint), [Do
I've replaced `DARMA/checkpoint` with `DARMA/magistrate` in the second column. Was there any other instance of `checkpoint` you want me to replace?

2023-10-18 19:27 UTC, cwschilly commented on docs/md/mainpage.md
> +| HPC LB Simulator                   | @m_span{m-text m-success} DARMA/LBAF @m_endspan (Load Balancing Analysis Framework)                 | [Github](https://github.com/DARMA-tasking/LB-analysis-fram
Done

2023-10-18 19:27 UTC, cwschilly commented on docs/md/mainpage.md
>  | Toolkit documentation              | @m_span{m-text m-success} DARMA/docs @m_endspan                                                     | [Docs](https://github.com/DARMA-tasking/DARMA-tasking.gith
Done

2023-10-24 17:06 UTC, lifflander approved these changes

2023-10-30 18:21 UTC, merged