#2125: Fix sprintf warnings
DARMA-tasking/vt pull request #2208
Opened 2023-10-27 13:51 UTC by thearusable

Closes #2125

2023-10-27 13:56 UTC, JacobDomagala approved these changes

2023-10-27 17:02 UTC, nlslatt requested changes
Please see comment below.

2023-10-27 17:02 UTC, nlslatt commented on src/vt/group/collective/group_info_collective.cc
> +        cur += snprintf(buf + cur, max_buffer_length, "%d,", elm);
Should this use `max_buffer_length - cur` instead of `max_buffer_length` because we are potentially writing mid-buffer?

2023-10-30 09:41 UTC, thearusable commented on src/vt/group/collective/group_info_collective.cc
> +        cur += snprintf(buf + cur, max_buffer_length, "%d,", elm);
Ah, Yes, You're right.

2023-11-06 19:24 UTC, nlslatt approved these changes
Looks good

2023-11-07 17:38 UTC, lifflander approved these changes

2023-11-07 20:03 UTC, merged