#2225: fix missing `<cstdint>` include
DARMA-tasking/vt pull request #2226
Opened 2023-12-01 14:34 UTC by cz4rs

fixes #2225 

Stumbled upon this when working on NimbleSM :slightly_smiling_face:

2023-12-04 16:07 UTC, JacobDomagala approved these changes

2023-12-05 17:37 UTC, nmm0 requested changes

2023-12-05 17:37 UTC, nmm0 commented on src/vt/configs/error/stack_out.h
> -#include <cstdlib>
I think technically `std::size_t` is from `<cstdlib>` and not `<cstdint>` though likely string and vector will pull it in. But for full portability we should keep this include

2023-12-05 17:37 UTC, nmm0 commented on src/vt/utils/compress/decompressor_base.h
> -#include <cstdlib>
Same as above

2023-12-06 20:35 UTC, lifflander approved these changes

2024-01-02 21:12 UTC, cwschilly commented
@cz4rs @lifflander @ppebay I rebased this PR but it is showing Partially Verified again--I think @cz4rs has to do the rebase in order for the commits to be properly signed (see ["Vigilant Mode"](https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits)).

2024-01-02 21:17 UTC, cz4rs commented
> @cz4rs @lifflander @ppebay I rebased this PR but it is showing Partially Verified again--I think @cz4rs has to do the rebase in order for the commits to be properly signed (see ["Vigilant Mode"](https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits)). 

I'll do the rebase in a moment :)

2024-01-03 19:24 UTC, merged