#2175: Add YAML as input as alternative to command-line arguments
DARMA-tasking/vt pull request #2230
Opened 2023-12-20 16:35 UTC by cwschilly

Fixes #2175

2023-12-20 16:44 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +        false // not required
The idea is that the user would not pass `--vt_input_CLI_config`; they would pass their file with `--vt_input_config` (as is the current API), and if it is a `toml` or `ini` file it would be set as the default value for the `app.set_config()` function.

2023-12-20 17:43 UTC, lifflander commented on src/vt/configs/arguments/args.cc
> +        false // not required
This looks good to me!

2023-12-20 21:21 UTC, cwschilly commented
I'm not sure what's going on with the `PR checks (git --check)` pipeline--there isn't any trailing white space in the file it's talking about

2023-12-21 13:16 UTC, JacobDomagala commented
I think we should strip it down to bare minimum. We don't need `test` and `contributing` dirs. That would also resolve the trailing whitespace issue : ) 

Should we also support using external `yaml-cpp`? Same way we intent to do with `fmt` (https://github.com/DARMA-tasking/vt/pull/2221)

2023-12-21 15:18 UTC, cwschilly commented
> Should we support using external `yaml-cpp`? Same way we intent to do with `fmt` (#2221)

I think this makes sense, especially since it seems the yaml-cpp source code doesn't pass the CI

2023-12-22 11:55 UTC, JacobDomagala commented
Also, is the use of a yaml-based config file incentivized by something (like Empire already using that file type)? If not, maybe we should consider using JSON for the config file as well? We already have it set up, and its structure is well-known to everyone.

2024-01-02 22:08 UTC, lifflander commented
> Also, is the use of a yaml-based config file incentivized by something (like Empire already using that file type)? If not, maybe we should consider using JSON for the config file as well? We already have it set up, and its structure is well-known to everyone.

Yes, Empire is using YAML for their input and we want to be able to pass that directly to VT. LBAF and vt-tv are also using YAML so it seems that that route makes sense.

2024-01-03 22:10 UTC, cwschilly commented
I've taken the approach of [this PR](https://github.com/jbeder/yaml-cpp/pull/815) to yaml-cpp in order to resolve the clang warnings.

2024-01-04 21:21 UTC, cwschilly commented on lib/yaml-cpp/include/yaml-cpp/null.h
> +extern YAML_CPP_API _Null BaseNull;
To avoid the shadowing warning caused by this (`YAML::Null`) and `YAML::NodeType::Null`, I've renamed this variable to `YAML::BaseNull`. I don't imagine that this will have any far-reaching consequences, but I want to highlight it just in case.

2024-04-23 20:13 UTC, JacobDomagala commented on lib/yaml-cpp/CMakeLists.txt
> +    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>)
If we don't care about the warning itself, we can probably just silence any warnings with: 

```suggestion
target_include_directories(yaml-cpp
  SYSTEM PUBLIC
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
  PRIVATE
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>)

```

2024-04-23 21:43 UTC, JacobDomagala commented on lib/yaml-cpp/CMakeLists.txt
> +    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>)
There's a duplication of logs now that we've added verbose builds. Most recent icpx is now clean.

2024-04-30 16:42 UTC, cwschilly commented on lib/yaml-cpp/CMakeLists.txt
> +    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>)
Thanks @JacobDomagala , I made this change

2024-04-30 22:56 UTC, lifflander commented
Summary of our discussion:
- Let's output the current configuration as a YAML file
- Use this output for testing input is working properly
- For the debug print configuration, take a list of components to output debug print statements
- Create further nesting for inputs, like the "LB Data Output"/"Statistics"/"LB Data Input"

2024-06-12 14:08 UTC, cz4rs commented
@cwschilly I have started to look at this, I will finish the review and post the comments tomorrow.

2024-06-18 19:59 UTC, cz4rs commented on lib/yaml-cpp/.clang-format
> +---
Let's not add any dotfiles from the library.

2024-06-18 20:05 UTC, cz4rs commented
> The order of precedence is currently
> 
>     1. input yaml
> 
>     2. command line arguments
> 
>     3. input `toml` or `ini` file,
> 
> 
> meaning that the YAML will overwrite the command line arguments (which in turn overwrite the input `toml` file).

Intuitively I'd expect the command line arguments to overwrite the configuration files. Whatever the order ends up being, this needs to be mentioned explicitly in the docs and possibly in usage / help message in the library.

2024-06-18 20:10 UTC, cz4rs commented on cmake/load_bundled_libraries.cmake
> +add_subdirectory(${PROJECT_LIB_DIR}/yaml-cpp)
> Should we support using external `yaml-cpp`? Same way we intent to do with `fmt` (#2221)

Getting back to this question. Current approach is to always use bundled version, can we expect any issues in the applications because of this?

2024-06-18 20:18 UTC, cz4rs commented on cmake/link_vt.cmake
> +    ARG "${noValOption}" "${singleValArg}" "${multiValueArg}" ${ARGN}
Curious that it didn't cause any bugs before :thinking:
Maybe no one uses `vt` with `CUSTOM_LINK_ARGS`.

2024-06-18 20:25 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  auto yaml_description = "Read in a yaml config file for VT";
```suggestion
  auto yaml_description = "Read in a YAML config file for VT";
```

2024-06-18 21:05 UTC, cz4rs commented on tests/unit/test_helpers.h
> +          EXPECT_TRUE(false);
Provide a clear error message for this case.

2024-06-18 21:10 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +        if (int_iter == 1) appConfig.vt_user_int_1 = user_input;
Place the instruction in a separate line after an `if` or `else`:
```suggestion
        if (int_iter == 1)
          appConfig.vt_user_int_1 = user_input;
```

2024-06-18 21:14 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +        if (int_iter == 1) appConfig.vt_user_int_1 = user_input;
When in doubt you can use `clang-format` (for example `git clang-format HEAD~1`). Note that the `.clang-format` configuration file we have does not reflect `vt`'s formatting style perfectly :shrug:

2024-06-19 17:51 UTC, cz4rs commented on src/vt/configs/arguments/app_config.h
> +  std::string vt_input_config_yaml = "";
This should probably be the only change in this header, all other should be moved elsewhere (preferably .cpp file to avoid pulling in `yaml-cpp` header).

2024-06-19 17:55 UTC, cz4rs commented on src/vt/configs/arguments/app_config.h
> +  std::vector<std::string> splitString(std::string input_str) {
Take a look at the existing `DemanglerUtils::splitString`.

2024-06-19 18:13 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  }
Use `vtAbortIf` here (we almost never use exceptions for error handling in `vt`).

2024-06-19 18:20 UTC, cz4rs commented on tests/unit/runtime/test_initialization.cc
> +    cfg_file_ << "Output Control:\n"
Use raw string literal so you don't have to use `<<` and `\n` everywhere.

2024-06-19 18:24 UTC, cz4rs commented on tests/unit/runtime/test_initialization.cc
> +TEST_F(TestInitialization, test_initialize_with_yaml) {
We need a test that shows order of precedence too. No need to test all combinations, but at least case that has `yaml`, `toml` and command line args.

2024-06-19 18:28 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +    } catch(...) {
Catch a specific class of exceptions if possible.

2024-06-19 18:34 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_debug_gen = (std::find(debug_enables.begin(), debug_enables.end(), "gen") != debug_enables.end());
You can wrap this `std::find` call in a lambda that captures `debug_enables` and takes the string as a parameter.

2024-06-19 18:37 UTC, cz4rs commented on lib/yaml-cpp/include/yaml-cpp/null.h
> +extern YAML_CPP_API _Null BaseNull;
It seems like the author is refusing to fix this upstream, so there's not much else to be done.

2024-06-19 18:45 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_color = output_control["Color"].as<bool>(true);
Consider what happens when user passes `--vt_color=false` in the command line.

Use current value of configuration variable as fallback:
```suggestion
  appConfig.vt_color = output_control["Color"].as<bool>(appConfig.vt_color);
```
This should make sense whatever order of precedence we end up with.

2024-06-19 18:49 UTC, cz4rs requested changes
@cwschilly Plenty of smaller changes requested.
I will still try to think of a couple more :wink: 

The "Should we support using external `yaml-cpp`" question should probably be brought up on Slack, because it might get lost among other comments here.

2024-06-19 19:15 UTC, cz4rs commented on src/vt/configs/arguments/app_config.h
> +  std::string vt_input_config_yaml = "";
`args.cc` looks like the right place for the conversion code.

2024-06-19 19:16 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_print_memory_each_phase = memory_usage_reporting["Print Memory Each Phase"].as<bool>(false);
Duplication: all the option strings like "Print Memory Each Phase" are repeated `app_config.h`. Use named variables (possibly file scoped?).

2024-07-08 18:38 UTC, cwschilly commented on lib/yaml-cpp/.clang-format
> +---
Fixed

2024-07-08 18:38 UTC, cwschilly commented on cmake/link_vt.cmake
>    set(allKeywords ${noValOption} ${singleValArg} ${multiValueArg})
I could not find it being used anywhere, so I removed it

2024-07-08 18:38 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  auto yaml_description = "Read in a yaml config file for VT";
Fixed

2024-07-08 18:38 UTC, cwschilly commented on tests/unit/test_helpers.h
> +          EXPECT_TRUE(false);
Fixed

2024-07-08 18:39 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +        if (int_iter == 1) appConfig.vt_user_int_1 = user_input;
Fixed, thanks

2024-07-08 18:39 UTC, cwschilly commented on src/vt/configs/arguments/app_config.h
> +  std::string vt_input_config_yaml = "";
Fixed; all conversion code is now in `args.cc`

2024-07-08 18:39 UTC, cwschilly commented on src/vt/configs/arguments/app_config.h
> +  std::vector<std::string> splitString(std::string input_str) {
Fixed, thanks for pointing this out

2024-07-08 18:39 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  }
Fixed

2024-07-08 18:39 UTC, cwschilly commented on tests/unit/runtime/test_initialization.cc
> +    cfg_file_ << "Output Control:\n"
Fixed

2024-07-08 18:40 UTC, cwschilly commented on tests/unit/runtime/test_initialization.cc
> +TEST_F(TestInitialization, test_initialize_with_yaml) {
New test added that shows order of precedence of toml->args->yaml

2024-07-08 18:40 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +    } catch(...) {
Fixed

2024-07-08 18:40 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_debug_gen = (std::find(debug_enables.begin(), debug_enables.end(), "gen") != debug_enables.end());
Fixed

2024-07-08 18:40 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_color = output_control["Color"].as<bool>(true);
Fixed

2024-07-08 20:44 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_print_memory_each_phase = memory_usage_reporting["Print Memory Each Phase"].as<bool>(false);
Fixed; I've moved everything into `args.cc` and stored all YAML labels as variables at the start of the file.

2024-07-10 15:25 UTC, cwschilly commented on cmake/load_bundled_libraries.cmake
> +add_subdirectory(${PROJECT_LIB_DIR}/yaml-cpp)
I don't anticipate any issues with always using bundled version (this is the same logic we use with the CLI library). However, adding support for an external `yaml-cpp` lib will be done in follow-on issue #2322

2024-07-15 11:08 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  // Parse the YAML parameters
We need to document the order of precedence for the users. I'd suggest putting it in the usage string (`VtFormatter::make_usage` in `args.cc`).

2024-07-15 11:12 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  // Parse remaining args
Misleading comments: parsing happens later, this is just preparation:
```suggestion
  // setup CLI parsing
  addYamlConfig(app, appConfig);
```

2024-07-15 11:17 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
Actually, maybe you could move the `app.set_config(...)` call from line 293 to have the CLI::App setup in one place.

2024-07-15 11:33 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +    }
Extract that logic into a helper function:
```suggestion
      appConfig.vt_output_config_str = convertConfigToString(appConfig);
```

2024-07-15 11:35 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +void addYamlConfig(CLI::App& app, AppConfig& appConfig) {
Rename this for consistency:
```suggestion
void addYamlArgs(CLI::App& app, AppConfig& appConfig) {
```

2024-07-15 11:36 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +void parseYaml(AppConfig& appConfig, std::string inputFile) {
Make the string a const ref.

2024-07-15 11:40 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  // appConfig.vt_debug_replay = debug_print_configuration["Enable replay"].as<bool>(false);
Should this be removed or uncommented?

2024-07-15 11:46 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  // appConfig.vt_lb_run_lb_first_phase = load_balancing["vt_lb_run_lb_first_phase"].as<bool>(false);
Commented out.

2024-07-15 11:52 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_no_color = not output_control[vt_color_label].as<bool>(not appConfig.vt_no_color);
This uses `not` twice.

2024-07-15 11:53 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +static const std::string vt_no_color_label = "Color";
This should probably be:
```suggestion
static const std::string vt_no_color_label = "No color";
```

2024-07-15 11:54 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_no_color = not output_control[vt_color_label].as<bool>(not appConfig.vt_no_color);
Also, instead of negating value for `vt_color_label` we should probably just use `vt_no_color_label`.

2024-07-15 12:17 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_no_color = not output_control[vt_color_label].as<bool>(not appConfig.vt_no_color);
Alright, I took a better look at it and we can improve :crossed_fingers: the code here with a following lambda:
```cpp
  // read the config value from YAML using default (current) value as fallback
  auto update_config = [](
    auto& config_entry, std::string const& label, YAML::Node const& node
  ) {
    using config_type = std::remove_reference_t<decltype(config_entry)>;
    config_entry = node[label].as<config_type>(config_entry);
  };
```

This should make the code less repetitive and slightly easier to follow:
```cpp
  update_config(appConfig.vt_color, vt_color_label, output_control);
```

2024-07-15 12:19 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  auto is_debug_enabled = [&debug_enables](const std::string& debug_type) {
Maybe add a comment here that the default value for all `vt_debug_` categories is `false`, so we don't need to check current value.

2024-07-15 12:38 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  vtAbortIf(too_many_user_args, "Only three user-defined arguments of each type (bool, int, or string) are supported.");
Extract that into a separate function.

2024-07-15 12:40 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +      {"Output Control", vt_no_color_label, static_cast<variantArg_t>(not appConfig.vt_no_color)},
Incorrect negation.

2024-07-15 12:44 UTC, cz4rs commented on src/vt/configs/arguments/args.cc
> +  return output_config_string;
```suggestion
  return yaml_stream.str();
```

2024-07-15 14:57 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  // Parse the YAML parameters
Fixed

2024-07-15 14:57 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  // Parse remaining args
Fixed

2024-07-15 14:57 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +    }
Fixed

2024-07-15 14:57 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +void parseYaml(AppConfig& appConfig, std::string inputFile) {
Fixed

2024-07-15 14:58 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  // appConfig.vt_debug_replay = debug_print_configuration["Enable replay"].as<bool>(false);
Uncommented; fixed

2024-07-15 14:58 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  // appConfig.vt_lb_run_lb_first_phase = load_balancing["vt_lb_run_lb_first_phase"].as<bool>(false);
This parameter isn't present in `appConfig` so I've removed this line

2024-07-15 14:58 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  appConfig.vt_no_color = not output_control[vt_color_label].as<bool>(not appConfig.vt_no_color);
Fixed, thanks!

2024-07-15 14:58 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  auto is_debug_enabled = [&debug_enables](const std::string& debug_type) {
Fixed

2024-07-15 14:58 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  vtAbortIf(too_many_user_args, "Only three user-defined arguments of each type (bool, int, or string) are supported.");
Fixed

2024-07-15 14:59 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +  return output_config_string;
Fixed

2024-07-15 15:00 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +    auto yaml_val = std::get<2>(yaml_data);
Fixed

2024-07-15 15:00 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +      {"Output Control", vt_no_color_label, static_cast<variantArg_t>(not appConfig.vt_no_color)},
Fixed

2024-07-15 15:00 UTC, cwschilly commented on src/vt/configs/arguments/args.cc
> +static const std::string vt_no_color_label = "Color";
Fixed

2024-07-16 12:08 UTC, cz4rs approved these changes
Looks good to me!

2024-07-16 17:21 UTC, lifflander approved these changes
This is ready to merge.

2024-07-16 17:21 UTC, lifflander commented
@cwschilly Can you edit the wiki to add yaml-cpp as one of our dependencies?

2024-07-17 19:55 UTC, lifflander commented
Can you rebase this?

2024-07-18 02:31 UTC, merged