#2260: Enable one verbose build for each compiler type
DARMA-tasking/vt pull request #2263
Opened 2024-03-27 15:29 UTC by thearusable

2024-03-28 20:05 UTC, JacobDomagala commented
Should we use `PR tests (gcc-12, ubuntu, mpich)` for verbose? It's the PR that runs even in draft mode.

2024-03-29 09:46 UTC, thearusable commented
> Should we use `PR tests (gcc-12, ubuntu, mpich)` for verbose? It's the PR that runs even in draft mode.

@JacobDomagala Yes, I think that's a great idea. I'll make this gcc pipeline a verbose one.

2024-04-16 16:21 UTC, thearusable commented
Debug verbose logs are enabled for:
- clang-14
- gcc-12
- icpx
- nvcc-12

Verbose debug logs are being compiled for jobs on those compilers but they won't be printed on CI. Enabling verbose logging for all modules with `--vt_debug_all` will result in very verbose output which is hard to analyze.

2024-04-17 13:46 UTC, thearusable commented
@lifflander / @nlslatt - I poked a little bit to check why you have the issue with missing verbose logs. 

I only found that not all of the parameters are being passed when building docker images. But that's all I found. All configuration in CMake looks good to me. Every option is properly stored in CMake's cache and it's properly overridden when we pass a different value for a flag.

2024-04-17 22:03 UTC, lifflander requested changes

2024-04-17 22:03 UTC, lifflander commented on ci/azure/azure-intel-oneapi-icpx-ubuntu-mpich.yml
> +  VT_CI_BUILD: 0
I really don't like lying about whether this is a CI build, since that option may be used in the future for other things. Is there a different approach we can take to this?

2024-04-22 22:35 UTC, lifflander approved these changes

2024-04-22 22:35 UTC, merged