#2299: Change minimal load for triggering LB to minimal modeled object load divided by number of nodes.
DARMA-tasking/vt pull request #2333
Opened 2024-08-06 14:55 UTC by thearusable

Closes #2299

2024-08-06 17:15 UTC, cz4rs commented
@thearusable `invalid project name "DARMA-tasking/vt": must consist only of lowercase alphanumeric characters, hyphens, and underscores as well as start with a letter or number` strikes again :shrug:

2024-08-06 21:03 UTC, nlslatt requested changes
PR needs to target `develop`

2024-08-07 12:14 UTC, JacobDomagala commented
> > @thearusable `invalid project name "DARMA-tasking/vt": must consist only of lowercase alphanumeric characters, hyphens, and underscores as well as start with a letter or number` strikes again 🤷
> 
> @cz4rs The target branch of this PR is `2201-implement-memory-aware-temperedlb-in-vt-rebased`, which is over two months old. This likely explains the error.

@cz4rs @thearusable Not related to this PR but most recent (on develop) spack workflow failed with that message (https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=60702&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=1364e02f-4e1e-51cf-2821-fd252a3c0e34&l=10)

2024-08-07 12:25 UTC, thearusable commented
> > > @thearusable `invalid project name "DARMA-tasking/vt": must consist only of lowercase alphanumeric characters, hyphens, and underscores as well as start with a letter or number` strikes again 🤷
> > 
> > 
> > @cz4rs The target branch of this PR is `2201-implement-memory-aware-temperedlb-in-vt-rebased`, which is over two months old. This likely explains the error.
> 
> @cz4rs @thearusable Not related to this PR but most recent (on develop) spack workflow failed with that message (https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=60702&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=1364e02f-4e1e-51cf-2821-fd252a3c0e34&l=10)

@JacobDomagala I will take a look on that

2024-08-27 14:02 UTC, cz4rs approved these changes
Looks good to me.

2024-08-27 14:36 UTC, PhilMiller commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +    return 0.0000001;
This ideally would use std chrono types and literals. Barring that, at least use scientific notation and specify the units.

Also, I think 100ns is on the low side, but it really doesn't matter.

2024-08-27 14:36 UTC, PhilMiller commented on src/vt/vrt/collection/balance/greedylb/greedylb.cc
> +  if (avg_load > getCollectiveEpochCost()) {
I came here to note that I think calculation like this should use max load, rather than average. Otherwise, if a large-scale job has maximal imbalance of a very fine-grain problem, averaging might mask it.

2024-08-27 15:37 UTC, thearusable commented on src/vt/vrt/collection/balance/baselb/baselb.h
> +    return 0.0000001;
Ok, I changed it to `std::chrono::nanoseconds`.

2024-09-03 09:57 UTC, thearusable commented on src/vt/vrt/collection/balance/greedylb/greedylb.cc
> +  if (avg_load > getCollectiveEpochCost()) {
@lifflander What should we use in this case?

2024-09-03 17:19 UTC, thearusable commented on src/vt/vrt/collection/balance/greedylb/greedylb.cc
> +  if (avg_load > getCollectiveEpochCost()) {
After the discussion on the meeting, we should use the `max` load instead of `avg` load and move the logic for checking that to `BaseLB` to be used only by the real load balancers.

2024-09-05 18:54 UTC, lifflander approved these changes
Looks good to me!

2024-09-06 10:31 UTC, thearusable commented
@lifflander PR rebased. Ready to merge.

2024-09-06 16:30 UTC, merged