Add task measurements using linux perf
DARMA-tasking/vt pull request #2381
Opened 2024-12-13 12:24 UTC by pierrepebay

Fixes #2380.

This contains the work done in #2304 with only the Linux Perf component.

2024-12-17 20:24 UTC, lifflander requested changes
Looks good overall. A few minor improvements requested

2024-12-17 20:24 UTC, lifflander commented on src/vt/metrics/perf_data.cc
> +  for (const auto &event_name : event_names_) {
```suggestion
  for (auto const& event_name : event_names_) {
```

2024-12-17 20:24 UTC, lifflander commented on src/vt/metrics/perf_data.cc
> +  for (const auto &event_name : event_names_) {
```suggestion
  for (auto const& event_name : event_names_) {
```

2024-12-17 20:24 UTC, lifflander commented on src/vt/metrics/perf_data.h
> +  ~PerfData();
Need a virtual destructor here.

2025-01-21 15:39 UTC, cz4rs commented
@pierrepebay I was unable to reproduce the failures from both `clang-9` and `clang-10` builds (with identical settings as the workflows use). The tests pass just fine locally.

2025-01-27 17:44 UTC, cz4rs commented
@pierrepebay See this for an example use of `GTEST_SKIP`:
https://github.com/DARMA-tasking/vt/blob/e4e445f0b4c61a1592df35557bf4cee43c8b07d3/tests/unit/trace/test_runnable_context_trace.cc#L61-L63

2025-01-30 00:04 UTC, lifflander approved these changes

2025-02-03 18:22 UTC, cz4rs commented on src/vt/metrics/perf_data.cc
> +    {
The formatting here is still incorrect:
```suggestion
    while (std::getline(ss, item, ',')) {
```

2025-02-03 18:23 UTC, cz4rs commented on src/vt/metrics/perf_data.cc
> +{
```suggestion
  : event_map_(example_event_map) {
```

2025-02-03 18:27 UTC, cz4rs approved these changes
Looks good to me.

2025-02-06 18:42 UTC, merged