990 nompi tests
DARMA-tasking/vt pull request #998
Opened 2020-08-20 06:18 UTC by pnstickne

2020-08-20 06:24 UTC, pnstickne commented on tests/CMakeLists.txt
> +        FAIL_REGULAR_EXPRESSION "FAILED;should be deleted but never is;Segmentation fault"
I always wonder about that line..

2020-08-20 07:22 UTC, cz4rs commented on tests/unit/lb/test_lb_reader.nompi.cc
> -#include "test_parallel_harness.h"
`#include "test_harness.h"` needed now

2020-08-20 07:31 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/lb/test_lb_reader.nompi.cc  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6043112&bid=19800449)

2020-08-20 07:33 UTC, cz4rs commented
I have switched `test_lb_reader.cc` to parallel harness to get proper initialization before running the test
- when you include TestHarness header, you will start getting segfaults - it's because `theConfig()` is used directly here both by tested code and in test setup (getting LB file name, debug printing)
- this means that in order to ditch parallel harness, we have to get `theConfig` and `theContext` components properly initialized in some other way

sample stacktrace:
```gdb
Program received signal SIGSEGV, Segmentation fault.
0x0000555555fea37c in vt::theConfig () at ../src/vt/runtime/runtime_get.cc:136
136     vt::arguments::AppConfig*   theConfig()             { return &CUR_RT->theArgConfig->config_;      }
(gdb) bt
#0  0x0000555555fea37c in vt::theConfig () at ../src/vt/runtime/runtime_get.cc:136
#1  0x0000555555f97407 in vt::tests::unit::TestLBReader_test_lb_read_1_Test::TestBody (this=0x555556a97d50) at ../tests/unit/lb/test_lb_reader.cc:98
#2  0x0000555555fd633b in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x555556a97d50, method=&virtual testing::Test::TestBody(), 
    location=0x555556660ff3 "the test body") at ../tests/extern/googletest/googletest/src/gtest.cc:2433
#3  0x0000555555fcee51 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x555556a97d50, method=&virtual testing::Test::TestBody(), 
    location=0x555556660ff3 "the test body") at ../tests/extern/googletest/googletest/src/gtest.cc:2469
#4  0x0000555555fa9c8c in testing::Test::Run (this=0x555556a97d50) at ../tests/extern/googletest/googletest/src/gtest.cc:2508
#5  0x0000555555faa677 in testing::TestInfo::Run (this=0x555556a85fa0) at ../tests/extern/googletest/googletest/src/gtest.cc:2684
#6  0x0000555555faadb2 in testing::TestSuite::Run (this=0x555556a86430) at ../tests/extern/googletest/googletest/src/gtest.cc:2816
#7  0x0000555555fb6e6e in testing::internal::UnitTestImpl::RunAllTests (this=0x555556a860f0) at ../tests/extern/googletest/googletest/src/gtest.cc:5338
#8  0x0000555555fd7864 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x555556a860f0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x555555fb6a66 <testing::internal::UnitTestImpl::RunAllTests()>, 
    location=0x555556661a30 "auxiliary test code (environments or event listeners)") at ../tests/extern/googletest/googletest/src/gtest.cc:2433
#9  0x0000555555fd008f in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x555556a860f0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x555555fb6a66 <testing::internal::UnitTestImpl::RunAllTests()>, 
    location=0x555556661a30 "auxiliary test code (environments or event listeners)") at ../tests/extern/googletest/googletest/src/gtest.cc:2469
#10 0x0000555555fb56ae in testing::UnitTest::Run (this=0x555556a70e40 <testing::UnitTest::GetInstance()::instance>) at ../tests/extern/googletest/googletest/src/gtest.cc:4925
#11 0x0000555555f77623 in RUN_ALL_TESTS () at ../tests/extern/googletest/googletest/include/gtest/gtest.h:2473
#12 0x0000555555f76967 in main (argc=1, argv=0x7fffffffda98) at ../tests/unit/main.cc:70
```

2020-08-20 10:14 UTC, cz4rs commented
@pnstickne 
some more thoughts on `test_lb_reader.cc`:
the LB reader tests have been unstable for some time (I believe this is independent from changing the test harness, although it could have made the issue worse)

I have run them locally a couple of times and they fail quite regularly because of some file reading problems:
```
vt: [2] ------------------------------------------------------------------------------------------------------------------------
vt: [2] ------------------------------------------- Runtime Error: System Aborting! --------------------------------------------
vt: [2] ------------------------------------------------ Fatal Error on Node 2 -------------------------------------------------
vt: [2] ------------------------------------------------------------------------------------------------------------------------
vt: [2] 
vt: [2]              Reason: Valid LB not found: "name="

vt: [2]                Type: vtAbort() Invoked
vt: [2]                Node: 2
vt: [2]           Num Nodes: 4
vt: [2]                File: ../src/vt/vrt/collection/balance/read_lb.cc
vt: [2]                Line: 211
vt: [2]            Function: readFile
```
I think this could be extracted into a separate issue with 2 goals:
- remove parallel harness and make this `nompi` test 
- improve file handling in the test code (using unique names / temporary files as suggested by Phil during weekly meeting)

2020-08-23 19:06 UTC, pnstickne commented on tests/unit/lb/test_lb_reader.nompi.cc
> -#include "test_parallel_harness.h"
Should be resolved once merged over #990.

2020-08-23 19:08 UTC, pnstickne commented on src/vt/runtime/runtime_get.cc
> +namespace vt { namespace debug {
Only mean to be used from the debug/diagnostic code, hence the `vt::debug` namespace. This also aligns with `vt::debug::preNode`. Only single access is exposed, freeing singular-use case sites of logic.

2020-08-23 19:09 UTC, pnstickne commented on src/vt/runtime/runtime_get.cc
> -#undef CUR_RT
Not relevant to undef in .cc

2020-08-23 19:11 UTC, pnstickne commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +  bool has_spec = ReadLBSpec::openSpec(theConfig()->vt_lb_file_name);
Usage sites must specify the file. This also avoids different paths of accessing the file which were (strictly by usage), all resolved from `theConfig()->vt_lb_file_name`.

This also NOW does a _read_, as the only core usages always followed up a `hasSpec` with an implicit read (inside, eg. `entry`).

2020-08-23 19:33 UTC, pnstickne commented on tests/unit/lb/test_lb_reader.nompi.cc
> -#include "test_parallel_harness.h"
Re-updated.

2020-08-24 08:14 UTC, cz4rs commented on src/vt/vrt/collection/balance/read_lb.cc
> +  if (filename.empty()) {
this check seems to be necessary, but maybe this could be rearranged for more clarity

2020-08-24 08:16 UTC, cz4rs commented on src/vt/vrt/collection/balance/read_lb.cc
> +  if (filename.empty()) {
maybe checking for `filename.empty()` first would be better?

2020-08-24 08:22 UTC, cz4rs commented on src/vt/vrt/collection/balance/read_lb.h
> +   * \brief Prepare the spec for reading, if it exists.
missing `\param` comment

2020-08-24 08:25 UTC, cz4rs commented on src/vt/vrt/collection/balance/read_lb.cc
> +    return "";
debug warning like "No LB Spec is open, returning empty string" could be good, also - this can be moved before declaration of `ss`

2020-08-24 08:30 UTC, cz4rs commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +  bool has_spec = ReadLBSpec::openSpec(theConfig()->vt_lb_file_name);
looks good, please update the doxygen comment in `read_lb.h` accordingly

2020-08-24 15:53 UTC, cz4rs requested changes
the builds look fine and the PR looks good overall, only minor comments to address

2020-08-25 07:10 UTC, pnstickne commented on src/vt/vrt/collection/balance/read_lb.h
> +   * \brief Prepare the spec for reading, if it exists.
Updated docs.

2020-08-25 07:10 UTC, pnstickne commented on src/vt/vrt/collection/balance/read_lb.cc
> +    return "";
Now returns "[No LB Spec open]".

2020-08-25 07:10 UTC, pnstickne commented on src/vt/vrt/collection/balance/read_lb.cc
> +  if (filename.empty()) {
Ordered for reading.

2020-08-25 07:10 UTC, pnstickne commented on src/vt/vrt/collection/balance/baselb/baselb.cc
> +  bool has_spec = ReadLBSpec::openSpec(theConfig()->vt_lb_file_name);
Updated docs.

2020-08-25 07:12 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/lb/test_lb_reader.nompi.cc  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6043112&bid=19800449)

2020-08-25 10:52 UTC, cz4rs approved these changes

2020-08-25 15:34 UTC, JacobDomagala approved these changes

2020-08-25 18:48 UTC, lifflander commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/lb/test_lb_reader.nompi.cc  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6043112&bid=19800449)

2020-08-25 20:22 UTC, merged